/**
 * @civfix/ui/i18n barrel — the i18n engine shared by web (react-native-web) + mobile (React Native).
 *
 * The host mounts <I18nProvider locale={…} setLocale={…}> high in the tree; shared bodies + host screens
 * call `useT('<namespace>')` for copy, `useLocale()` for the active locale + switcher action, and
 * `useRelativeTime()` for localized "ago" labels. `resolveLocale` + `supportedLocales` back the host's
 * device/browser detection and the LanguageSettingsBody radio list.
 *
 * Catalogs live under ./locales/<lng>/<ns>.json; resources.ts (generated by
 * scripts/gen-i18n-resources.mjs) assembles them. config.ts wires fallback/ns/interpolation.
 */
export { I18nProvider } from "./I18nProvider"
export type { I18nProviderProps } from "./I18nProvider"

export { useT } from "./useT"
// Re-export <Trans> so call sites compose rich (component-interpolated) copy without
// importing react-i18next directly — that dep lives in @civfix/ui, not the app repos.
export { Trans } from "react-i18next"
export { useLocale } from "./LocaleContext"
export type { LocaleContextValue } from "./LocaleContext"

export { useRelativeTime } from "./useRelativeTime"
export type { UseRelativeTime } from "./useRelativeTime"

export { resolveLocale, supportedLocales, FALLBACK_LOCALE } from "./resolveLocale"
export { resolveActiveLocale } from "./resolveActiveLocale"
export type { LocaleSources } from "./resolveActiveLocale"
export { createI18n, defaultNS } from "./config"

// Re-export the contract locale type so consumers can `import { SupportedLocale } from "@civfix/ui/i18n"`.
export type { SupportedLocale } from "@civfix/shared"
