/**
 * AUTO-GENERATED by scripts/gen-i18n-resources.mjs: DO NOT EDIT BY HAND.
 *
 * Re-run `pnpm --filter @civfix/ui i18n:gen` after adding or removing a namespace or locale.
 */
import type { Resource } from "i18next"

import en from "./catalogs/en"
import es from "./catalogs/es"
import de from "./catalogs/de"
import ko from "./catalogs/ko"

export { namespaces } from "./catalogs/namespaces"

/** Every locale assembled statically: locale -> namespace -> catalog object. */
export const resources: Resource = {
  en,
  es,
  de,
  ko,
}
