/**
 * AUTO-GENERATED by scripts/gen-i18n-resources.mjs — DO NOT EDIT BY HAND.
 *
 * Re-run `node scripts/gen-i18n-resources.mjs` after adding/removing a namespace or locale. It scans
 * src/i18n/locales/<lng>/<ns>.json and emits static imports (Metro-safe; no dynamic require) assembled
 * into the i18next `resources` object + the `namespaces` list config.ts feeds to `ns`.
 */
import type { Resource } from "i18next"

import en_about from "./locales/en/about.json"
import en_account_blocked from "./locales/en/account-blocked.json"
import en_account_delete from "./locales/en/account-delete.json"
import en_appearance_settings from "./locales/en/appearance-settings.json"
import en_channel_create from "./locales/en/channel-create.json"
import en_common from "./locales/en/common.json"
import en_common_datetime from "./locales/en/common-datetime.json"
import en_common_search from "./locales/en/common-search.json"
import en_common_share from "./locales/en/common-share.json"
import en_conversation from "./locales/en/conversation.json"
import en_conversation_mentions from "./locales/en/conversation-mentions.json"
import en_conversation_polls from "./locales/en/conversation-polls.json"
import en_conversation_reactions from "./locales/en/conversation-reactions.json"
import en_discussion from "./locales/en/discussion.json"
import en_discussion_composer from "./locales/en/discussion-composer.json"
import en_discussion_delete from "./locales/en/discussion-delete.json"
import en_donations from "./locales/en/donations.json"
import en_enums from "./locales/en/enums.json"
import en_event_bring from "./locales/en/event-bring.json"
import en_event_cancel from "./locales/en/event-cancel.json"
import en_event_card from "./locales/en/event-card.json"
import en_event_create from "./locales/en/event-create.json"
import en_event_dashboard from "./locales/en/event-dashboard.json"
import en_event_detail from "./locales/en/event-detail.json"
import en_event_edit from "./locales/en/event-edit.json"
import en_event_form from "./locales/en/event-form.json"
import en_event_guest_rsvp from "./locales/en/event-guest-rsvp.json"
import en_event_list from "./locales/en/event-list.json"
import en_event_members from "./locales/en/event-members.json"
import en_event_resources from "./locales/en/event-resources.json"
import en_event_rsvp from "./locales/en/event-rsvp.json"
import en_event_slots from "./locales/en/event-slots.json"
import en_group_create from "./locales/en/group-create.json"
import en_group_info from "./locales/en/group-info.json"
import en_home_feed from "./locales/en/home-feed.json"
import en_home_sidebar from "./locales/en/home-sidebar.json"
import en_host_analytics from "./locales/en/host-analytics.json"
import en_host_attendees from "./locales/en/host-attendees.json"
import en_host_broadcasts from "./locales/en/host-broadcasts.json"
import en_host_checkin from "./locales/en/host-checkin.json"
import en_host_common from "./locales/en/host-common.json"
import en_host_event from "./locales/en/host-event.json"
import en_host_exports from "./locales/en/host-exports.json"
import en_host_mode from "./locales/en/host-mode.json"
import en_host_org from "./locales/en/host-org.json"
import en_host_page_builder from "./locales/en/host-page-builder.json"
import en_host_payments from "./locales/en/host-payments.json"
import en_host_portfolio from "./locales/en/host-portfolio.json"
import en_host_settings from "./locales/en/host-settings.json"
import en_host_team from "./locales/en/host-team.json"
import en_host_ticket from "./locales/en/host-ticket.json"
import en_host_tickets from "./locales/en/host-tickets.json"
import en_language_settings from "./locales/en/language-settings.json"
import en_leaderboard from "./locales/en/leaderboard.json"
import en_lightbox from "./locales/en/lightbox.json"
import en_map_address from "./locales/en/map-address.json"
import en_map_ui from "./locales/en/map-ui.json"
import en_messages_list from "./locales/en/messages-list.json"
import en_mobile_a11y from "./locales/en/mobile-a11y.json"
import en_mobile_auth_otp from "./locales/en/mobile-auth-otp.json"
import en_mobile_auth_registration from "./locales/en/mobile-auth-registration.json"
import en_mobile_auth_signin from "./locales/en/mobile-auth-signin.json"
import en_mobile_auth_welcome from "./locales/en/mobile-auth-welcome.json"
import en_mobile_branding from "./locales/en/mobile-branding.json"
import en_mobile_errors from "./locales/en/mobile-errors.json"
import en_mobile_onboarding from "./locales/en/mobile-onboarding.json"
import en_mobile_report_camera from "./locales/en/mobile-report-camera.json"
import en_mobile_system from "./locales/en/mobile-system.json"
import en_nav from "./locales/en/nav.json"
import en_notifications from "./locales/en/notifications.json"
import en_notifications_prefs from "./locales/en/notifications-prefs.json"
import en_onboarding_age from "./locales/en/onboarding-age.json"
import en_onboarding_terms from "./locales/en/onboarding-terms.json"
import en_post_composer from "./locales/en/post-composer.json"
import en_profile from "./locales/en/profile.json"
import en_profile_connections from "./locales/en/profile-connections.json"
import en_profile_follow from "./locales/en/profile-follow.json"
import en_profile_person from "./locales/en/profile-person.json"
import en_profile_view from "./locales/en/profile-view.json"
import en_report_cluster from "./locales/en/report-cluster.json"
import en_report_content from "./locales/en/report-content.json"
import en_report_detail from "./locales/en/report-detail.json"
import en_report_linked from "./locales/en/report-linked.json"
import en_report_picker from "./locales/en/report-picker.json"
import en_report_list from "./locales/en/report-list.json"
import en_report_row from "./locales/en/report-row.json"
import en_report_wizard from "./locales/en/report-wizard.json"
import en_search from "./locales/en/search.json"
import en_settings from "./locales/en/settings.json"
import en_settings_account from "./locales/en/settings-account.json"
import en_settings_privacy from "./locales/en/settings-privacy.json"
import en_share_post from "./locales/en/share-post.json"
import en_volunteer_hours from "./locales/en/volunteer-hours.json"
import en_web_auth from "./locales/en/web-auth.json"
import en_web_claims from "./locales/en/web-claims.json"
import en_web_common from "./locales/en/web-common.json"
import en_web_errors from "./locales/en/web-errors.json"
import en_web_registration from "./locales/en/web-registration.json"
import en_web_service_record from "./locales/en/web-service-record.json"
import es_about from "./locales/es/about.json"
import es_account_blocked from "./locales/es/account-blocked.json"
import es_account_delete from "./locales/es/account-delete.json"
import es_appearance_settings from "./locales/es/appearance-settings.json"
import es_channel_create from "./locales/es/channel-create.json"
import es_common from "./locales/es/common.json"
import es_common_datetime from "./locales/es/common-datetime.json"
import es_common_search from "./locales/es/common-search.json"
import es_common_share from "./locales/es/common-share.json"
import es_conversation from "./locales/es/conversation.json"
import es_conversation_mentions from "./locales/es/conversation-mentions.json"
import es_conversation_polls from "./locales/es/conversation-polls.json"
import es_conversation_reactions from "./locales/es/conversation-reactions.json"
import es_discussion from "./locales/es/discussion.json"
import es_discussion_composer from "./locales/es/discussion-composer.json"
import es_discussion_delete from "./locales/es/discussion-delete.json"
import es_donations from "./locales/es/donations.json"
import es_enums from "./locales/es/enums.json"
import es_event_bring from "./locales/es/event-bring.json"
import es_event_cancel from "./locales/es/event-cancel.json"
import es_event_card from "./locales/es/event-card.json"
import es_event_create from "./locales/es/event-create.json"
import es_event_dashboard from "./locales/es/event-dashboard.json"
import es_event_detail from "./locales/es/event-detail.json"
import es_event_edit from "./locales/es/event-edit.json"
import es_event_form from "./locales/es/event-form.json"
import es_event_guest_rsvp from "./locales/es/event-guest-rsvp.json"
import es_event_list from "./locales/es/event-list.json"
import es_event_members from "./locales/es/event-members.json"
import es_event_resources from "./locales/es/event-resources.json"
import es_event_rsvp from "./locales/es/event-rsvp.json"
import es_event_slots from "./locales/es/event-slots.json"
import es_group_create from "./locales/es/group-create.json"
import es_group_info from "./locales/es/group-info.json"
import es_home_feed from "./locales/es/home-feed.json"
import es_home_sidebar from "./locales/es/home-sidebar.json"
import es_host_analytics from "./locales/es/host-analytics.json"
import es_host_attendees from "./locales/es/host-attendees.json"
import es_host_broadcasts from "./locales/es/host-broadcasts.json"
import es_host_checkin from "./locales/es/host-checkin.json"
import es_host_common from "./locales/es/host-common.json"
import es_host_event from "./locales/es/host-event.json"
import es_host_exports from "./locales/es/host-exports.json"
import es_host_mode from "./locales/es/host-mode.json"
import es_host_org from "./locales/es/host-org.json"
import es_host_page_builder from "./locales/es/host-page-builder.json"
import es_host_payments from "./locales/es/host-payments.json"
import es_host_portfolio from "./locales/es/host-portfolio.json"
import es_host_settings from "./locales/es/host-settings.json"
import es_host_team from "./locales/es/host-team.json"
import es_host_ticket from "./locales/es/host-ticket.json"
import es_host_tickets from "./locales/es/host-tickets.json"
import es_language_settings from "./locales/es/language-settings.json"
import es_leaderboard from "./locales/es/leaderboard.json"
import es_lightbox from "./locales/es/lightbox.json"
import es_map_address from "./locales/es/map-address.json"
import es_map_ui from "./locales/es/map-ui.json"
import es_messages_list from "./locales/es/messages-list.json"
import es_mobile_a11y from "./locales/es/mobile-a11y.json"
import es_mobile_auth_otp from "./locales/es/mobile-auth-otp.json"
import es_mobile_auth_registration from "./locales/es/mobile-auth-registration.json"
import es_mobile_auth_signin from "./locales/es/mobile-auth-signin.json"
import es_mobile_auth_welcome from "./locales/es/mobile-auth-welcome.json"
import es_mobile_branding from "./locales/es/mobile-branding.json"
import es_mobile_errors from "./locales/es/mobile-errors.json"
import es_mobile_onboarding from "./locales/es/mobile-onboarding.json"
import es_mobile_report_camera from "./locales/es/mobile-report-camera.json"
import es_mobile_system from "./locales/es/mobile-system.json"
import es_nav from "./locales/es/nav.json"
import es_notifications from "./locales/es/notifications.json"
import es_notifications_prefs from "./locales/es/notifications-prefs.json"
import es_onboarding_age from "./locales/es/onboarding-age.json"
import es_onboarding_terms from "./locales/es/onboarding-terms.json"
import es_post_composer from "./locales/es/post-composer.json"
import es_profile from "./locales/es/profile.json"
import es_profile_connections from "./locales/es/profile-connections.json"
import es_profile_follow from "./locales/es/profile-follow.json"
import es_profile_person from "./locales/es/profile-person.json"
import es_profile_view from "./locales/es/profile-view.json"
import es_report_cluster from "./locales/es/report-cluster.json"
import es_report_content from "./locales/es/report-content.json"
import es_report_detail from "./locales/es/report-detail.json"
import es_report_linked from "./locales/es/report-linked.json"
import es_report_picker from "./locales/es/report-picker.json"
import es_report_list from "./locales/es/report-list.json"
import es_report_row from "./locales/es/report-row.json"
import es_report_wizard from "./locales/es/report-wizard.json"
import es_search from "./locales/es/search.json"
import es_settings from "./locales/es/settings.json"
import es_settings_account from "./locales/es/settings-account.json"
import es_settings_privacy from "./locales/es/settings-privacy.json"
import es_share_post from "./locales/es/share-post.json"
import es_volunteer_hours from "./locales/es/volunteer-hours.json"
import es_web_auth from "./locales/es/web-auth.json"
import es_web_claims from "./locales/es/web-claims.json"
import es_web_common from "./locales/es/web-common.json"
import es_web_errors from "./locales/es/web-errors.json"
import es_web_registration from "./locales/es/web-registration.json"
import es_web_service_record from "./locales/es/web-service-record.json"
import de_about from "./locales/de/about.json"
import de_account_blocked from "./locales/de/account-blocked.json"
import de_account_delete from "./locales/de/account-delete.json"
import de_appearance_settings from "./locales/de/appearance-settings.json"
import de_channel_create from "./locales/de/channel-create.json"
import de_common from "./locales/de/common.json"
import de_common_datetime from "./locales/de/common-datetime.json"
import de_common_search from "./locales/de/common-search.json"
import de_common_share from "./locales/de/common-share.json"
import de_conversation from "./locales/de/conversation.json"
import de_conversation_mentions from "./locales/de/conversation-mentions.json"
import de_conversation_polls from "./locales/de/conversation-polls.json"
import de_conversation_reactions from "./locales/de/conversation-reactions.json"
import de_discussion from "./locales/de/discussion.json"
import de_discussion_composer from "./locales/de/discussion-composer.json"
import de_discussion_delete from "./locales/de/discussion-delete.json"
import de_donations from "./locales/de/donations.json"
import de_enums from "./locales/de/enums.json"
import de_event_bring from "./locales/de/event-bring.json"
import de_event_cancel from "./locales/de/event-cancel.json"
import de_event_card from "./locales/de/event-card.json"
import de_event_create from "./locales/de/event-create.json"
import de_event_dashboard from "./locales/de/event-dashboard.json"
import de_event_detail from "./locales/de/event-detail.json"
import de_event_edit from "./locales/de/event-edit.json"
import de_event_form from "./locales/de/event-form.json"
import de_event_guest_rsvp from "./locales/de/event-guest-rsvp.json"
import de_event_list from "./locales/de/event-list.json"
import de_event_members from "./locales/de/event-members.json"
import de_event_resources from "./locales/de/event-resources.json"
import de_event_rsvp from "./locales/de/event-rsvp.json"
import de_event_slots from "./locales/de/event-slots.json"
import de_group_create from "./locales/de/group-create.json"
import de_group_info from "./locales/de/group-info.json"
import de_home_feed from "./locales/de/home-feed.json"
import de_home_sidebar from "./locales/de/home-sidebar.json"
import de_host_analytics from "./locales/de/host-analytics.json"
import de_host_attendees from "./locales/de/host-attendees.json"
import de_host_broadcasts from "./locales/de/host-broadcasts.json"
import de_host_checkin from "./locales/de/host-checkin.json"
import de_host_common from "./locales/de/host-common.json"
import de_host_event from "./locales/de/host-event.json"
import de_host_exports from "./locales/de/host-exports.json"
import de_host_mode from "./locales/de/host-mode.json"
import de_host_org from "./locales/de/host-org.json"
import de_host_page_builder from "./locales/de/host-page-builder.json"
import de_host_payments from "./locales/de/host-payments.json"
import de_host_portfolio from "./locales/de/host-portfolio.json"
import de_host_settings from "./locales/de/host-settings.json"
import de_host_team from "./locales/de/host-team.json"
import de_host_ticket from "./locales/de/host-ticket.json"
import de_host_tickets from "./locales/de/host-tickets.json"
import de_language_settings from "./locales/de/language-settings.json"
import de_leaderboard from "./locales/de/leaderboard.json"
import de_lightbox from "./locales/de/lightbox.json"
import de_map_address from "./locales/de/map-address.json"
import de_map_ui from "./locales/de/map-ui.json"
import de_messages_list from "./locales/de/messages-list.json"
import de_mobile_a11y from "./locales/de/mobile-a11y.json"
import de_mobile_auth_otp from "./locales/de/mobile-auth-otp.json"
import de_mobile_auth_registration from "./locales/de/mobile-auth-registration.json"
import de_mobile_auth_signin from "./locales/de/mobile-auth-signin.json"
import de_mobile_auth_welcome from "./locales/de/mobile-auth-welcome.json"
import de_mobile_branding from "./locales/de/mobile-branding.json"
import de_mobile_errors from "./locales/de/mobile-errors.json"
import de_mobile_onboarding from "./locales/de/mobile-onboarding.json"
import de_mobile_report_camera from "./locales/de/mobile-report-camera.json"
import de_mobile_system from "./locales/de/mobile-system.json"
import de_nav from "./locales/de/nav.json"
import de_notifications from "./locales/de/notifications.json"
import de_notifications_prefs from "./locales/de/notifications-prefs.json"
import de_onboarding_age from "./locales/de/onboarding-age.json"
import de_onboarding_terms from "./locales/de/onboarding-terms.json"
import de_post_composer from "./locales/de/post-composer.json"
import de_profile from "./locales/de/profile.json"
import de_profile_connections from "./locales/de/profile-connections.json"
import de_profile_follow from "./locales/de/profile-follow.json"
import de_profile_person from "./locales/de/profile-person.json"
import de_profile_view from "./locales/de/profile-view.json"
import de_report_cluster from "./locales/de/report-cluster.json"
import de_report_content from "./locales/de/report-content.json"
import de_report_detail from "./locales/de/report-detail.json"
import de_report_linked from "./locales/de/report-linked.json"
import de_report_picker from "./locales/de/report-picker.json"
import de_report_list from "./locales/de/report-list.json"
import de_report_row from "./locales/de/report-row.json"
import de_report_wizard from "./locales/de/report-wizard.json"
import de_search from "./locales/de/search.json"
import de_settings from "./locales/de/settings.json"
import de_settings_account from "./locales/de/settings-account.json"
import de_settings_privacy from "./locales/de/settings-privacy.json"
import de_share_post from "./locales/de/share-post.json"
import de_volunteer_hours from "./locales/de/volunteer-hours.json"
import de_web_auth from "./locales/de/web-auth.json"
import de_web_claims from "./locales/de/web-claims.json"
import de_web_common from "./locales/de/web-common.json"
import de_web_errors from "./locales/de/web-errors.json"
import de_web_registration from "./locales/de/web-registration.json"
import de_web_service_record from "./locales/de/web-service-record.json"
import ko_about from "./locales/ko/about.json"
import ko_account_blocked from "./locales/ko/account-blocked.json"
import ko_account_delete from "./locales/ko/account-delete.json"
import ko_appearance_settings from "./locales/ko/appearance-settings.json"
import ko_channel_create from "./locales/ko/channel-create.json"
import ko_common from "./locales/ko/common.json"
import ko_common_datetime from "./locales/ko/common-datetime.json"
import ko_common_search from "./locales/ko/common-search.json"
import ko_common_share from "./locales/ko/common-share.json"
import ko_conversation from "./locales/ko/conversation.json"
import ko_conversation_mentions from "./locales/ko/conversation-mentions.json"
import ko_conversation_polls from "./locales/ko/conversation-polls.json"
import ko_conversation_reactions from "./locales/ko/conversation-reactions.json"
import ko_discussion from "./locales/ko/discussion.json"
import ko_discussion_composer from "./locales/ko/discussion-composer.json"
import ko_discussion_delete from "./locales/ko/discussion-delete.json"
import ko_donations from "./locales/ko/donations.json"
import ko_enums from "./locales/ko/enums.json"
import ko_event_bring from "./locales/ko/event-bring.json"
import ko_event_cancel from "./locales/ko/event-cancel.json"
import ko_event_card from "./locales/ko/event-card.json"
import ko_event_create from "./locales/ko/event-create.json"
import ko_event_dashboard from "./locales/ko/event-dashboard.json"
import ko_event_detail from "./locales/ko/event-detail.json"
import ko_event_edit from "./locales/ko/event-edit.json"
import ko_event_form from "./locales/ko/event-form.json"
import ko_event_guest_rsvp from "./locales/ko/event-guest-rsvp.json"
import ko_event_list from "./locales/ko/event-list.json"
import ko_event_members from "./locales/ko/event-members.json"
import ko_event_resources from "./locales/ko/event-resources.json"
import ko_event_rsvp from "./locales/ko/event-rsvp.json"
import ko_event_slots from "./locales/ko/event-slots.json"
import ko_group_create from "./locales/ko/group-create.json"
import ko_group_info from "./locales/ko/group-info.json"
import ko_home_feed from "./locales/ko/home-feed.json"
import ko_home_sidebar from "./locales/ko/home-sidebar.json"
import ko_host_analytics from "./locales/ko/host-analytics.json"
import ko_host_attendees from "./locales/ko/host-attendees.json"
import ko_host_broadcasts from "./locales/ko/host-broadcasts.json"
import ko_host_checkin from "./locales/ko/host-checkin.json"
import ko_host_common from "./locales/ko/host-common.json"
import ko_host_event from "./locales/ko/host-event.json"
import ko_host_exports from "./locales/ko/host-exports.json"
import ko_host_mode from "./locales/ko/host-mode.json"
import ko_host_org from "./locales/ko/host-org.json"
import ko_host_page_builder from "./locales/ko/host-page-builder.json"
import ko_host_payments from "./locales/ko/host-payments.json"
import ko_host_portfolio from "./locales/ko/host-portfolio.json"
import ko_host_settings from "./locales/ko/host-settings.json"
import ko_host_team from "./locales/ko/host-team.json"
import ko_host_ticket from "./locales/ko/host-ticket.json"
import ko_host_tickets from "./locales/ko/host-tickets.json"
import ko_language_settings from "./locales/ko/language-settings.json"
import ko_leaderboard from "./locales/ko/leaderboard.json"
import ko_lightbox from "./locales/ko/lightbox.json"
import ko_map_address from "./locales/ko/map-address.json"
import ko_map_ui from "./locales/ko/map-ui.json"
import ko_messages_list from "./locales/ko/messages-list.json"
import ko_mobile_a11y from "./locales/ko/mobile-a11y.json"
import ko_mobile_auth_otp from "./locales/ko/mobile-auth-otp.json"
import ko_mobile_auth_registration from "./locales/ko/mobile-auth-registration.json"
import ko_mobile_auth_signin from "./locales/ko/mobile-auth-signin.json"
import ko_mobile_auth_welcome from "./locales/ko/mobile-auth-welcome.json"
import ko_mobile_branding from "./locales/ko/mobile-branding.json"
import ko_mobile_errors from "./locales/ko/mobile-errors.json"
import ko_mobile_onboarding from "./locales/ko/mobile-onboarding.json"
import ko_mobile_report_camera from "./locales/ko/mobile-report-camera.json"
import ko_mobile_system from "./locales/ko/mobile-system.json"
import ko_nav from "./locales/ko/nav.json"
import ko_notifications from "./locales/ko/notifications.json"
import ko_notifications_prefs from "./locales/ko/notifications-prefs.json"
import ko_onboarding_age from "./locales/ko/onboarding-age.json"
import ko_onboarding_terms from "./locales/ko/onboarding-terms.json"
import ko_post_composer from "./locales/ko/post-composer.json"
import ko_profile from "./locales/ko/profile.json"
import ko_profile_connections from "./locales/ko/profile-connections.json"
import ko_profile_follow from "./locales/ko/profile-follow.json"
import ko_profile_person from "./locales/ko/profile-person.json"
import ko_profile_view from "./locales/ko/profile-view.json"
import ko_report_cluster from "./locales/ko/report-cluster.json"
import ko_report_content from "./locales/ko/report-content.json"
import ko_report_detail from "./locales/ko/report-detail.json"
import ko_report_linked from "./locales/ko/report-linked.json"
import ko_report_picker from "./locales/ko/report-picker.json"
import ko_report_list from "./locales/ko/report-list.json"
import ko_report_row from "./locales/ko/report-row.json"
import ko_report_wizard from "./locales/ko/report-wizard.json"
import ko_search from "./locales/ko/search.json"
import ko_settings from "./locales/ko/settings.json"
import ko_settings_account from "./locales/ko/settings-account.json"
import ko_settings_privacy from "./locales/ko/settings-privacy.json"
import ko_share_post from "./locales/ko/share-post.json"
import ko_volunteer_hours from "./locales/ko/volunteer-hours.json"
import ko_web_auth from "./locales/ko/web-auth.json"
import ko_web_claims from "./locales/ko/web-claims.json"
import ko_web_common from "./locales/ko/web-common.json"
import ko_web_errors from "./locales/ko/web-errors.json"
import ko_web_registration from "./locales/ko/web-registration.json"
import ko_web_service_record from "./locales/ko/web-service-record.json"

/** Every namespace (catalog file) the app loads. `config.ts` passes this to i18next's `ns`. */
export const namespaces = [
  "about",
  "account-blocked",
  "account-delete",
  "appearance-settings",
  "channel-create",
  "common",
  "common-datetime",
  "common-search",
  "common-share",
  "conversation",
  "conversation-mentions",
  "conversation-polls",
  "conversation-reactions",
  "discussion",
  "discussion-composer",
  "discussion-delete",
  "donations",
  "enums",
  "event-bring",
  "event-cancel",
  "event-card",
  "event-create",
  "event-dashboard",
  "event-detail",
  "event-edit",
  "event-form",
  "event-guest-rsvp",
  "event-list",
  "event-members",
  "event-resources",
  "event-rsvp",
  "event-slots",
  "group-create",
  "group-info",
  "home-feed",
  "home-sidebar",
  "host-analytics",
  "host-attendees",
  "host-broadcasts",
  "host-checkin",
  "host-common",
  "host-event",
  "host-exports",
  "host-mode",
  "host-org",
  "host-page-builder",
  "host-payments",
  "host-portfolio",
  "host-settings",
  "host-team",
  "host-ticket",
  "host-tickets",
  "language-settings",
  "leaderboard",
  "lightbox",
  "map-address",
  "map-ui",
  "messages-list",
  "mobile-a11y",
  "mobile-auth-otp",
  "mobile-auth-registration",
  "mobile-auth-signin",
  "mobile-auth-welcome",
  "mobile-branding",
  "mobile-errors",
  "mobile-onboarding",
  "mobile-report-camera",
  "mobile-system",
  "nav",
  "notifications",
  "notifications-prefs",
  "onboarding-age",
  "onboarding-terms",
  "post-composer",
  "profile",
  "profile-connections",
  "profile-follow",
  "profile-person",
  "profile-view",
  "report-cluster",
  "report-content",
  "report-detail",
  "report-linked",
  "report-picker",
  "report-list",
  "report-row",
  "report-wizard",
  "search",
  "settings",
  "settings-account",
  "settings-privacy",
  "share-post",
  "volunteer-hours",
  "web-auth",
  "web-claims",
  "web-common",
  "web-errors",
  "web-registration",
  "web-service-record",
] as const

/** The assembled i18next resources: locale -> namespace -> catalog object. */
export const resources: Resource = {
  en: {
    "about": en_about,
    "account-blocked": en_account_blocked,
    "account-delete": en_account_delete,
    "appearance-settings": en_appearance_settings,
    "channel-create": en_channel_create,
    "common": en_common,
    "common-datetime": en_common_datetime,
    "common-search": en_common_search,
    "common-share": en_common_share,
    "conversation": en_conversation,
    "conversation-mentions": en_conversation_mentions,
    "conversation-polls": en_conversation_polls,
    "conversation-reactions": en_conversation_reactions,
    "discussion": en_discussion,
    "discussion-composer": en_discussion_composer,
    "discussion-delete": en_discussion_delete,
    "donations": en_donations,
    "enums": en_enums,
    "event-bring": en_event_bring,
    "event-cancel": en_event_cancel,
    "event-card": en_event_card,
    "event-create": en_event_create,
    "event-dashboard": en_event_dashboard,
    "event-detail": en_event_detail,
    "event-edit": en_event_edit,
    "event-form": en_event_form,
    "event-guest-rsvp": en_event_guest_rsvp,
    "event-list": en_event_list,
    "event-members": en_event_members,
    "event-resources": en_event_resources,
    "event-rsvp": en_event_rsvp,
    "event-slots": en_event_slots,
    "group-create": en_group_create,
    "group-info": en_group_info,
    "home-feed": en_home_feed,
    "home-sidebar": en_home_sidebar,
    "host-analytics": en_host_analytics,
    "host-attendees": en_host_attendees,
    "host-broadcasts": en_host_broadcasts,
    "host-checkin": en_host_checkin,
    "host-common": en_host_common,
    "host-event": en_host_event,
    "host-exports": en_host_exports,
    "host-mode": en_host_mode,
    "host-org": en_host_org,
    "host-page-builder": en_host_page_builder,
    "host-payments": en_host_payments,
    "host-portfolio": en_host_portfolio,
    "host-settings": en_host_settings,
    "host-team": en_host_team,
    "host-ticket": en_host_ticket,
    "host-tickets": en_host_tickets,
    "language-settings": en_language_settings,
    "leaderboard": en_leaderboard,
    "lightbox": en_lightbox,
    "map-address": en_map_address,
    "map-ui": en_map_ui,
    "messages-list": en_messages_list,
    "mobile-a11y": en_mobile_a11y,
    "mobile-auth-otp": en_mobile_auth_otp,
    "mobile-auth-registration": en_mobile_auth_registration,
    "mobile-auth-signin": en_mobile_auth_signin,
    "mobile-auth-welcome": en_mobile_auth_welcome,
    "mobile-branding": en_mobile_branding,
    "mobile-errors": en_mobile_errors,
    "mobile-onboarding": en_mobile_onboarding,
    "mobile-report-camera": en_mobile_report_camera,
    "mobile-system": en_mobile_system,
    "nav": en_nav,
    "notifications": en_notifications,
    "notifications-prefs": en_notifications_prefs,
    "onboarding-age": en_onboarding_age,
    "onboarding-terms": en_onboarding_terms,
    "post-composer": en_post_composer,
    "profile": en_profile,
    "profile-connections": en_profile_connections,
    "profile-follow": en_profile_follow,
    "profile-person": en_profile_person,
    "profile-view": en_profile_view,
    "report-cluster": en_report_cluster,
    "report-content": en_report_content,
    "report-detail": en_report_detail,
    "report-linked": en_report_linked,
    "report-picker": en_report_picker,
    "report-list": en_report_list,
    "report-row": en_report_row,
    "report-wizard": en_report_wizard,
    "search": en_search,
    "settings": en_settings,
    "settings-account": en_settings_account,
    "settings-privacy": en_settings_privacy,
    "share-post": en_share_post,
    "volunteer-hours": en_volunteer_hours,
    "web-auth": en_web_auth,
    "web-claims": en_web_claims,
    "web-common": en_web_common,
    "web-errors": en_web_errors,
    "web-registration": en_web_registration,
    "web-service-record": en_web_service_record,
  },
  es: {
    "about": es_about,
    "account-blocked": es_account_blocked,
    "account-delete": es_account_delete,
    "appearance-settings": es_appearance_settings,
    "channel-create": es_channel_create,
    "common": es_common,
    "common-datetime": es_common_datetime,
    "common-search": es_common_search,
    "common-share": es_common_share,
    "conversation": es_conversation,
    "conversation-mentions": es_conversation_mentions,
    "conversation-polls": es_conversation_polls,
    "conversation-reactions": es_conversation_reactions,
    "discussion": es_discussion,
    "discussion-composer": es_discussion_composer,
    "discussion-delete": es_discussion_delete,
    "donations": es_donations,
    "enums": es_enums,
    "event-bring": es_event_bring,
    "event-cancel": es_event_cancel,
    "event-card": es_event_card,
    "event-create": es_event_create,
    "event-dashboard": es_event_dashboard,
    "event-detail": es_event_detail,
    "event-edit": es_event_edit,
    "event-form": es_event_form,
    "event-guest-rsvp": es_event_guest_rsvp,
    "event-list": es_event_list,
    "event-members": es_event_members,
    "event-resources": es_event_resources,
    "event-rsvp": es_event_rsvp,
    "event-slots": es_event_slots,
    "group-create": es_group_create,
    "group-info": es_group_info,
    "home-feed": es_home_feed,
    "home-sidebar": es_home_sidebar,
    "host-analytics": es_host_analytics,
    "host-attendees": es_host_attendees,
    "host-broadcasts": es_host_broadcasts,
    "host-checkin": es_host_checkin,
    "host-common": es_host_common,
    "host-event": es_host_event,
    "host-exports": es_host_exports,
    "host-mode": es_host_mode,
    "host-org": es_host_org,
    "host-page-builder": es_host_page_builder,
    "host-payments": es_host_payments,
    "host-portfolio": es_host_portfolio,
    "host-settings": es_host_settings,
    "host-team": es_host_team,
    "host-ticket": es_host_ticket,
    "host-tickets": es_host_tickets,
    "language-settings": es_language_settings,
    "leaderboard": es_leaderboard,
    "lightbox": es_lightbox,
    "map-address": es_map_address,
    "map-ui": es_map_ui,
    "messages-list": es_messages_list,
    "mobile-a11y": es_mobile_a11y,
    "mobile-auth-otp": es_mobile_auth_otp,
    "mobile-auth-registration": es_mobile_auth_registration,
    "mobile-auth-signin": es_mobile_auth_signin,
    "mobile-auth-welcome": es_mobile_auth_welcome,
    "mobile-branding": es_mobile_branding,
    "mobile-errors": es_mobile_errors,
    "mobile-onboarding": es_mobile_onboarding,
    "mobile-report-camera": es_mobile_report_camera,
    "mobile-system": es_mobile_system,
    "nav": es_nav,
    "notifications": es_notifications,
    "notifications-prefs": es_notifications_prefs,
    "onboarding-age": es_onboarding_age,
    "onboarding-terms": es_onboarding_terms,
    "post-composer": es_post_composer,
    "profile": es_profile,
    "profile-connections": es_profile_connections,
    "profile-follow": es_profile_follow,
    "profile-person": es_profile_person,
    "profile-view": es_profile_view,
    "report-cluster": es_report_cluster,
    "report-content": es_report_content,
    "report-detail": es_report_detail,
    "report-linked": es_report_linked,
    "report-picker": es_report_picker,
    "report-list": es_report_list,
    "report-row": es_report_row,
    "report-wizard": es_report_wizard,
    "search": es_search,
    "settings": es_settings,
    "settings-account": es_settings_account,
    "settings-privacy": es_settings_privacy,
    "share-post": es_share_post,
    "volunteer-hours": es_volunteer_hours,
    "web-auth": es_web_auth,
    "web-claims": es_web_claims,
    "web-common": es_web_common,
    "web-errors": es_web_errors,
    "web-registration": es_web_registration,
    "web-service-record": es_web_service_record,
  },
  de: {
    "about": de_about,
    "account-blocked": de_account_blocked,
    "account-delete": de_account_delete,
    "appearance-settings": de_appearance_settings,
    "channel-create": de_channel_create,
    "common": de_common,
    "common-datetime": de_common_datetime,
    "common-search": de_common_search,
    "common-share": de_common_share,
    "conversation": de_conversation,
    "conversation-mentions": de_conversation_mentions,
    "conversation-polls": de_conversation_polls,
    "conversation-reactions": de_conversation_reactions,
    "discussion": de_discussion,
    "discussion-composer": de_discussion_composer,
    "discussion-delete": de_discussion_delete,
    "donations": de_donations,
    "enums": de_enums,
    "event-bring": de_event_bring,
    "event-cancel": de_event_cancel,
    "event-card": de_event_card,
    "event-create": de_event_create,
    "event-dashboard": de_event_dashboard,
    "event-detail": de_event_detail,
    "event-edit": de_event_edit,
    "event-form": de_event_form,
    "event-guest-rsvp": de_event_guest_rsvp,
    "event-list": de_event_list,
    "event-members": de_event_members,
    "event-resources": de_event_resources,
    "event-rsvp": de_event_rsvp,
    "event-slots": de_event_slots,
    "group-create": de_group_create,
    "group-info": de_group_info,
    "home-feed": de_home_feed,
    "home-sidebar": de_home_sidebar,
    "host-analytics": de_host_analytics,
    "host-attendees": de_host_attendees,
    "host-broadcasts": de_host_broadcasts,
    "host-checkin": de_host_checkin,
    "host-common": de_host_common,
    "host-event": de_host_event,
    "host-exports": de_host_exports,
    "host-mode": de_host_mode,
    "host-org": de_host_org,
    "host-page-builder": de_host_page_builder,
    "host-payments": de_host_payments,
    "host-portfolio": de_host_portfolio,
    "host-settings": de_host_settings,
    "host-team": de_host_team,
    "host-ticket": de_host_ticket,
    "host-tickets": de_host_tickets,
    "language-settings": de_language_settings,
    "leaderboard": de_leaderboard,
    "lightbox": de_lightbox,
    "map-address": de_map_address,
    "map-ui": de_map_ui,
    "messages-list": de_messages_list,
    "mobile-a11y": de_mobile_a11y,
    "mobile-auth-otp": de_mobile_auth_otp,
    "mobile-auth-registration": de_mobile_auth_registration,
    "mobile-auth-signin": de_mobile_auth_signin,
    "mobile-auth-welcome": de_mobile_auth_welcome,
    "mobile-branding": de_mobile_branding,
    "mobile-errors": de_mobile_errors,
    "mobile-onboarding": de_mobile_onboarding,
    "mobile-report-camera": de_mobile_report_camera,
    "mobile-system": de_mobile_system,
    "nav": de_nav,
    "notifications": de_notifications,
    "notifications-prefs": de_notifications_prefs,
    "onboarding-age": de_onboarding_age,
    "onboarding-terms": de_onboarding_terms,
    "post-composer": de_post_composer,
    "profile": de_profile,
    "profile-connections": de_profile_connections,
    "profile-follow": de_profile_follow,
    "profile-person": de_profile_person,
    "profile-view": de_profile_view,
    "report-cluster": de_report_cluster,
    "report-content": de_report_content,
    "report-detail": de_report_detail,
    "report-linked": de_report_linked,
    "report-picker": de_report_picker,
    "report-list": de_report_list,
    "report-row": de_report_row,
    "report-wizard": de_report_wizard,
    "search": de_search,
    "settings": de_settings,
    "settings-account": de_settings_account,
    "settings-privacy": de_settings_privacy,
    "share-post": de_share_post,
    "volunteer-hours": de_volunteer_hours,
    "web-auth": de_web_auth,
    "web-claims": de_web_claims,
    "web-common": de_web_common,
    "web-errors": de_web_errors,
    "web-registration": de_web_registration,
    "web-service-record": de_web_service_record,
  },
  ko: {
    "about": ko_about,
    "account-blocked": ko_account_blocked,
    "account-delete": ko_account_delete,
    "appearance-settings": ko_appearance_settings,
    "channel-create": ko_channel_create,
    "common": ko_common,
    "common-datetime": ko_common_datetime,
    "common-search": ko_common_search,
    "common-share": ko_common_share,
    "conversation": ko_conversation,
    "conversation-mentions": ko_conversation_mentions,
    "conversation-polls": ko_conversation_polls,
    "conversation-reactions": ko_conversation_reactions,
    "discussion": ko_discussion,
    "discussion-composer": ko_discussion_composer,
    "discussion-delete": ko_discussion_delete,
    "donations": ko_donations,
    "enums": ko_enums,
    "event-bring": ko_event_bring,
    "event-cancel": ko_event_cancel,
    "event-card": ko_event_card,
    "event-create": ko_event_create,
    "event-dashboard": ko_event_dashboard,
    "event-detail": ko_event_detail,
    "event-edit": ko_event_edit,
    "event-form": ko_event_form,
    "event-guest-rsvp": ko_event_guest_rsvp,
    "event-list": ko_event_list,
    "event-members": ko_event_members,
    "event-resources": ko_event_resources,
    "event-rsvp": ko_event_rsvp,
    "event-slots": ko_event_slots,
    "group-create": ko_group_create,
    "group-info": ko_group_info,
    "home-feed": ko_home_feed,
    "home-sidebar": ko_home_sidebar,
    "host-analytics": ko_host_analytics,
    "host-attendees": ko_host_attendees,
    "host-broadcasts": ko_host_broadcasts,
    "host-checkin": ko_host_checkin,
    "host-common": ko_host_common,
    "host-event": ko_host_event,
    "host-exports": ko_host_exports,
    "host-mode": ko_host_mode,
    "host-org": ko_host_org,
    "host-page-builder": ko_host_page_builder,
    "host-payments": ko_host_payments,
    "host-portfolio": ko_host_portfolio,
    "host-settings": ko_host_settings,
    "host-team": ko_host_team,
    "host-ticket": ko_host_ticket,
    "host-tickets": ko_host_tickets,
    "language-settings": ko_language_settings,
    "leaderboard": ko_leaderboard,
    "lightbox": ko_lightbox,
    "map-address": ko_map_address,
    "map-ui": ko_map_ui,
    "messages-list": ko_messages_list,
    "mobile-a11y": ko_mobile_a11y,
    "mobile-auth-otp": ko_mobile_auth_otp,
    "mobile-auth-registration": ko_mobile_auth_registration,
    "mobile-auth-signin": ko_mobile_auth_signin,
    "mobile-auth-welcome": ko_mobile_auth_welcome,
    "mobile-branding": ko_mobile_branding,
    "mobile-errors": ko_mobile_errors,
    "mobile-onboarding": ko_mobile_onboarding,
    "mobile-report-camera": ko_mobile_report_camera,
    "mobile-system": ko_mobile_system,
    "nav": ko_nav,
    "notifications": ko_notifications,
    "notifications-prefs": ko_notifications_prefs,
    "onboarding-age": ko_onboarding_age,
    "onboarding-terms": ko_onboarding_terms,
    "post-composer": ko_post_composer,
    "profile": ko_profile,
    "profile-connections": ko_profile_connections,
    "profile-follow": ko_profile_follow,
    "profile-person": ko_profile_person,
    "profile-view": ko_profile_view,
    "report-cluster": ko_report_cluster,
    "report-content": ko_report_content,
    "report-detail": ko_report_detail,
    "report-linked": ko_report_linked,
    "report-picker": ko_report_picker,
    "report-list": ko_report_list,
    "report-row": ko_report_row,
    "report-wizard": ko_report_wizard,
    "search": ko_search,
    "settings": ko_settings,
    "settings-account": ko_settings_account,
    "settings-privacy": ko_settings_privacy,
    "share-post": ko_share_post,
    "volunteer-hours": ko_volunteer_hours,
    "web-auth": ko_web_auth,
    "web-claims": ko_web_claims,
    "web-common": ko_web_common,
    "web-errors": ko_web_errors,
    "web-registration": ko_web_registration,
    "web-service-record": ko_web_service_record,
  },
}
