import { def } from "../def.js"
import {
  AnalyticsKpisResponseSchema,
  AnalyticsPinsByWeekResponseSchema,
  AnalyticsByCategoryResponseSchema,
  AnalyticsFunnelResponseSchema,
  AnalyticsCoverageResponseSchema,
  AnalyticsResolutionByCategoryResponseSchema,
  AnalyticsEventsResponseSchema,
  AnalyticsTopJurisdictionsResponseSchema,
  AnalyticsTopContributorsResponseSchema,
  AnalyticsHeatmapResponseSchema,
  AnalyticsRetentionResponseSchema,
} from "../../../schemas/admin/analytics.js"

export const adminAnalyticsEndpoints = {
  analyticsKpis: def({
    method: "GET",
    path: "/admin/analytics/kpis",
    request: null,
    response: AnalyticsKpisResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsPinsByWeek: def({
    method: "GET",
    path: "/admin/analytics/pins-by-week",
    request: null,
    response: AnalyticsPinsByWeekResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsByCategory: def({
    method: "GET",
    path: "/admin/analytics/by-category",
    request: null,
    response: AnalyticsByCategoryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsFunnel: def({
    method: "GET",
    path: "/admin/analytics/funnel",
    request: null,
    response: AnalyticsFunnelResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsCoverage: def({
    method: "GET",
    path: "/admin/analytics/coverage",
    request: null,
    response: AnalyticsCoverageResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsResolutionByCategory: def({
    method: "GET",
    path: "/admin/analytics/resolution-by-category",
    request: null,
    response: AnalyticsResolutionByCategoryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsEvents: def({
    method: "GET",
    path: "/admin/analytics/events",
    request: null,
    response: AnalyticsEventsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsTopJurisdictions: def({
    method: "GET",
    path: "/admin/analytics/top-jurisdictions",
    request: null,
    response: AnalyticsTopJurisdictionsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsTopContributors: def({
    method: "GET",
    path: "/admin/analytics/top-contributors",
    request: null,
    response: AnalyticsTopContributorsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsHeatmap: def({
    method: "GET",
    path: "/admin/analytics/heatmap",
    request: null,
    response: AnalyticsHeatmapResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsRetention: def({
    method: "GET",
    path: "/admin/analytics/retention",
    request: null,
    response: AnalyticsRetentionResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
} as const
