import { def } from "../def.js"
import {
  AdminEventListQuerySchema,
  AdminEventListResponseSchema,
  GetAdminEventResponseSchema,
  SetEventStatusRequestSchema,
  FlagEventRequestSchema,
  CancelRequestSchema,
  PostMessageRequestSchema,
  SetEventOutcomeRequestSchema,
  LinkEventReportsRequestSchema,
} from "../../../schemas/admin/events.js"
import { AdminOkResponseSchema } from "../../../schemas/admin/common.js"

export const adminEventEndpoints = {
  listAdminEvents: def({
    method: "GET",
    path: "/admin/events",
    request: AdminEventListQuerySchema,
    response: AdminEventListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getAdminEvent: def({
    method: "GET",
    path: "/admin/events/:id",
    request: null,
    response: GetAdminEventResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  setEventStatus: def({
    method: "POST",
    path: "/admin/events/:id/status",
    request: SetEventStatusRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  flagEvent: def({
    method: "POST",
    path: "/admin/events/:id/flag",
    request: FlagEventRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  cancelEvent: def({
    method: "POST",
    path: "/admin/events/:id/cancel",
    request: CancelRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  postEventMessage: def({
    method: "POST",
    path: "/admin/events/:id/message",
    request: PostMessageRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setEventOutcome: def({
    method: "POST",
    path: "/admin/events/:id/outcome",
    request: SetEventOutcomeRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  linkEventReports: def({
    method: "POST",
    path: "/admin/events/:id/link-reports",
    request: LinkEventReportsRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unlinkEventReport: def({
    method: "DELETE",
    path: "/admin/events/:id/reports/:reportId",
    request: null,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
