import { def } from "../def.js"
import { GetLegalVersionsResponseSchema } from "../../../schemas/legal.js"
import {
  AdminAddOrgMemberRequestSchema,
  AdminAddOrgMemberResponseSchema,
  AdminCreateOrgRequestSchema,
  AdminCreateOrgResponseSchema,
  AdminOrgEventListRequestSchema,
  AdminOrgEventListResponseSchema,
  AdminOrgListQuerySchema,
  AdminOrgListResponseSchema,
  AdminOrgMemberListRequestSchema,
  AdminOrgMemberListResponseSchema,
  AdminOrgVerificationListQuerySchema,
  AdminOrgVerificationListResponseSchema,
  AdminRemoveOrgMemberRequestSchema,
  AdminRemoveOrgMemberResponseSchema,
  AdminSetOrgMemberRoleRequestSchema,
  AdminSetOrgMemberRoleResponseSchema,
  AdminSetOrgSuspendedRequestSchema,
  AdminSetOrgSuspendedResponseSchema,
  AdminUpdateOrgRequestSchema,
  AdminUpdateOrgResponseSchema,
  DecideOrgVerificationRequestSchema,
  DecideOrgVerificationResponseSchema,
  GetAdminOrgRequestSchema,
  GetAdminOrgResponseSchema,
} from "../../../schemas/admin/orgs.js"
import {
  AdminBroadcastListQuerySchema,
  AdminBroadcastListResponseSchema,
  AdminHostListQuerySchema,
  AdminHostListResponseSchema,
  SetHostMessagingSuspendedRequestSchema,
  SetHostMessagingSuspendedResponseSchema,
} from "../../../schemas/admin/hosts.js"
import {
  AdminEventPageListQuerySchema,
  AdminEventPageListResponseSchema,
  AdminGetEventPageRequestSchema,
  AdminGetEventPageResponseSchema,
  FlagEventPageRequestSchema,
  FlagEventPageResponseSchema,
  UnpublishEventPageRequestSchema,
  UnpublishEventPageResponseSchema,
} from "../../../schemas/admin/pages.js"
import { AdminGetMediaRequestSchema, AdminGetMediaResponseSchema } from "../../../schemas/admin/media.js"

export const hostAdminEndpoints = {
  adminListOrgVerifications: def({
    method: "GET",
    path: "/admin/orgs/verifications",
    request: AdminOrgVerificationListQuerySchema,
    response: AdminOrgVerificationListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminGetOrg: def({
    method: "GET",
    path: "/admin/orgs/:id",
    request: GetAdminOrgRequestSchema,
    response: GetAdminOrgResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminDecideOrgVerification: def({
    method: "POST",
    path: "/admin/orgs/:id/verification",
    request: DecideOrgVerificationRequestSchema,
    response: DecideOrgVerificationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminListOrgs: def({
    method: "GET",
    path: "/admin/orgs",
    request: AdminOrgListQuerySchema,
    response: AdminOrgListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminCreateOrg: def({
    method: "POST",
    path: "/admin/orgs",
    request: AdminCreateOrgRequestSchema,
    response: AdminCreateOrgResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminUpdateOrg: def({
    method: "PATCH",
    path: "/admin/orgs/:id",
    request: AdminUpdateOrgRequestSchema,
    response: AdminUpdateOrgResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminSetOrgSuspended: def({
    method: "POST",
    path: "/admin/orgs/:id/suspend",
    request: AdminSetOrgSuspendedRequestSchema,
    response: AdminSetOrgSuspendedResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminListOrgMembers: def({
    method: "GET",
    path: "/admin/orgs/:id/members",
    request: AdminOrgMemberListRequestSchema,
    response: AdminOrgMemberListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminAddOrgMember: def({
    method: "POST",
    path: "/admin/orgs/:id/members",
    request: AdminAddOrgMemberRequestSchema,
    response: AdminAddOrgMemberResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminSetOrgMemberRole: def({
    method: "PATCH",
    path: "/admin/orgs/:id/members/:userId",
    request: AdminSetOrgMemberRoleRequestSchema,
    response: AdminSetOrgMemberRoleResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminRemoveOrgMember: def({
    method: "DELETE",
    path: "/admin/orgs/:id/members/:userId",
    request: AdminRemoveOrgMemberRequestSchema,
    response: AdminRemoveOrgMemberResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminListOrgEvents: def({
    method: "GET",
    path: "/admin/orgs/:id/events",
    request: AdminOrgEventListRequestSchema,
    response: AdminOrgEventListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  adminSetHostMessagingSuspended: def({
    method: "POST",
    path: "/admin/hosts/:id/messaging",
    request: SetHostMessagingSuspendedRequestSchema,
    response: SetHostMessagingSuspendedResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminListBroadcasts: def({
    method: "GET",
    path: "/admin/broadcasts",
    request: AdminBroadcastListQuerySchema,
    response: AdminBroadcastListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  adminListEventPages: def({
    method: "GET",
    path: "/admin/pages",
    request: AdminEventPageListQuerySchema,
    response: AdminEventPageListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminFlagEventPage: def({
    method: "POST",
    path: "/admin/pages/:id/flag",
    request: FlagEventPageRequestSchema,
    response: FlagEventPageResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminUnpublishEventPage: def({
    method: "POST",
    path: "/admin/pages/:id/unpublish",
    request: UnpublishEventPageRequestSchema,
    response: UnpublishEventPageResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  adminListHosts: def({
    method: "GET",
    path: "/admin/hosts",
    request: AdminHostListQuerySchema,
    response: AdminHostListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminGetEventPage: def({
    method: "GET",
    path: "/admin/pages/:id",
    request: AdminGetEventPageRequestSchema,
    response: AdminGetEventPageResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminGetMedia: def({
    method: "GET",
    path: "/admin/media/:id",
    request: AdminGetMediaRequestSchema,
    response: AdminGetMediaResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminGetLegalVersions: def({
    method: "GET",
    path: "/admin/legal/versions",
    request: null,
    response: GetLegalVersionsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
} as const
