import { def } from "../def.js"
import {
  MailListQuerySchema,
  MailListResponseSchema,
  GetMailThreadResponseSchema,
  MailStatsResponseSchema,
  ComposeRequestSchema,
  ReplyRequestSchema,
  MarkMailReadRequestSchema,
  SetMailStatusRequestSchema,
  ResendRequestSchema,
  PublishMailReplyRequestSchema,
  PublishMailReplyResponseSchema,
} from "../../../schemas/admin/mail.js"
import {
  GetForwardTemplateDefaultResponseSchema,
  SetForwardTemplateDefaultRequestSchema,
  PreviewForwardTemplateRequestSchema,
  PreviewForwardTemplateResponseSchema,
} from "../../../schemas/admin/forward-template.js"
import {
  InboxListQuerySchema,
  InboxListResponseSchema,
  GetInboxMessageResponseSchema,
  SetInboxStatusRequestSchema,
  InboxFeedQuerySchema,
  InboxFeedResponseSchema,
} from "../../../schemas/admin/inbox.js"
import { AdminOkResponseSchema } from "../../../schemas/admin/common.js"

export const adminMailEndpoints = {
  listMail: def({
    method: "GET",
    path: "/admin/mail",
    request: MailListQuerySchema,
    response: MailListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getMailThread: def({
    method: "GET",
    path: "/admin/mail/:id",
    request: null,
    response: GetMailThreadResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  composeMail: def({
    method: "POST",
    path: "/admin/mail",
    request: ComposeRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  replyMail: def({
    method: "POST",
    path: "/admin/mail/:id/reply",
    request: ReplyRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  markMailRead: def({
    method: "POST",
    path: "/admin/mail/:id/read",
    request: MarkMailReadRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setMailStatus: def({
    method: "POST",
    path: "/admin/mail/:id/status",
    request: SetMailStatusRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  resendMail: def({
    method: "POST",
    path: "/admin/mail/:id/resend",
    request: ResendRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getMailStats: def({
    method: "GET",
    path: "/admin/mail/stats",
    request: null,
    response: MailStatsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getForwardTemplateDefault: def({
    method: "GET",
    path: "/admin/mail/forward-template",
    request: null,
    response: GetForwardTemplateDefaultResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  setForwardTemplateDefault: def({
    method: "PUT",
    path: "/admin/mail/forward-template",
    request: SetForwardTemplateDefaultRequestSchema,
    response: GetForwardTemplateDefaultResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  previewForwardTemplate: def({
    method: "POST",
    path: "/admin/mail/forward-template/preview",
    request: PreviewForwardTemplateRequestSchema,
    response: PreviewForwardTemplateResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listInbox: def({
    method: "GET",
    path: "/admin/inbox",
    request: InboxListQuerySchema,
    response: InboxListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getInboxMessage: def({
    method: "GET",
    path: "/admin/inbox/:id",
    request: null,
    response: GetInboxMessageResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  setInboxStatus: def({
    method: "POST",
    path: "/admin/inbox/:id/status",
    request: SetInboxStatusRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const

export const adminInboxEndpoints = {
  listInboxFeed: def({
    method: "GET",
    path: "/admin/inbox/feed",
    request: InboxFeedQuerySchema,
    response: InboxFeedResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  publishMailReply: def({
    method: "POST",
    path: "/admin/mail/:id/messages/:messageId/publish",
    request: PublishMailReplyRequestSchema,
    response: PublishMailReplyResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
