import { def } from "../def.js"
import {
  AdminReportListQuerySchema,
  AdminReportListResponseSchema,
  GetAdminReportResponseSchema,
  SetReportStatusRequestSchema,
  FlagReportRequestSchema,
  RemoveReportRequestSchema,
  SendFollowupRequestSchema,
  RouteReportRequestSchema,
  RouteReportResponseSchema,
  SetReportVerdictRequestSchema,
  SetReportVerdictResponseSchema,
  AdminReportMessagesRequestSchema,
  AdminReportMessagesResponseSchema,
  AdminSendReportMessageRequestSchema,
  AdminSendReportMessageResponseSchema,
  AdminRemoveReportMessageRequestSchema,
} from "../../../schemas/admin/reports.js"
import { AdminOkResponseSchema } from "../../../schemas/admin/common.js"

export const adminReportEndpoints = {
  listAdminReports: def({
    method: "GET",
    path: "/admin/reports",
    request: AdminReportListQuerySchema,
    response: AdminReportListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getAdminReport: def({
    method: "GET",
    path: "/admin/reports/:id",
    request: null,
    response: GetAdminReportResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  setReportStatus: def({
    method: "POST",
    path: "/admin/reports/:id/status",
    request: SetReportStatusRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  flagReport: def({
    method: "POST",
    path: "/admin/reports/:id/flag",
    request: FlagReportRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  removeReport: def({
    method: "POST",
    path: "/admin/reports/:id/remove",
    request: RemoveReportRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  sendReportFollowup: def({
    method: "POST",
    path: "/admin/reports/:id/message",
    request: SendFollowupRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  routeReport: def({
    method: "POST",
    path: "/admin/reports/:id/route",
    request: RouteReportRequestSchema,
    response: RouteReportResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setReportVerdict: def({
    method: "POST",
    path: "/admin/reports/:id/verdict",
    request: SetReportVerdictRequestSchema,
    response: SetReportVerdictResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const

export const adminReportChatEndpoints = {
  adminReportMessages: def({
    method: "GET",
    path: "/admin/reports/:id/messages",
    request: AdminReportMessagesRequestSchema,
    response: AdminReportMessagesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminSendReportMessage: def({
    method: "POST",
    path: "/admin/reports/:id/messages",
    request: AdminSendReportMessageRequestSchema,
    response: AdminSendReportMessageResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminRemoveReportMessage: def({
    method: "POST",
    path: "/admin/reports/:id/messages/:messageId/remove",
    request: AdminRemoveReportMessageRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
