import { def } from "../def.js"
import {
  AdminUserListQuerySchema,
  AdminUserListResponseSchema,
  GetAdminUserResponseSchema,
  UserSubListQuerySchema,
  UserReportsResponseSchema,
  UserEventsResponseSchema,
  UserMessagesResponseSchema,
  FlagUserRequestSchema,
  SetUserStatusRequestSchema,
  SetRoleRequestSchema,
  SetUserReportVerifiedRequestSchema,
  RemoveUserMessageRequestSchema,
} from "../../../schemas/admin/users.js"
import {
  GovClaimListQuerySchema,
  GovClaimListResponseSchema,
  GetGovClaimResponseSchema,
  VerifyCheckRequestSchema,
  ApproveGovClaimRequestSchema,
  RejectGovClaimRequestSchema,
} from "../../../schemas/admin/gov.js"
import { AdminOkResponseSchema } from "../../../schemas/admin/common.js"

export const adminUserEndpoints = {
  listAdminUsers: def({
    method: "GET",
    path: "/admin/users",
    request: AdminUserListQuerySchema,
    response: AdminUserListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getAdminUser: def({
    method: "GET",
    path: "/admin/users/:id",
    request: null,
    response: GetAdminUserResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getUserReports: def({
    method: "GET",
    path: "/admin/users/:id/reports",
    request: UserSubListQuerySchema,
    response: UserReportsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getUserEvents: def({
    method: "GET",
    path: "/admin/users/:id/events",
    request: UserSubListQuerySchema,
    response: UserEventsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getUserMessages: def({
    method: "GET",
    path: "/admin/users/:id/messages",
    request: UserSubListQuerySchema,
    response: UserMessagesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  flagUser: def({
    method: "POST",
    path: "/admin/users/:id/flag",
    request: FlagUserRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setUserStatus: def({
    method: "POST",
    path: "/admin/users/:id/status",
    request: SetUserStatusRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setUserRole: def({
    method: "POST",
    path: "/admin/users/:id/role",
    request: SetRoleRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setUserReportVerified: def({
    method: "POST",
    path: "/admin/users/:id/report-verify",
    request: SetUserReportVerifiedRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  removeUserMessage: def({
    method: "POST",
    path: "/admin/users/:id/messages/:messageId/remove",
    request: RemoveUserMessageRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listGovClaims: def({
    method: "GET",
    path: "/admin/gov-claims",
    request: GovClaimListQuerySchema,
    response: GovClaimListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getGovClaim: def({
    method: "GET",
    path: "/admin/gov-claims/:id",
    request: null,
    response: GetGovClaimResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  verifyGovClaim: def({
    method: "POST",
    path: "/admin/gov-claims/:id/verify",
    request: VerifyCheckRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  approveGovClaim: def({
    method: "POST",
    path: "/admin/gov-claims/:id/approve",
    request: ApproveGovClaimRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  rejectGovClaim: def({
    method: "POST",
    path: "/admin/gov-claims/:id/reject",
    request: RejectGovClaimRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
