/**
 * Renders the i18n catalog modules from one static import per locale and namespace JSON: Metro cannot
 * statically resolve a dynamic `require`, and webpack needs a literal `import()` specifier to emit one
 * chunk per locale. A namespace missing for one locale is skipped there, and i18next falls back to `en`.
 *
 * Modules, keyed by path relative to src/i18n/:
 *   catalogs/namespaces.ts  the namespace list config.ts feeds to i18next's `ns`
 *   catalogs/<lng>.ts       one locale's catalogs (namespace -> JSON)
 *   catalogs/lazy.ts        an `import()` per non-fallback locale, for the web seam only
 *   resources.ts            every locale assembled statically, for the native seam and the parity tests
 *
 * gen-i18n-resources.mjs writes them; check-i18n-resources.mjs fails when the committed files differ.
 */
import { readdirSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { LocaleEnum } from "@civfix/shared"

export const i18nDir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "i18n")
export const CATALOGS_DIR = "catalogs"
const localesDir = join(i18nDir, "locales")

// The contract enum, not the folder list: config.ts hands the same list to i18next as supportedLngs, so
// the bundle carries exactly the locales the app can select. It reads the built package, so build
// @civfix/shared first after adding a locale.
const LOCALES = LocaleEnum.options

// Must equal FALLBACK_LOCALE in src/i18n/resolveLocale.ts: the web bundles it statically so a key never
// renders raw while another locale's chunk is in flight.
const STATIC_LOCALE = "en"
if (!LOCALES.includes(STATIC_LOCALE)) throw new Error(`LocaleEnum no longer contains ${STATIC_LOCALE}`)

const jsonNames = (dir) =>
  readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""))

function ident(lng, ns) {
  return `${lng}_${ns}`.replace(/[^A-Za-z0-9_]/g, "_")
}

const banner = `/**
 * AUTO-GENERATED by scripts/gen-i18n-resources.mjs: DO NOT EDIT BY HAND.
 *
 * Re-run \`pnpm --filter @civfix/ui i18n:gen\` after adding or removing a namespace or locale.
 */`

export function renderI18nModules() {
  // Sorted for stable output.
  const namespaces = jsonNames(join(localesDir, STATIC_LOCALE)).sort()
  const namespacesFor = (lng) => {
    const present = new Set(jsonNames(join(localesDir, lng)))
    return namespaces.filter((ns) => present.has(ns))
  }

  const modules = new Map()
  modules.set(
    `${CATALOGS_DIR}/namespaces.ts`,
    `${banner}

/** Every namespace (catalog file) the app loads. \`config.ts\` passes this to i18next's \`ns\`. */
export const namespaces = [
${namespaces.map((ns) => `  "${ns}",`).join("\n")}
] as const
`,
  )

  let importCount = 0
  for (const lng of LOCALES) {
    const nsList = namespacesFor(lng)
    importCount += nsList.length
    modules.set(
      `${CATALOGS_DIR}/${lng}.ts`,
      `${banner}
import type { ResourceLanguage } from "i18next"

${nsList.map((ns) => `import ${ident(lng, ns)} from "../locales/${lng}/${ns}.json"`).join("\n")}

const catalog: ResourceLanguage = {
${nsList.map((ns) => `  "${ns}": ${ident(lng, ns)},`).join("\n")}
}

export default catalog
`,
    )
  }

  const lazyLocales = LOCALES.filter((lng) => lng !== STATIC_LOCALE)
  modules.set(
    `${CATALOGS_DIR}/lazy.ts`,
    `${banner}
import type { ResourceLanguage } from "i18next"
import type { SupportedLocale } from "@civfix/shared"

/** One loader per locale the web does not bundle statically; webpack emits each as its own chunk. */
export const lazyCatalogs: Record<
  Exclude<SupportedLocale, "${STATIC_LOCALE}">,
  () => Promise<{ default: ResourceLanguage }>
> = {
${lazyLocales.map((lng) => `  ${lng}: () => import(/* webpackChunkName: "i18n-${lng}" */ "./${lng}"),`).join("\n")}
}
`,
  )

  modules.set(
    "resources.ts",
    `${banner}
import type { Resource } from "i18next"

${LOCALES.map((lng) => `import ${lng} from "./catalogs/${lng}"`).join("\n")}

export { namespaces } from "./catalogs/namespaces"

/** Every locale assembled statically: locale -> namespace -> catalog object. */
export const resources: Resource = {
${LOCALES.map((lng) => `  ${lng},`).join("\n")}
}
`,
  )

  return { modules, summary: { locales: LOCALES, staticLocale: STATIC_LOCALE, namespaces, importCount } }
}
