import { def } from "./def.js"
import {
  GetProfileResponseSchema,
  UpdateProfileRequestSchema,
  UpdateProfileResponseSchema,
  HandleAvailableRequestSchema,
  HandleAvailableResponseSchema,
  UpdateSettingsRequestSchema,
  UpdateSettingsResponseSchema,
  DeleteAccountRequestSchema,
  DeleteAccountResponseSchema,
  RequestDataExportResponseSchema,
} from "../../schemas/social.js"

export const accountEndpoints = {
  myProfile: def({
    method: "GET",
    path: "/me/profile",
    request: null,
    response: GetProfileResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  updateProfile: def({
    method: "PUT",
    path: "/me/profile",
    request: UpdateProfileRequestSchema,
    response: UpdateProfileResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  checkHandle: def({
    method: "GET",
    path: "/me/handle-available",
    request: HandleAvailableRequestSchema,
    response: HandleAvailableResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  updateSettings: def({
    method: "PUT",
    path: "/me/settings",
    request: UpdateSettingsRequestSchema,
    response: UpdateSettingsResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  deleteAccount: def({
    method: "DELETE",
    path: "/me",
    request: DeleteAccountRequestSchema,
    response: DeleteAccountResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  requestDataExport: def({
    method: "POST",
    path: "/me/data-export",
    request: null,
    response: RequestDataExportResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
