import { z } from "zod"
import { def } from "./def.js"
import {
  AppleSignInRequestSchema,
  AppleCallbackBodySchema,
  GoogleSignInRequestSchema,
  OAuthStartQuerySchema,
  OAuthCallbackQuerySchema,
  EmailOtpRequestRequestSchema,
  EmailOtpRequestResponseSchema,
  EmailOtpVerifyRequestSchema,
  SessionResponseSchema,
  SessionCheckResponseSchema,
  LogoutResponseSchema,
  WsTicketResponseSchema,
} from "../../schemas/auth.js"

const OAuthStartResponseSchema = z.object({ url: z.string() })

export const authEndpoints = {
  appleSignIn: def({
    method: "POST",
    path: "/auth/apple",
    request: AppleSignInRequestSchema,
    response: SessionResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  googleSignIn: def({
    method: "POST",
    path: "/auth/google",
    request: GoogleSignInRequestSchema,
    response: SessionResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  googleStart: def({
    method: "GET",
    path: "/auth/google/start",
    request: OAuthStartQuerySchema,
    response: OAuthStartResponseSchema,
    auth: "public",
    csrf: false,
    version: "unversioned",
  }),
  googleCallback: def({
    method: "GET",
    path: "/auth/google/callback",
    request: OAuthCallbackQuerySchema,
    response: SessionResponseSchema,
    auth: "public",
    csrf: false,
    version: "unversioned",
  }),
  appleStart: def({
    method: "GET",
    path: "/auth/apple/start",
    request: OAuthStartQuerySchema,
    response: OAuthStartResponseSchema,
    auth: "public",
    csrf: false,
    version: "unversioned",
  }),
  appleCallback: def({
    method: "POST",
    path: "/auth/apple/callback",
    request: AppleCallbackBodySchema,
    response: SessionResponseSchema,
    auth: "public",
    csrf: false,
    version: "unversioned",
  }),
  otpRequest: def({
    method: "POST",
    path: "/auth/otp/request",
    request: EmailOtpRequestRequestSchema,
    response: EmailOtpRequestResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  otpVerify: def({
    method: "POST",
    path: "/auth/otp/verify",
    request: EmailOtpVerifyRequestSchema,
    response: SessionResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  session: def({
    method: "GET",
    path: "/auth/session",
    request: null,
    response: SessionCheckResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  logout: def({
    method: "POST",
    path: "/auth/logout",
    request: null,
    response: LogoutResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  wsTicket: def({
    method: "POST",
    path: "/ws-ticket",
    request: null,
    response: WsTicketResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
