import { def } from "./def.js"
import {
  ChatHistoryResponseSchema,
  ChatMessageDTOSchema,
  ListThreadsResponseSchema,
  MarkThreadReadRequestSchema,
  MarkThreadReadResponseSchema,
  OpenDmRequestSchema,
  OpenDmResponseSchema,
  DmHistoryRequestSchema,
  DmHistoryResponseSchema,
  EditChatMessageRequestSchema,
  EditMessageRequestSchema,
  SetMessagePinnedRequestSchema,
  ToggleMessageReactionRequestSchema,
  DeleteDmMessageRequestSchema,
  DeleteCleanupMessageRequestSchema,
  ToggleCleanupMessageReactionRequestSchema,
  ToggleDmMessageReactionRequestSchema,
  ReportChatHistoryRequestSchema,
  DeleteReportMessageRequestSchema,
  ToggleReportMessageReactionRequestSchema,
  CreatePollRequestSchema,
  VotePollRequestSchema,
  ClosePollRequestSchema,
} from "../../schemas/chat.js"
import {
  JoinReportChatRequestSchema,
  LeaveReportChatRequestSchema,
  ReportChatParticipantsResponseSchema,
  ToggleMuteRequestSchema,
  ToggleMuteResponseSchema,
  ToggleHiddenRequestSchema,
  ToggleHiddenResponseSchema,
} from "../../schemas/report-chat.js"
import { PaginationQuerySchema } from "../../schemas/common.js"
import { OkResponseSchema } from "../../schemas/internal-fields.js"

export const chatEndpoints = {
  listThreads: def({
    method: "GET",
    path: "/threads",
    request: PaginationQuerySchema,
    response: ListThreadsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  markThreadRead: def({
    method: "PUT",
    path: "/threads/read",
    request: MarkThreadReadRequestSchema,
    response: MarkThreadReadResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  openDm: def({
    method: "POST",
    path: "/dm",
    request: OpenDmRequestSchema,
    response: OpenDmResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  dmMessages: def({
    method: "GET",
    path: "/dm/:id/messages",
    request: DmHistoryRequestSchema,
    response: DmHistoryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  editDmMessage: def({
    method: "PATCH",
    path: "/dm/:threadId/messages/:messageId",
    request: EditChatMessageRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  editChatMessage: def({
    method: "PATCH",
    path: "/messages",
    request: EditMessageRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setMessagePinned: def({
    method: "PUT",
    path: "/messages/pin",
    request: SetMessagePinnedRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  toggleMessageReaction: def({
    method: "POST",
    path: "/messages/reactions",
    request: ToggleMessageReactionRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  createPoll: def({
    method: "POST",
    path: "/messages/poll",
    request: CreatePollRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  votePoll: def({
    method: "PUT",
    path: "/messages/poll/vote",
    request: VotePollRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  closePoll: def({
    method: "POST",
    path: "/messages/poll/close",
    request: ClosePollRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  deleteDmMessage: def({
    method: "DELETE",
    path: "/dm/:threadId/messages/:messageId",
    request: DeleteDmMessageRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  deleteCleanupMessage: def({
    method: "DELETE",
    path: "/cleanups/:cleanupId/messages/:messageId",
    request: DeleteCleanupMessageRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  toggleCleanupMessageReaction: def({
    method: "POST",
    path: "/cleanups/:cleanupId/messages/:messageId/reactions",
    request: ToggleCleanupMessageReactionRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  toggleDmMessageReaction: def({
    method: "POST",
    path: "/dm/:threadId/messages/:messageId/reactions",
    request: ToggleDmMessageReactionRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  reportMessages: def({
    method: "GET",
    path: "/reports/:id/messages",
    request: ReportChatHistoryRequestSchema,
    response: ChatHistoryResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  deleteReportMessage: def({
    method: "DELETE",
    path: "/reports/:id/messages/:messageId",
    request: DeleteReportMessageRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  toggleReportMessageReaction: def({
    method: "POST",
    path: "/reports/:id/messages/:messageId/reactions",
    request: ToggleReportMessageReactionRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  joinReportChat: def({
    method: "POST",
    path: "/reports/:id/chat/join",
    request: JoinReportChatRequestSchema,
    response: OkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getReportChatParticipants: def({
    method: "GET",
    path: "/reports/:id/chat/participants",
    request: null,
    response: ReportChatParticipantsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  leaveReportChat: def({
    method: "POST",
    path: "/reports/:id/chat/leave",
    request: LeaveReportChatRequestSchema,
    response: OkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  toggleConversationMute: def({
    method: "PUT",
    path: "/conversations/mute",
    request: ToggleMuteRequestSchema,
    response: ToggleMuteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  toggleConversationHidden: def({
    method: "PUT",
    path: "/conversations/hidden",
    request: ToggleHiddenRequestSchema,
    response: ToggleHiddenResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
