import { def } from "./def.js"
import {
  CreateCleanupRequestSchema,
  UpdateCleanupRequestSchema,
  CancelCleanupRequestSchema,
  CleanupDTOSchema,
  ListCleanupsRequestSchema,
  GetCleanupResponseSchema,
  JoinCleanupResponseSchema,
  LeaveCleanupResponseSchema,
  CleanupAttendeesResponseSchema,
  SetMemberRoleRequestSchema,
  SetMemberRoleResponseSchema,
  RemoveMemberRequestSchema,
  RemoveMemberResponseSchema,
  RequestEventResourcesRequestSchema,
  RequestEventResourcesResponseSchema,
  CompleteCleanupRequestSchema,
  ClaimEventSlotRequestSchema,
  GuestRsvpRequestRequestSchema,
  GuestRsvpRequestResponseSchema,
  GuestRsvpVerifyRequestSchema,
  GuestRsvpVerifyResponseSchema,
  GuestRsvpCancelRequestSchema,
  GuestRsvpCancelResponseSchema,
  DuplicateCleanupRequestSchema,
  GetCleanupGuestsRequestSchema,
  GetCleanupGuestsResponseSchema,
} from "../../schemas/cleanups.js"
import { ChatHistoryRequestSchema, ChatHistoryResponseSchema } from "../../schemas/chat.js"
import { pageResponse } from "../../schemas/common.js"

export const cleanupEndpoints = {
  createCleanup: def({
    method: "POST",
    path: "/cleanups",
    request: CreateCleanupRequestSchema,
    response: CleanupDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listCleanups: def({
    method: "GET",
    path: "/cleanups",
    request: ListCleanupsRequestSchema,
    response: pageResponse(CleanupDTOSchema),
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  getCleanup: def({
    method: "GET",
    path: "/cleanups/:id",
    request: null,
    response: GetCleanupResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  updateCleanup: def({
    method: "PATCH",
    path: "/cleanups/:id",
    request: UpdateCleanupRequestSchema,
    response: GetCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  duplicateCleanup: def({
    method: "POST",
    path: "/cleanups/:id/duplicate",
    request: DuplicateCleanupRequestSchema,
    response: GetCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  joinCleanup: def({
    method: "POST",
    path: "/cleanups/:id/join",
    request: null,
    response: JoinCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  leaveCleanup: def({
    method: "POST",
    path: "/cleanups/:id/leave",
    request: null,
    response: LeaveCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  cleanupMessages: def({
    method: "GET",
    path: "/cleanups/:id/messages",
    request: ChatHistoryRequestSchema,
    response: ChatHistoryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getCleanupAttendees: def({
    method: "GET",
    path: "/cleanups/:id/attendees",
    request: null,
    response: CleanupAttendeesResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  guestRsvpRequest: def({
    method: "POST",
    path: "/cleanups/:id/guest-rsvp/request",
    request: GuestRsvpRequestRequestSchema,
    response: GuestRsvpRequestResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  guestRsvpVerify: def({
    method: "POST",
    path: "/cleanups/:id/guest-rsvp/verify",
    request: GuestRsvpVerifyRequestSchema,
    response: GuestRsvpVerifyResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  guestRsvpCancel: def({
    method: "POST",
    path: "/guest-rsvp/cancel",
    request: GuestRsvpCancelRequestSchema,
    response: GuestRsvpCancelResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  getCleanupGuests: def({
    method: "GET",
    path: "/cleanups/:id/guests",
    request: GetCleanupGuestsRequestSchema,
    response: GetCleanupGuestsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  cancelCleanup: def({
    method: "POST",
    path: "/cleanups/:id/cancel",
    request: CancelCleanupRequestSchema,
    response: GetCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  completeCleanup: def({
    method: "POST",
    path: "/cleanups/:id/complete",
    request: CompleteCleanupRequestSchema,
    response: GetCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  claimEventSlot: def({
    method: "PUT",
    path: "/cleanups/:id/slot",
    request: ClaimEventSlotRequestSchema,
    response: GetCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  requestEventResources: def({
    method: "POST",
    path: "/cleanups/:id/request-resources",
    request: RequestEventResourcesRequestSchema,
    response: RequestEventResourcesResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setCleanupMemberRole: def({
    method: "PATCH",
    path: "/cleanups/:id/members/:userId",
    request: SetMemberRoleRequestSchema,
    response: SetMemberRoleResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  removeCleanupMember: def({
    method: "DELETE",
    path: "/cleanups/:id/members/:userId",
    request: RemoveMemberRequestSchema,
    response: RemoveMemberResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
