import { def } from "./def.js"
import { ChatHistoryResponseSchema, ChatMessageDTOSchema } from "../../schemas/chat.js"
import {
  ChatGroupDTOSchema,
  CreateChatGroupRequestSchema,
  GetChatGroupRequestSchema,
  UpdateChatGroupRequestSchema,
  GroupHistoryRequestSchema,
  AddGroupMembersRequestSchema,
  RemoveGroupMemberRequestSchema,
  SetGroupMemberRoleRequestSchema,
  ListGroupMembersRequestSchema,
  ListGroupMembersResponseSchema,
  GroupMemberDTOSchema,
  DeleteGroupMessageRequestSchema,
} from "../../schemas/groups.js"
import { OkResponseSchema } from "../../schemas/internal-fields.js"

export const groupEndpoints = {
  createChatGroup: def({
    method: "POST",
    path: "/groups",
    request: CreateChatGroupRequestSchema,
    response: ChatGroupDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getChatGroup: def({
    method: "GET",
    path: "/groups/:id",
    request: GetChatGroupRequestSchema,
    response: ChatGroupDTOSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  groupMessages: def({
    method: "GET",
    path: "/groups/:id/messages",
    request: GroupHistoryRequestSchema,
    response: ChatHistoryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  updateChatGroup: def({
    method: "PATCH",
    path: "/groups/:id",
    request: UpdateChatGroupRequestSchema,
    response: ChatGroupDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  addGroupMembers: def({
    method: "POST",
    path: "/groups/:id/members",
    request: AddGroupMembersRequestSchema,
    response: ListGroupMembersResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  removeGroupMember: def({
    method: "DELETE",
    path: "/groups/:id/members/:userId",
    request: RemoveGroupMemberRequestSchema,
    response: OkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setGroupMemberRole: def({
    method: "PUT",
    path: "/groups/:id/members/:userId/role",
    request: SetGroupMemberRoleRequestSchema,
    response: GroupMemberDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listGroupMembers: def({
    method: "GET",
    path: "/groups/:id/members",
    request: ListGroupMembersRequestSchema,
    response: ListGroupMembersResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  deleteGroupMessage: def({
    method: "DELETE",
    path: "/groups/:id/messages/:messageId",
    request: DeleteGroupMessageRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  joinChatGroup: def({
    method: "POST",
    path: "/groups/:id/join",
    request: GetChatGroupRequestSchema,
    response: ChatGroupDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
