import { def } from "./def.js"
import {
  TileInfoResponseSchema,
  ResolveJurisdictionRequestSchema,
  JurisdictionDTOSchema,
  ReverseLabelRequestSchema,
  ReverseLabelResponseSchema,
  ResolveAddressRequestSchema,
  ResolveAddressResponseSchema,
  SuggestPlacesRequestSchema,
  SuggestPlacesResponseSchema,
  ListCleanupsInBBoxRequestSchema,
  MapCleanupsResponseSchema,
  SuggestContactRequestSchema,
  SuggestContactResponseSchema,
} from "../../schemas/map.js"
import {
  GetApproximateLocationRequestSchema,
  GetApproximateLocationResponseSchema,
} from "../../schemas/geo.js"

export const mapEndpoints = {
  getApproximateLocation: def({
    method: "GET",
    path: "/geo/approximate",
    request: GetApproximateLocationRequestSchema,
    response: GetApproximateLocationResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),

  tileInfo: def({
    method: "GET",
    path: "/map/tileinfo",
    request: null,
    response: TileInfoResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  resolveJurisdiction: def({
    method: "POST",
    path: "/map/resolve-jurisdiction",
    request: ResolveJurisdictionRequestSchema,
    response: JurisdictionDTOSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  reverseLabel: def({
    method: "POST",
    path: "/map/reverse-label",
    request: ReverseLabelRequestSchema,
    response: ReverseLabelResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  resolveAddress: def({
    method: "POST",
    path: "/map/resolve-address",
    request: ResolveAddressRequestSchema,
    response: ResolveAddressResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  suggest: def({
    method: "POST",
    path: "/map/suggest",
    request: SuggestPlacesRequestSchema,
    response: SuggestPlacesResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  mapCleanups: def({
    method: "GET",
    path: "/map/cleanups",
    request: ListCleanupsInBBoxRequestSchema,
    response: MapCleanupsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  suggestJurisdictionContact: def({
    method: "POST",
    path: "/map/jurisdictions/:geoid/suggest-contact",
    request: SuggestContactRequestSchema,
    response: SuggestContactResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
} as const
