import { def } from "./def.js"
import {
  PostComposeInputSchema,
  CreatePostResponseSchema,
  GetPostResponseSchema,
  DeletePostResponseSchema,
  ListRepliesResponseSchema,
  RepostResponseSchema,
  LikePostResponseSchema,
  SavePostResponseSchema,
  HomeFeedQuerySchema,
  PostRepliesQuerySchema,
  UserPostsQuerySchema,
  HomeFeedResponseSchema,
  FeedCountsRequestSchema,
  FeedCountsResponseSchema,
  ListUserPostsResponseSchema,
  ListSavesResponseSchema,
} from "../../schemas/posts.js"
import { PaginationQuerySchema } from "../../schemas/common.js"

export const postEndpoints = {
  createPost: def({
    method: "POST",
    path: "/posts",
    request: PostComposeInputSchema,
    response: CreatePostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getPost: def({
    method: "GET",
    path: "/posts/:id",
    request: null,
    response: GetPostResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  deletePost: def({
    method: "DELETE",
    path: "/posts/:id",
    request: null,
    response: DeletePostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listReplies: def({
    method: "GET",
    path: "/posts/:id/replies",
    request: PostRepliesQuerySchema,
    response: ListRepliesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  repostPost: def({
    method: "POST",
    path: "/posts/:id/repost",
    request: null,
    response: RepostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unrepostPost: def({
    method: "DELETE",
    path: "/posts/:id/repost",
    request: null,
    response: RepostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  likePost: def({
    method: "POST",
    path: "/posts/:id/like",
    request: null,
    response: LikePostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unlikePost: def({
    method: "DELETE",
    path: "/posts/:id/like",
    request: null,
    response: LikePostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  savePost: def({
    method: "POST",
    path: "/posts/:id/save",
    request: null,
    response: SavePostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unsavePost: def({
    method: "DELETE",
    path: "/posts/:id/save",
    request: null,
    response: SavePostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  homeFeed: def({
    method: "GET",
    path: "/feed/home",
    request: HomeFeedQuerySchema,
    response: HomeFeedResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  getFeedCounts: def({
    method: "POST",
    path: "/feed/counts",
    request: FeedCountsRequestSchema,
    response: FeedCountsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  listUserPosts: def({
    method: "GET",
    path: "/people/:id/posts",
    request: UserPostsQuerySchema,
    response: ListUserPostsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  listSaves: def({
    method: "GET",
    path: "/me/saves",
    request: PaginationQuerySchema,
    response: ListSavesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
} as const
