import { def } from "./def.js"
import {
  CreateReportRequestSchema,
  GetReportResponseSchema,
  ListMyReportsRequestSchema,
  ListMyReportsResponseSchema,
  ListReportsInBBoxRequestSchema,
  ListReportsSearchRequestSchema,
  ListReportsSearchResponseSchema,
  ReportClusterResponseSchema,
  ReportDTOSchema,
  ResolveReportRequestSchema,
  UnlistReportRequestSchema,
} from "../../schemas/reports.js"

export const reportEndpoints = {
  createReport: def({
    method: "POST",
    path: "/reports",
    request: CreateReportRequestSchema,
    response: ReportDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getReport: def({
    method: "GET",
    path: "/reports/:id",
    request: null,
    response: GetReportResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  listMyReports: def({
    method: "GET",
    path: "/reports",
    request: ListMyReportsRequestSchema,
    response: ListMyReportsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  mapReports: def({
    method: "GET",
    path: "/map/reports",
    request: ListReportsInBBoxRequestSchema,
    response: ReportClusterResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  searchReports: def({
    method: "GET",
    path: "/reports/search",
    request: ListReportsSearchRequestSchema,
    response: ListReportsSearchResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  resolveReport: def({
    method: "POST",
    path: "/reports/:id/resolve",
    request: ResolveReportRequestSchema,
    response: ReportDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unlistReport: def({
    method: "POST",
    path: "/reports/:id/unlist",
    request: UnlistReportRequestSchema,
    response: ReportDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
