import { def } from "./def.js"
import {
  ListPeopleRequestSchema,
  ListPeopleResponseSchema,
  FollowPersonResponseSchema,
  GetProfileResponseSchema,
  ProfileEventsRequestSchema,
  ProfileEventsResponseSchema,
  SearchUsersRequestSchema,
  SearchUsersResponseSchema,
  FollowSuggestionsRequestSchema,
  FollowSuggestionsResponseSchema,
  MentionSearchRequestSchema,
  BlockUserResponseSchema,
  ListBlocksResponseSchema,
  ConnectionsListQuerySchema,
} from "../../schemas/social.js"
import { ReportContentRequestSchema, ReportContentResponseSchema } from "../../schemas/content-report.js"
import { PaginationQuerySchema } from "../../schemas/common.js"

export const socialEndpoints = {
  listPeople: def({
    method: "GET",
    path: "/people",
    request: ListPeopleRequestSchema,
    response: ListPeopleResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  searchUsers: def({
    method: "GET",
    path: "/users/search",
    request: SearchUsersRequestSchema,
    response: SearchUsersResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  followSuggestions: def({
    method: "GET",
    path: "/users/follow-suggestions",
    request: FollowSuggestionsRequestSchema,
    response: FollowSuggestionsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  mentionSearch: def({
    method: "GET",
    path: "/users/mention-search",
    request: MentionSearchRequestSchema,
    response: SearchUsersResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  blockUser: def({
    method: "POST",
    path: "/users/:id/block",
    request: null,
    response: BlockUserResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unblockUser: def({
    method: "DELETE",
    path: "/users/:id/block",
    request: null,
    response: BlockUserResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listBlocks: def({
    method: "GET",
    path: "/me/blocks",
    request: PaginationQuerySchema,
    response: ListBlocksResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  followPerson: def({
    method: "POST",
    path: "/people/:id/follow",
    request: null,
    response: FollowPersonResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unfollowPerson: def({
    method: "DELETE",
    path: "/people/:id/follow",
    request: null,
    response: FollowPersonResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getProfile: def({
    method: "GET",
    path: "/people/:id",
    request: null,
    response: GetProfileResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  getProfileEvents: def({
    method: "GET",
    path: "/people/:id/events",
    request: ProfileEventsRequestSchema,
    response: ProfileEventsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  listFollowers: def({
    method: "GET",
    path: "/people/:id/followers",
    request: ConnectionsListQuerySchema,
    response: ListPeopleResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  listFollowing: def({
    method: "GET",
    path: "/people/:id/following",
    request: ConnectionsListQuerySchema,
    response: ListPeopleResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  reportContent: def({
    method: "POST",
    path: "/content-reports",
    request: ReportContentRequestSchema,
    response: ReportContentResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
