import { def } from "./def.js"
import {
  GetMyHoursResponseSchema,
  LeaderboardQuerySchema,
  LeaderboardResponseSchema,
  LogEventHoursRequestSchema,
  LogEventHoursResponseSchema,
  EventHoursQuerySchema,
  EventHoursResponseSchema,
  MyVolunteerHoursEntriesQuerySchema,
  MyVolunteerHoursEntriesResponseSchema,
  PublicVolunteerHoursQuerySchema,
  PublicVolunteerHoursResponseSchema,
} from "../../schemas/volunteer.js"
import {
  IssueServiceHoursCertificateRequestSchema,
  IssueServiceHoursCertificateResponseSchema,
  ListMyCertificatesResponseSchema,
  RevokeCertificateRequestSchema,
  RevokeCertificateResponseSchema,
  VerifyCertificateRequestSchema,
  VerifyCertificateResponseSchema,
} from "../../schemas/certificates.js"

export const volunteerEndpoints = {
  getMyHours: def({
    method: "GET",
    path: "/me/volunteer-hours",
    request: null,
    response: GetMyHoursResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getMyHoursEntries: def({
    method: "GET",
    path: "/me/volunteer-hours/entries",
    request: MyVolunteerHoursEntriesQuerySchema,
    response: MyVolunteerHoursEntriesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getPublicVolunteerHours: def({
    method: "GET",
    path: "/people/:id/volunteer-hours",
    request: PublicVolunteerHoursQuerySchema,
    response: PublicVolunteerHoursResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),

  logEventHours: def({
    method: "POST",
    path: "/cleanups/:id/hours",
    request: LogEventHoursRequestSchema,
    response: LogEventHoursResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getEventHours: def({
    method: "GET",
    path: "/cleanups/:id/hours",
    request: EventHoursQuerySchema,
    response: EventHoursResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  getJurisdictionLeaderboard: def({
    method: "GET",
    path: "/jurisdictions/:geoid/leaderboard",
    request: LeaderboardQuerySchema,
    response: LeaderboardResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),

  issueServiceHoursCertificate: def({
    method: "POST",
    path: "/me/volunteer-hours/certificates",
    request: IssueServiceHoursCertificateRequestSchema,
    response: IssueServiceHoursCertificateResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listMyServiceHoursCertificates: def({
    method: "GET",
    path: "/me/volunteer-hours/certificates",
    request: null,
    response: ListMyCertificatesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  revokeServiceHoursCertificate: def({
    method: "POST",
    path: "/me/volunteer-hours/certificates/:code/revoke",
    request: RevokeCertificateRequestSchema,
    response: RevokeCertificateResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  verifyServiceHoursCertificate: def({
    method: "GET",
    path: "/service-hours/verify/:code",
    request: VerifyCertificateRequestSchema,
    response: VerifyCertificateResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
} as const
