import { z } from "zod"

import type { EndpointVersion } from "./versioning.js"
import {
  AppleSignInRequestSchema,
  AppleCallbackBodySchema,
  GoogleSignInRequestSchema,
  OAuthStartQuerySchema,
  OAuthCallbackQuerySchema,
  EmailOtpRequestRequestSchema,
  EmailOtpRequestResponseSchema,
  EmailOtpVerifyRequestSchema,
  SessionResponseSchema,
  SessionCheckResponseSchema,
  LogoutResponseSchema,
  WsTicketResponseSchema,
} from "../schemas/auth.js"
import {
  CreateReportRequestSchema,
  GetReportResponseSchema,
  ListMyReportsRequestSchema,
  ListMyReportsResponseSchema,
  ListReportsInBBoxRequestSchema,
  ListReportsSearchRequestSchema,
  ListReportsSearchResponseSchema,
  ReportClusterResponseSchema,
  ReportDTOSchema,
  ResolveReportRequestSchema,
  UnlistReportRequestSchema,
} from "../schemas/reports.js"
import {
  TileInfoResponseSchema,
  ResolveJurisdictionRequestSchema,
  JurisdictionDTOSchema,
  ReverseLabelRequestSchema,
  ReverseLabelResponseSchema,
  ResolveAddressRequestSchema,
  ResolveAddressResponseSchema,
  SuggestPlacesRequestSchema,
  SuggestPlacesResponseSchema,
  ListCleanupsInBBoxRequestSchema,
  MapCleanupsResponseSchema,
  SuggestContactRequestSchema,
  SuggestContactResponseSchema,
} from "../schemas/map.js"
import {
  GetApproximateLocationRequestSchema,
  GetApproximateLocationResponseSchema,
} from "../schemas/geo.js"
import {
  CreateCleanupRequestSchema,
  UpdateCleanupRequestSchema,
  CancelCleanupRequestSchema,
  CleanupDTOSchema,
  ListCleanupsRequestSchema,
  GetCleanupResponseSchema,
  JoinCleanupResponseSchema,
  LeaveCleanupResponseSchema,
  CleanupAttendeesResponseSchema,
  SetMemberRoleRequestSchema,
  SetMemberRoleResponseSchema,
  RemoveMemberRequestSchema,
  RemoveMemberResponseSchema,
  RequestEventResourcesRequestSchema,
  RequestEventResourcesResponseSchema,
  CompleteCleanupRequestSchema,
  ClaimEventSlotRequestSchema,
  GuestRsvpRequestRequestSchema,
  GuestRsvpRequestResponseSchema,
  GuestRsvpVerifyRequestSchema,
  GuestRsvpVerifyResponseSchema,
  GuestRsvpCancelRequestSchema,
  GuestRsvpCancelResponseSchema,
  DuplicateCleanupRequestSchema,
  GetCleanupGuestsRequestSchema,
  GetCleanupGuestsResponseSchema,
} from "../schemas/cleanups.js"
import {
  ChatHistoryRequestSchema,
  ChatHistoryResponseSchema,
  ChatMessageDTOSchema,
  ListThreadsResponseSchema,
  MarkThreadReadRequestSchema,
  MarkThreadReadResponseSchema,
  OpenDmRequestSchema,
  OpenDmResponseSchema,
  DmHistoryRequestSchema,
  DmHistoryResponseSchema,
  EditChatMessageRequestSchema,
  EditMessageRequestSchema,
  SetMessagePinnedRequestSchema,
  ToggleMessageReactionRequestSchema,
  DeleteDmMessageRequestSchema,
  DeleteCleanupMessageRequestSchema,
  ToggleCleanupMessageReactionRequestSchema,
  ToggleDmMessageReactionRequestSchema,
  ReportChatHistoryRequestSchema,
  DeleteReportMessageRequestSchema,
  ToggleReportMessageReactionRequestSchema,
  CreatePollRequestSchema,
  VotePollRequestSchema,
  ClosePollRequestSchema,
} from "../schemas/chat.js"
import {
  JoinReportChatRequestSchema,
  LeaveReportChatRequestSchema,
  ReportChatParticipantsResponseSchema,
  ToggleMuteRequestSchema,
  ToggleMuteResponseSchema,
  ToggleHiddenRequestSchema,
  ToggleHiddenResponseSchema,
} from "../schemas/report-chat.js"
import {
  ChatGroupDTOSchema,
  CreateChatGroupRequestSchema,
  GetChatGroupRequestSchema,
  UpdateChatGroupRequestSchema,
  GroupHistoryRequestSchema,
  AddGroupMembersRequestSchema,
  RemoveGroupMemberRequestSchema,
  SetGroupMemberRoleRequestSchema,
  ListGroupMembersRequestSchema,
  ListGroupMembersResponseSchema,
  GroupMemberDTOSchema,
  DeleteGroupMessageRequestSchema,
} from "../schemas/groups.js"
import {
  ListPeopleRequestSchema,
  ListPeopleResponseSchema,
  FollowPersonResponseSchema,
  GetProfileResponseSchema,
  ProfileEventsRequestSchema,
  ProfileEventsResponseSchema,
  UpdateProfileRequestSchema,
  UpdateProfileResponseSchema,
  HandleAvailableRequestSchema,
  HandleAvailableResponseSchema,
  SearchUsersRequestSchema,
  SearchUsersResponseSchema,
  FollowSuggestionsRequestSchema,
  FollowSuggestionsResponseSchema,
  MentionSearchRequestSchema,
  UpdateSettingsRequestSchema,
  UpdateSettingsResponseSchema,
  DeleteAccountRequestSchema,
  DeleteAccountResponseSchema,
  RequestDataExportResponseSchema,
  BlockUserResponseSchema,
  ListBlocksResponseSchema,
  ConnectionsListQuerySchema,
} from "../schemas/social.js"
import {
  PostComposeInputSchema,
  CreatePostResponseSchema,
  GetPostResponseSchema,
  DeletePostResponseSchema,
  ListRepliesResponseSchema,
  RepostResponseSchema,
  LikePostResponseSchema,
  SavePostResponseSchema,
  HomeFeedQuerySchema,
  PostRepliesQuerySchema,
  UserPostsQuerySchema,
  HomeFeedResponseSchema,
  FeedCountsRequestSchema,
  FeedCountsResponseSchema,
  ListUserPostsResponseSchema,
  ListSavesResponseSchema,
} from "../schemas/posts.js"
import {
  ReportContentRequestSchema,
  ReportContentResponseSchema,
} from "../schemas/content-report.js"
import {
  GetMyHoursResponseSchema,
  LeaderboardQuerySchema,
  LeaderboardResponseSchema,
  LogEventHoursRequestSchema,
  LogEventHoursResponseSchema,
  EventHoursQuerySchema,
  EventHoursResponseSchema,
  MyVolunteerHoursEntriesQuerySchema,
  MyVolunteerHoursEntriesResponseSchema,
  PublicVolunteerHoursQuerySchema,
  PublicVolunteerHoursResponseSchema,
} from "../schemas/volunteer.js"
import {
  IssueServiceHoursCertificateRequestSchema,
  IssueServiceHoursCertificateResponseSchema,
  ListMyCertificatesResponseSchema,
  RevokeCertificateRequestSchema,
  RevokeCertificateResponseSchema,
  VerifyCertificateRequestSchema,
  VerifyCertificateResponseSchema,
} from "../schemas/certificates.js"
import {
  ListNotificationsResponseSchema,
  MarkReadRequestSchema,
  MarkReadResponseSchema,
  GetNotificationPrefsResponseSchema,
  UpdateNotificationPrefsRequestSchema,
  RegisterPushTokenRequestSchema,
  RegisterPushTokenResponseSchema,
  UnregisterPushTokenRequestSchema,
} from "../schemas/notifications.js"
import {
  CreateMediaUploadRequestSchema,
  CreateMediaUploadResponseSchema,
  FinalizeMediaRequestSchema,
  FinalizeMediaResponseSchema,
  GetMediaResponseSchema,
} from "../schemas/media.js"
import {
  AnonReportRequestSchema,
  AnonReportResponseSchema,
  AnonReportStatusRequestSchema,
  AnonReportStatusResponseSchema,
} from "../schemas/anon.js"
import {
  ClaimNudgeRequestSchema,
  ClaimNudgeResponseSchema,
  ClaimReportRequestSchema,
  ClaimReportResponseSchema,
} from "../schemas/claim.js"
import { PaginationQuerySchema } from "../schemas/common.js"

import {
  AdminLoginResponseSchema,
  AdminSessionResponseSchema,
  AdminLogoutResponseSchema,
} from "../schemas/admin/auth.js"
import { HomeSummaryResponseSchema, HomeMapResponseSchema } from "../schemas/admin/home.js"
import {
  DiscoveryListQuerySchema,
  DiscoveryListResponseSchema,
  GetDiscoveryTaskResponseSchema,
  AddNoteRequestSchema,
  FlagDiscoveryRequestSchema,
  SaveDraftRequestSchema,
} from "../schemas/admin/discovery.js"
import {
  SaveContactsRequestSchema,
  JurisdictionListQuerySchema,
  JurisdictionDirectoryResponseSchema,
  JurisdictionGeometryRequestSchema,
  JurisdictionGeometryResponseSchema,
  PatchJurisdictionRequestSchema,
} from "../schemas/admin/jurisdictions.js"
import {
  AdminReportListQuerySchema,
  AdminReportListResponseSchema,
  GetAdminReportResponseSchema,
  SetReportStatusRequestSchema,
  FlagReportRequestSchema,
  RemoveReportRequestSchema,
  SendFollowupRequestSchema,
  RouteReportRequestSchema,
  RouteReportResponseSchema,
  SetReportVerdictRequestSchema,
  SetReportVerdictResponseSchema,
  AdminReportMessagesRequestSchema,
  AdminReportMessagesResponseSchema,
  AdminSendReportMessageRequestSchema,
  AdminSendReportMessageResponseSchema,
  AdminRemoveReportMessageRequestSchema,
} from "../schemas/admin/reports.js"
import {
  AdminEventListQuerySchema,
  AdminEventListResponseSchema,
  GetAdminEventResponseSchema,
  SetEventStatusRequestSchema,
  FlagEventRequestSchema,
  CancelRequestSchema,
  PostMessageRequestSchema,
  SetEventOutcomeRequestSchema,
  LinkEventReportsRequestSchema,
} from "../schemas/admin/events.js"
import {
  AdminUserListQuerySchema,
  AdminUserListResponseSchema,
  GetAdminUserResponseSchema,
  UserSubListQuerySchema,
  UserReportsResponseSchema,
  UserEventsResponseSchema,
  UserMessagesResponseSchema,
  FlagUserRequestSchema,
  SetUserStatusRequestSchema,
  SetRoleRequestSchema,
  SetUserReportVerifiedRequestSchema,
  RemoveUserMessageRequestSchema,
} from "../schemas/admin/users.js"
import {
  GovClaimListQuerySchema,
  GovClaimListResponseSchema,
  GetGovClaimResponseSchema,
  VerifyCheckRequestSchema,
  ApproveGovClaimRequestSchema,
  RejectGovClaimRequestSchema,
} from "../schemas/admin/gov.js"
import {
  ModerationListQuerySchema,
  ModerationListResponseSchema,
  GetModerationItemResponseSchema,
  ApproveModerationRequestSchema,
  RemoveModerationRequestSchema,
  HoldModerationRequestSchema,
  AppealModerationRequestSchema,
} from "../schemas/admin/moderation.js"
import {
  MailListQuerySchema,
  MailListResponseSchema,
  GetMailThreadResponseSchema,
  MailStatsResponseSchema,
  ComposeRequestSchema,
  ReplyRequestSchema,
  MarkMailReadRequestSchema,
  SetMailStatusRequestSchema,
  ResendRequestSchema,
} from "../schemas/admin/mail.js"
import {
  GetForwardTemplateDefaultResponseSchema,
  SetForwardTemplateDefaultRequestSchema,
  PreviewForwardTemplateRequestSchema,
  PreviewForwardTemplateResponseSchema,
} from "../schemas/admin/forward-template.js"
import {
  InboxListQuerySchema,
  InboxListResponseSchema,
  GetInboxMessageResponseSchema,
  SetInboxStatusRequestSchema,
} from "../schemas/admin/inbox.js"
import {
  AnalyticsKpisResponseSchema,
  AnalyticsPinsByWeekResponseSchema,
  AnalyticsByCategoryResponseSchema,
  AnalyticsFunnelResponseSchema,
  AnalyticsCoverageResponseSchema,
  AnalyticsResolutionByCategoryResponseSchema,
  AnalyticsEventsResponseSchema,
  AnalyticsTopJurisdictionsResponseSchema,
  AnalyticsTopContributorsResponseSchema,
  AnalyticsHeatmapResponseSchema,
  AnalyticsRetentionResponseSchema,
} from "../schemas/admin/analytics.js"
import { ActivityListQuerySchema, ActivityListResponseSchema } from "../schemas/admin/activity.js"
import { AuditListQuerySchema, AuditListResponseSchema } from "../schemas/admin/audit.js"
import { SystemHealthResponseSchema } from "../schemas/admin/system.js"
import { AdminOkResponseSchema } from "../schemas/admin/common.js"
import {
  AcceptOrganizationInviteRequestSchema,
  AcceptOrganizationInviteResponseSchema,
  ApplyOrganizationVerificationRequestSchema,
  ApplyOrganizationVerificationResponseSchema,
  CreateOrganizationRequestSchema,
  CreateOrganizationResponseSchema,
  GetOrganizationRequestSchema,
  GetOrganizationResponseSchema,
  GetOrganizationVerificationRequestSchema,
  GetOrganizationVerificationResponseSchema,
  AcceptMyOrgInviteRequestSchema,
  AcceptMyOrgInviteResponseSchema,
  DeclineMyOrgInviteRequestSchema,
  DeclineMyOrgInviteResponseSchema,
  InviteOrganizationMemberRequestSchema,
  InviteOrganizationMemberResponseSchema,
  ListMyOrgInvitesResponseSchema,
  ListMyOrganizationsResponseSchema,
  ListOrganizationEventsRequestSchema,
  ListOrganizationEventsResponseSchema,
  ListOrganizationInvitesRequestSchema,
  ListOrganizationInvitesResponseSchema,
  ListOrganizationMembersRequestSchema,
  ListOrganizationMembersResponseSchema,
  RemoveOrganizationMemberRequestSchema,
  RemoveOrganizationMemberResponseSchema,
  RevokeOrganizationInviteRequestSchema,
  RevokeOrganizationInviteResponseSchema,
  SetOrganizationMemberRoleRequestSchema,
  SetOrganizationMemberRoleResponseSchema,
  UpdateOrganizationRequestSchema,
  UpdateOrganizationResponseSchema,
} from "../schemas/host/organizations.js"
import {
  AcceptEventTeamInviteRequestSchema,
  AcceptEventTeamInviteResponseSchema,
  AcceptMyEventInviteRequestSchema,
  AcceptMyEventInviteResponseSchema,
  DeclineMyEventInviteRequestSchema,
  DeclineMyEventInviteResponseSchema,
  InviteEventTeamMemberRequestSchema,
  InviteEventTeamMemberResponseSchema,
  ListEventTeamRequestSchema,
  ListEventTeamResponseSchema,
  ListMyEventInvitesRequestSchema,
  ListMyEventInvitesResponseSchema,
  RevokeEventTeamInviteRequestSchema,
  RevokeEventTeamInviteResponseSchema,
} from "../schemas/host/team.js"
import {
  ListMyHostedEventsRequestSchema,
  ListMyHostedEventsResponseSchema,
} from "../schemas/host/portfolio.js"
import {
  CreateEventTicketTypeRequestSchema,
  CreateEventTicketTypeResponseSchema,
  DeleteEventTicketTypeRequestSchema,
  DeleteEventTicketTypeResponseSchema,
  ListEventTicketTypesRequestSchema,
  ListEventTicketTypesResponseSchema,
  ReorderEventTicketTypesRequestSchema,
  ReorderEventTicketTypesResponseSchema,
  UpdateEventTicketTypeRequestSchema,
  UpdateEventTicketTypeResponseSchema,
} from "../schemas/host/tickets.js"
import {
  ListEventQuestionsRequestSchema,
  ListEventQuestionsResponseSchema,
  SaveEventQuestionsRequestSchema,
  SaveEventQuestionsResponseSchema,
} from "../schemas/host/questions.js"
import {
  CancelEventRegistrationRequestSchema,
  CancelEventRegistrationResponseSchema,
  CreateWalkupRegistrationRequestSchema,
  CreateWalkupRegistrationResponseSchema,
  GetEventRegistrationAnswersRequestSchema,
  GetEventRegistrationAnswersResponseSchema,
  GetEventRegistrationRequestSchema,
  GetEventRegistrationResponseSchema,
  ListEventRegistrationsRequestSchema,
  ListEventRegistrationsResponseSchema,
  RegisterForEventRequestSchema,
  RegisterForEventResponseSchema,
  RemoveEventRegistrationRequestSchema,
  RemoveEventRegistrationResponseSchema,
  SetEventRegistrationNoteRequestSchema,
  SetEventRegistrationNoteResponseSchema,
  TransferEventRegistrationRequestSchema,
  TransferEventRegistrationResponseSchema,
} from "../schemas/host/registrations.js"
import {
  ClaimWaitlistOfferRequestSchema,
  ClaimWaitlistOfferResponseSchema,
  JoinEventWaitlistRequestSchema,
  JoinEventWaitlistResponseSchema,
  LeaveEventWaitlistRequestSchema,
  LeaveEventWaitlistResponseSchema,
  ListEventWaitlistRequestSchema,
  ListEventWaitlistResponseSchema,
  PromoteFromWaitlistRequestSchema,
  PromoteFromWaitlistResponseSchema,
} from "../schemas/host/waitlist.js"
import {
  CheckEventPageSlugRequestSchema,
  CheckEventPageSlugResponseSchema,
  GetEventPageRequestSchema,
  GetEventPageResponseSchema,
  GetPublicEventPageRequestSchema,
  GetPublicEventPageResponseSchema,
  PublishEventPageRequestSchema,
  PublishEventPageResponseSchema,
  RecordEventPageViewRequestSchema,
  RecordEventPageViewResponseSchema,
  SaveEventPageRequestSchema,
  SaveEventPageResponseSchema,
} from "../schemas/host/pages.js"
import {
  CheckInEventSeatRequestSchema,
  CheckInEventSeatResponseSchema,
  GetEventCheckinCountersRequestSchema,
  GetEventCheckinCountersResponseSchema,
  GetGuestEventTicketRequestSchema,
  GetGuestEventTicketResponseSchema,
  GetMyEventTicketRequestSchema,
  GetMyEventTicketResponseSchema,
  MarkEventNoShowsRequestSchema,
  MarkEventNoShowsResponseSchema,
  ScanEventTicketRequestSchema,
  ScanEventTicketResponseSchema,
  UndoEventCheckInRequestSchema,
  UndoEventCheckInResponseSchema,
} from "../schemas/host/checkin.js"
import { GetEventIcsRequestSchema, GetEventIcsResponseSchema } from "../schemas/host/ics.js"
import {
  CancelEventBroadcastRequestSchema,
  CancelEventBroadcastResponseSchema,
  CreateEventBroadcastRequestSchema,
  CreateEventBroadcastResponseSchema,
  DeleteEventBroadcastRequestSchema,
  DeleteEventBroadcastResponseSchema,
  GetEventBroadcastRequestSchema,
  GetEventBroadcastResponseSchema,
  ListBroadcastDeliveriesRequestSchema,
  ListBroadcastDeliveriesResponseSchema,
  ListEventBroadcastsRequestSchema,
  ListEventBroadcastsResponseSchema,
  OpenUnsubscribeBroadcastsRequestSchema,
  OpenUnsubscribeBroadcastsResponseSchema,
  PreviewEventBroadcastRequestSchema,
  PreviewEventBroadcastResponseSchema,
  ScheduleEventBroadcastRequestSchema,
  ScheduleEventBroadcastResponseSchema,
  SendEventBroadcastRequestSchema,
  SendEventBroadcastResponseSchema,
  SetEventBroadcastMuteRequestSchema,
  SetEventBroadcastMuteResponseSchema,
  TestSendEventBroadcastRequestSchema,
  TestSendEventBroadcastResponseSchema,
  UnsubscribeBroadcastsRequestSchema,
  UnsubscribeBroadcastsResponseSchema,
  UpdateEventBroadcastRequestSchema,
  UpdateEventBroadcastResponseSchema,
} from "../schemas/host/broadcasts.js"
import {
  EventAnalyticsBroadcastsResponseSchema,
  EventAnalyticsCheckinsResponseSchema,
  EventAnalyticsOverviewResponseSchema,
  EventAnalyticsRegistrationsResponseSchema,
  EventAnalyticsRequestSchema,
  EventAnalyticsSourcesResponseSchema,
  GetEventAnalyticsRequestSchema,
  GetEventAnalyticsResponseSchema,
  HostAnalyticsSummaryRequestSchema,
  HostAnalyticsSummaryResponseSchema,
  HostedEventsAnalyticsRequestSchema,
  HostedEventsAnalyticsResponseSchema,
} from "../schemas/host/analytics.js"
import {
  CreateEventAnnouncementRequestSchema,
  CreateEventAnnouncementResponseSchema,
  GetEventAnnouncementRequestSchema,
  GetEventAnnouncementResponseSchema,
  ListEventAnnouncementsRequestSchema,
  ListEventAnnouncementsResponseSchema,
} from "../schemas/host/announcements.js"
import {
  GetEventInsightsRequestSchema,
  GetEventInsightsResponseSchema,
} from "../schemas/host/insights.js"
import {
  DownloadHostExportRequestSchema,
  DownloadHostExportResponseSchema,
  GetEventExportRequestSchema,
  GetEventExportResponseSchema,
  ListEventExportsRequestSchema,
  ListEventExportsResponseSchema,
  RequestEventExportRequestSchema,
  RequestEventExportResponseSchema,
} from "../schemas/host/exports.js"
import { GetLegalVersionsResponseSchema } from "../schemas/legal.js"
import {
  AdminAddOrgMemberRequestSchema,
  AdminAddOrgMemberResponseSchema,
  AdminCreateOrgRequestSchema,
  AdminCreateOrgResponseSchema,
  AdminOrgEventListRequestSchema,
  AdminOrgEventListResponseSchema,
  AdminOrgListQuerySchema,
  AdminOrgListResponseSchema,
  AdminOrgMemberListRequestSchema,
  AdminOrgMemberListResponseSchema,
  AdminOrgVerificationListQuerySchema,
  AdminOrgVerificationListResponseSchema,
  AdminRemoveOrgMemberRequestSchema,
  AdminRemoveOrgMemberResponseSchema,
  AdminSetOrgMemberRoleRequestSchema,
  AdminSetOrgMemberRoleResponseSchema,
  AdminSetOrgSuspendedRequestSchema,
  AdminSetOrgSuspendedResponseSchema,
  AdminUpdateOrgRequestSchema,
  AdminUpdateOrgResponseSchema,
  DecideOrgVerificationRequestSchema,
  DecideOrgVerificationResponseSchema,
  GetAdminOrgRequestSchema,
  GetAdminOrgResponseSchema,
} from "../schemas/admin/orgs.js"
import {
  AdminBroadcastListQuerySchema,
  AdminBroadcastListResponseSchema,
  AdminHostListQuerySchema,
  AdminHostListResponseSchema,
  SetHostMessagingSuspendedRequestSchema,
  SetHostMessagingSuspendedResponseSchema,
} from "../schemas/admin/hosts.js"
import {
  AdminEventPageListQuerySchema,
  AdminEventPageListResponseSchema,
  AdminGetEventPageRequestSchema,
  AdminGetEventPageResponseSchema,
  FlagEventPageRequestSchema,
  FlagEventPageResponseSchema,
  UnpublishEventPageRequestSchema,
  UnpublishEventPageResponseSchema,
} from "../schemas/admin/pages.js"
import {
  AdminGetMediaRequestSchema,
  AdminGetMediaResponseSchema,
} from "../schemas/admin/media.js"

export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE" | "PATCH"
export type EndpointAuth = "public" | "optional" | "required"

export interface EndpointDef<
  Req extends z.ZodTypeAny | null = z.ZodTypeAny | null,
  Res extends z.ZodTypeAny = z.ZodTypeAny,
  Path extends string = string,
> {
  method: HttpMethod
  path: Path
  request: Req
  response: Res
  auth: EndpointAuth
  csrf: boolean
  version: EndpointVersion
}

function def<Req extends z.ZodTypeAny | null, Res extends z.ZodTypeAny, Path extends string>(
  d: EndpointDef<Req, Res, Path>,
): EndpointDef<Req, Res, Path> {
  return d
}

const HealthzResponseSchema = z.object({ ok: z.literal(true) }).passthrough()
const OAuthStartResponseSchema = z.object({ url: z.string() })
const ReportChatOkResponseSchema = z.object({ ok: z.literal(true) })

export const coreEndpoints = {
  health: def({
    method: "GET",
    path: "/healthz",
    request: null,
    response: HealthzResponseSchema,
    auth: "public",
    csrf: false,
    version: "unversioned",
  }),

  appleSignIn: def({
    method: "POST",
    path: "/auth/apple",
    request: AppleSignInRequestSchema,
    response: SessionResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  googleSignIn: def({
    method: "POST",
    path: "/auth/google",
    request: GoogleSignInRequestSchema,
    response: SessionResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  googleStart: def({
    method: "GET",
    path: "/auth/google/start",
    request: OAuthStartQuerySchema,
    response: OAuthStartResponseSchema,
    auth: "public",
    csrf: false,
    version: "unversioned",
  }),
  googleCallback: def({
    method: "GET",
    path: "/auth/google/callback",
    request: OAuthCallbackQuerySchema,
    response: SessionResponseSchema,
    auth: "public",
    csrf: false,
    version: "unversioned",
  }),
  appleStart: def({
    method: "GET",
    path: "/auth/apple/start",
    request: OAuthStartQuerySchema,
    response: OAuthStartResponseSchema,
    auth: "public",
    csrf: false,
    version: "unversioned",
  }),
  appleCallback: def({
    method: "POST",
    path: "/auth/apple/callback",
    request: AppleCallbackBodySchema,
    response: SessionResponseSchema,
    auth: "public",
    csrf: false,
    version: "unversioned",
  }),
  otpRequest: def({
    method: "POST",
    path: "/auth/otp/request",
    request: EmailOtpRequestRequestSchema,
    response: EmailOtpRequestResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  otpVerify: def({
    method: "POST",
    path: "/auth/otp/verify",
    request: EmailOtpVerifyRequestSchema,
    response: SessionResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  session: def({
    method: "GET",
    path: "/auth/session",
    request: null,
    response: SessionCheckResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  logout: def({
    method: "POST",
    path: "/auth/logout",
    request: null,
    response: LogoutResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  wsTicket: def({
    method: "POST",
    path: "/ws-ticket",
    request: null,
    response: WsTicketResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  createReport: def({
    method: "POST",
    path: "/reports",
    request: CreateReportRequestSchema,
    response: ReportDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getReport: def({
    method: "GET",
    path: "/reports/:id",
    request: null,
    response: GetReportResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  listMyReports: def({
    method: "GET",
    path: "/reports",
    request: ListMyReportsRequestSchema,
    response: ListMyReportsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  mapReports: def({
    method: "GET",
    path: "/map/reports",
    request: ListReportsInBBoxRequestSchema,
    response: ReportClusterResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  searchReports: def({
    method: "GET",
    path: "/reports/search",
    request: ListReportsSearchRequestSchema,
    response: ListReportsSearchResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  resolveReport: def({
    method: "POST",
    path: "/reports/:id/resolve",
    request: ResolveReportRequestSchema,
    response: ReportDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unlistReport: def({
    method: "POST",
    path: "/reports/:id/unlist",
    request: UnlistReportRequestSchema,
    response: ReportDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  getApproximateLocation: def({
    method: "GET",
    path: "/geo/approximate",
    request: GetApproximateLocationRequestSchema,
    response: GetApproximateLocationResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),

  tileInfo: def({
    method: "GET",
    path: "/map/tileinfo",
    request: null,
    response: TileInfoResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  resolveJurisdiction: def({
    method: "POST",
    path: "/map/resolve-jurisdiction",
    request: ResolveJurisdictionRequestSchema,
    response: JurisdictionDTOSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  reverseLabel: def({
    method: "POST",
    path: "/map/reverse-label",
    request: ReverseLabelRequestSchema,
    response: ReverseLabelResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  resolveAddress: def({
    method: "POST",
    path: "/map/resolve-address",
    request: ResolveAddressRequestSchema,
    response: ResolveAddressResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  suggest: def({
    method: "POST",
    path: "/map/suggest",
    request: SuggestPlacesRequestSchema,
    response: SuggestPlacesResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  mapCleanups: def({
    method: "GET",
    path: "/map/cleanups",
    request: ListCleanupsInBBoxRequestSchema,
    response: MapCleanupsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  suggestJurisdictionContact: def({
    method: "POST",
    path: "/map/jurisdictions/:geoid/suggest-contact",
    request: SuggestContactRequestSchema,
    response: SuggestContactResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),

  createCleanup: def({
    method: "POST",
    path: "/cleanups",
    request: CreateCleanupRequestSchema,
    response: CleanupDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listCleanups: def({
    method: "GET",
    path: "/cleanups",
    request: ListCleanupsRequestSchema,
    response: z.object({ items: z.array(CleanupDTOSchema), nextCursor: z.string().nullable() }),
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  getCleanup: def({
    method: "GET",
    path: "/cleanups/:id",
    request: null,
    response: GetCleanupResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  updateCleanup: def({
    method: "PATCH",
    path: "/cleanups/:id",
    request: UpdateCleanupRequestSchema,
    response: GetCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  duplicateCleanup: def({
    method: "POST",
    path: "/cleanups/:id/duplicate",
    request: DuplicateCleanupRequestSchema,
    response: GetCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  joinCleanup: def({
    method: "POST",
    path: "/cleanups/:id/join",
    request: null,
    response: JoinCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  leaveCleanup: def({
    method: "POST",
    path: "/cleanups/:id/leave",
    request: null,
    response: LeaveCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  cleanupMessages: def({
    method: "GET",
    path: "/cleanups/:id/messages",
    request: ChatHistoryRequestSchema,
    response: ChatHistoryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getCleanupAttendees: def({
    method: "GET",
    path: "/cleanups/:id/attendees",
    request: null,
    response: CleanupAttendeesResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  guestRsvpRequest: def({
    method: "POST",
    path: "/cleanups/:id/guest-rsvp/request",
    request: GuestRsvpRequestRequestSchema,
    response: GuestRsvpRequestResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  guestRsvpVerify: def({
    method: "POST",
    path: "/cleanups/:id/guest-rsvp/verify",
    request: GuestRsvpVerifyRequestSchema,
    response: GuestRsvpVerifyResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  guestRsvpCancel: def({
    method: "POST",
    path: "/guest-rsvp/cancel",
    request: GuestRsvpCancelRequestSchema,
    response: GuestRsvpCancelResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  getCleanupGuests: def({
    method: "GET",
    path: "/cleanups/:id/guests",
    request: GetCleanupGuestsRequestSchema,
    response: GetCleanupGuestsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  cancelCleanup: def({
    method: "POST",
    path: "/cleanups/:id/cancel",
    request: CancelCleanupRequestSchema,
    response: GetCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  completeCleanup: def({
    method: "POST",
    path: "/cleanups/:id/complete",
    request: CompleteCleanupRequestSchema,
    response: GetCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  claimEventSlot: def({
    method: "PUT",
    path: "/cleanups/:id/slot",
    request: ClaimEventSlotRequestSchema,
    response: GetCleanupResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  requestEventResources: def({
    method: "POST",
    path: "/cleanups/:id/request-resources",
    request: RequestEventResourcesRequestSchema,
    response: RequestEventResourcesResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setCleanupMemberRole: def({
    method: "PATCH",
    path: "/cleanups/:id/members/:userId",
    request: SetMemberRoleRequestSchema,
    response: SetMemberRoleResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  removeCleanupMember: def({
    method: "DELETE",
    path: "/cleanups/:id/members/:userId",
    request: RemoveMemberRequestSchema,
    response: RemoveMemberResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listThreads: def({
    method: "GET",
    path: "/threads",
    request: PaginationQuerySchema,
    response: ListThreadsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  markThreadRead: def({
    method: "PUT",
    path: "/threads/read",
    request: MarkThreadReadRequestSchema,
    response: MarkThreadReadResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  openDm: def({
    method: "POST",
    path: "/dm",
    request: OpenDmRequestSchema,
    response: OpenDmResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  dmMessages: def({
    method: "GET",
    path: "/dm/:id/messages",
    request: DmHistoryRequestSchema,
    response: DmHistoryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  editDmMessage: def({
    method: "PATCH",
    path: "/dm/:threadId/messages/:messageId",
    request: EditChatMessageRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  editChatMessage: def({
    method: "PATCH",
    path: "/messages",
    request: EditMessageRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setMessagePinned: def({
    method: "PUT",
    path: "/messages/pin",
    request: SetMessagePinnedRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  toggleMessageReaction: def({
    method: "POST",
    path: "/messages/reactions",
    request: ToggleMessageReactionRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  createPoll: def({
    method: "POST",
    path: "/messages/poll",
    request: CreatePollRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  votePoll: def({
    method: "PUT",
    path: "/messages/poll/vote",
    request: VotePollRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  closePoll: def({
    method: "POST",
    path: "/messages/poll/close",
    request: ClosePollRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  deleteDmMessage: def({
    method: "DELETE",
    path: "/dm/:threadId/messages/:messageId",
    request: DeleteDmMessageRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  deleteCleanupMessage: def({
    method: "DELETE",
    path: "/cleanups/:cleanupId/messages/:messageId",
    request: DeleteCleanupMessageRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  toggleCleanupMessageReaction: def({
    method: "POST",
    path: "/cleanups/:cleanupId/messages/:messageId/reactions",
    request: ToggleCleanupMessageReactionRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  toggleDmMessageReaction: def({
    method: "POST",
    path: "/dm/:threadId/messages/:messageId/reactions",
    request: ToggleDmMessageReactionRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  reportMessages: def({
    method: "GET",
    path: "/reports/:id/messages",
    request: ReportChatHistoryRequestSchema,
    response: ChatHistoryResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  deleteReportMessage: def({
    method: "DELETE",
    path: "/reports/:id/messages/:messageId",
    request: DeleteReportMessageRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  toggleReportMessageReaction: def({
    method: "POST",
    path: "/reports/:id/messages/:messageId/reactions",
    request: ToggleReportMessageReactionRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  joinReportChat: def({
    method: "POST",
    path: "/reports/:id/chat/join",
    request: JoinReportChatRequestSchema,
    response: ReportChatOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getReportChatParticipants: def({
    method: "GET",
    path: "/reports/:id/chat/participants",
    request: null,
    response: ReportChatParticipantsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  leaveReportChat: def({
    method: "POST",
    path: "/reports/:id/chat/leave",
    request: LeaveReportChatRequestSchema,
    response: ReportChatOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  toggleConversationMute: def({
    method: "PUT",
    path: "/conversations/mute",
    request: ToggleMuteRequestSchema,
    response: ToggleMuteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  toggleConversationHidden: def({
    method: "PUT",
    path: "/conversations/hidden",
    request: ToggleHiddenRequestSchema,
    response: ToggleHiddenResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  createChatGroup: def({
    method: "POST",
    path: "/groups",
    request: CreateChatGroupRequestSchema,
    response: ChatGroupDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getChatGroup: def({
    method: "GET",
    path: "/groups/:id",
    request: GetChatGroupRequestSchema,
    response: ChatGroupDTOSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  groupMessages: def({
    method: "GET",
    path: "/groups/:id/messages",
    request: GroupHistoryRequestSchema,
    response: ChatHistoryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  updateChatGroup: def({
    method: "PATCH",
    path: "/groups/:id",
    request: UpdateChatGroupRequestSchema,
    response: ChatGroupDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  addGroupMembers: def({
    method: "POST",
    path: "/groups/:id/members",
    request: AddGroupMembersRequestSchema,
    response: ListGroupMembersResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  removeGroupMember: def({
    method: "DELETE",
    path: "/groups/:id/members/:userId",
    request: RemoveGroupMemberRequestSchema,
    response: z.object({ ok: z.literal(true) }),
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setGroupMemberRole: def({
    method: "PUT",
    path: "/groups/:id/members/:userId/role",
    request: SetGroupMemberRoleRequestSchema,
    response: GroupMemberDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listGroupMembers: def({
    method: "GET",
    path: "/groups/:id/members",
    request: ListGroupMembersRequestSchema,
    response: ListGroupMembersResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  deleteGroupMessage: def({
    method: "DELETE",
    path: "/groups/:id/messages/:messageId",
    request: DeleteGroupMessageRequestSchema,
    response: ChatMessageDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  joinChatGroup: def({
    method: "POST",
    path: "/groups/:id/join",
    request: GetChatGroupRequestSchema,
    response: ChatGroupDTOSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listPeople: def({
    method: "GET",
    path: "/people",
    request: ListPeopleRequestSchema,
    response: ListPeopleResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  searchUsers: def({
    method: "GET",
    path: "/users/search",
    request: SearchUsersRequestSchema,
    response: SearchUsersResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  followSuggestions: def({
    method: "GET",
    path: "/users/follow-suggestions",
    request: FollowSuggestionsRequestSchema,
    response: FollowSuggestionsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  mentionSearch: def({
    method: "GET",
    path: "/users/mention-search",
    request: MentionSearchRequestSchema,
    response: SearchUsersResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  createPost: def({
    method: "POST",
    path: "/posts",
    request: PostComposeInputSchema,
    response: CreatePostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getPost: def({
    method: "GET",
    path: "/posts/:id",
    request: null,
    response: GetPostResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  deletePost: def({
    method: "DELETE",
    path: "/posts/:id",
    request: null,
    response: DeletePostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listReplies: def({
    method: "GET",
    path: "/posts/:id/replies",
    request: PostRepliesQuerySchema,
    response: ListRepliesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  repostPost: def({
    method: "POST",
    path: "/posts/:id/repost",
    request: null,
    response: RepostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unrepostPost: def({
    method: "DELETE",
    path: "/posts/:id/repost",
    request: null,
    response: RepostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  likePost: def({
    method: "POST",
    path: "/posts/:id/like",
    request: null,
    response: LikePostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unlikePost: def({
    method: "DELETE",
    path: "/posts/:id/like",
    request: null,
    response: LikePostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  savePost: def({
    method: "POST",
    path: "/posts/:id/save",
    request: null,
    response: SavePostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unsavePost: def({
    method: "DELETE",
    path: "/posts/:id/save",
    request: null,
    response: SavePostResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  homeFeed: def({
    method: "GET",
    path: "/feed/home",
    request: HomeFeedQuerySchema,
    response: HomeFeedResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  getFeedCounts: def({
    method: "POST",
    path: "/feed/counts",
    request: FeedCountsRequestSchema,
    response: FeedCountsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  listUserPosts: def({
    method: "GET",
    path: "/people/:id/posts",
    request: UserPostsQuerySchema,
    response: ListUserPostsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  listSaves: def({
    method: "GET",
    path: "/me/saves",
    request: PaginationQuerySchema,
    response: ListSavesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  blockUser: def({
    method: "POST",
    path: "/users/:id/block",
    request: null,
    response: BlockUserResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unblockUser: def({
    method: "DELETE",
    path: "/users/:id/block",
    request: null,
    response: BlockUserResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listBlocks: def({
    method: "GET",
    path: "/me/blocks",
    request: PaginationQuerySchema,
    response: ListBlocksResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  followPerson: def({
    method: "POST",
    path: "/people/:id/follow",
    request: null,
    response: FollowPersonResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unfollowPerson: def({
    method: "DELETE",
    path: "/people/:id/follow",
    request: null,
    response: FollowPersonResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getProfile: def({
    method: "GET",
    path: "/people/:id",
    request: null,
    response: GetProfileResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  getProfileEvents: def({
    method: "GET",
    path: "/people/:id/events",
    request: ProfileEventsRequestSchema,
    response: ProfileEventsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  myProfile: def({
    method: "GET",
    path: "/me/profile",
    request: null,
    response: GetProfileResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  updateProfile: def({
    method: "PUT",
    path: "/me/profile",
    request: UpdateProfileRequestSchema,
    response: UpdateProfileResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  checkHandle: def({
    method: "GET",
    path: "/me/handle-available",
    request: HandleAvailableRequestSchema,
    response: HandleAvailableResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  updateSettings: def({
    method: "PUT",
    path: "/me/settings",
    request: UpdateSettingsRequestSchema,
    response: UpdateSettingsResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  deleteAccount: def({
    method: "DELETE",
    path: "/me",
    request: DeleteAccountRequestSchema,
    response: DeleteAccountResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  requestDataExport: def({
    method: "POST",
    path: "/me/data-export",
    request: null,
    response: RequestDataExportResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listFollowers: def({
    method: "GET",
    path: "/people/:id/followers",
    request: ConnectionsListQuerySchema,
    response: ListPeopleResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  listFollowing: def({
    method: "GET",
    path: "/people/:id/following",
    request: ConnectionsListQuerySchema,
    response: ListPeopleResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),

  getMyHours: def({
    method: "GET",
    path: "/me/volunteer-hours",
    request: null,
    response: GetMyHoursResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getMyHoursEntries: def({
    method: "GET",
    path: "/me/volunteer-hours/entries",
    request: MyVolunteerHoursEntriesQuerySchema,
    response: MyVolunteerHoursEntriesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getPublicVolunteerHours: def({
    method: "GET",
    path: "/people/:id/volunteer-hours",
    request: PublicVolunteerHoursQuerySchema,
    response: PublicVolunteerHoursResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),

  logEventHours: def({
    method: "POST",
    path: "/cleanups/:id/hours",
    request: LogEventHoursRequestSchema,
    response: LogEventHoursResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getEventHours: def({
    method: "GET",
    path: "/cleanups/:id/hours",
    request: EventHoursQuerySchema,
    response: EventHoursResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  getJurisdictionLeaderboard: def({
    method: "GET",
    path: "/jurisdictions/:geoid/leaderboard",
    request: LeaderboardQuerySchema,
    response: LeaderboardResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),

  issueServiceHoursCertificate: def({
    method: "POST",
    path: "/me/volunteer-hours/certificates",
    request: IssueServiceHoursCertificateRequestSchema,
    response: IssueServiceHoursCertificateResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listMyServiceHoursCertificates: def({
    method: "GET",
    path: "/me/volunteer-hours/certificates",
    request: null,
    response: ListMyCertificatesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  revokeServiceHoursCertificate: def({
    method: "POST",
    path: "/me/volunteer-hours/certificates/:code/revoke",
    request: RevokeCertificateRequestSchema,
    response: RevokeCertificateResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  verifyServiceHoursCertificate: def({
    method: "GET",
    path: "/service-hours/verify/:code",
    request: VerifyCertificateRequestSchema,
    response: VerifyCertificateResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),

  reportContent: def({
    method: "POST",
    path: "/content-reports",
    request: ReportContentRequestSchema,
    response: ReportContentResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listNotifications: def({
    method: "GET",
    path: "/notifications",
    request: PaginationQuerySchema,
    response: ListNotificationsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  markNotificationsRead: def({
    method: "POST",
    path: "/notifications/read",
    request: MarkReadRequestSchema,
    response: MarkReadResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getNotificationPrefs: def({
    method: "GET",
    path: "/notifications/prefs",
    request: null,
    response: GetNotificationPrefsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  updateNotificationPrefs: def({
    method: "PUT",
    path: "/notifications/prefs",
    request: UpdateNotificationPrefsRequestSchema,
    response: GetNotificationPrefsResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  registerPush: def({
    method: "POST",
    path: "/push/register",
    request: RegisterPushTokenRequestSchema,
    response: RegisterPushTokenResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  pushUnregister: def({
    method: "POST",
    path: "/push/unregister",
    request: UnregisterPushTokenRequestSchema,
    response: RegisterPushTokenResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  createMediaUpload: def({
    method: "POST",
    path: "/media/upload",
    request: CreateMediaUploadRequestSchema,
    response: CreateMediaUploadResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  finalizeMedia: def({
    method: "POST",
    path: "/media/:uploadId/finalize",
    request: FinalizeMediaRequestSchema,
    response: FinalizeMediaResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  getMedia: def({
    method: "GET",
    path: "/media/:id",
    request: null,
    response: GetMediaResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),

  anonCreateReport: def({
    method: "POST",
    path: "/anon/reports",
    request: AnonReportRequestSchema,
    response: AnonReportResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  anonReportStatus: def({
    method: "GET",
    path: "/anon/reports/:id/status",
    request: AnonReportStatusRequestSchema,
    response: AnonReportStatusResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),

  claimNudge: def({
    method: "POST",
    path: "/claim/nudge",
    request: ClaimNudgeRequestSchema,
    response: ClaimNudgeResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  claimReport: def({
    method: "POST",
    path: "/claim/report",
    request: ClaimReportRequestSchema,
    response: ClaimReportResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),


  adminAccessExchange: def({
    method: "POST",
    path: "/admin/auth/access/exchange",
    request: null,
    response: AdminLoginResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  adminSession: def({
    method: "GET",
    path: "/admin/auth/session",
    request: null,
    response: AdminSessionResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminLogout: def({
    method: "POST",
    path: "/admin/auth/logout",
    request: null,
    response: AdminLogoutResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  adminHomeSummary: def({
    method: "GET",
    path: "/admin/home/summary",
    request: null,
    response: HomeSummaryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminHomeMap: def({
    method: "GET",
    path: "/admin/home/map",
    request: null,
    response: HomeMapResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminActivity: def({
    method: "GET",
    path: "/admin/activity",
    request: ActivityListQuerySchema,
    response: ActivityListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminSystemHealth: def({
    method: "GET",
    path: "/admin/system/health",
    request: null,
    response: SystemHealthResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  listDiscovery: def({
    method: "GET",
    path: "/admin/discovery",
    request: DiscoveryListQuerySchema,
    response: DiscoveryListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getDiscoveryTask: def({
    method: "GET",
    path: "/admin/discovery/:id",
    request: null,
    response: GetDiscoveryTaskResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  addDiscoveryNote: def({
    method: "POST",
    path: "/admin/discovery/:id/notes",
    request: AddNoteRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  flagDiscovery: def({
    method: "POST",
    path: "/admin/discovery/:id/flag",
    request: FlagDiscoveryRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  saveDiscoveryDraft: def({
    method: "POST",
    path: "/admin/discovery/:id/draft",
    request: SaveDraftRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  saveJurisdictionContacts: def({
    method: "POST",
    path: "/admin/jurisdictions/:geoid/contacts",
    request: SaveContactsRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listJurisdictions: def({
    method: "GET",
    path: "/admin/jurisdictions",
    request: JurisdictionListQuerySchema,
    response: JurisdictionDirectoryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getJurisdictionGeometry: def({
    method: "GET",
    path: "/admin/jurisdictions/:geoid/geometry",
    request: JurisdictionGeometryRequestSchema,
    response: JurisdictionGeometryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  patchJurisdiction: def({
    method: "PATCH",
    path: "/admin/jurisdictions/:geoid",
    request: PatchJurisdictionRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listAdminReports: def({
    method: "GET",
    path: "/admin/reports",
    request: AdminReportListQuerySchema,
    response: AdminReportListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getAdminReport: def({
    method: "GET",
    path: "/admin/reports/:id",
    request: null,
    response: GetAdminReportResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  setReportStatus: def({
    method: "POST",
    path: "/admin/reports/:id/status",
    request: SetReportStatusRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  flagReport: def({
    method: "POST",
    path: "/admin/reports/:id/flag",
    request: FlagReportRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  removeReport: def({
    method: "POST",
    path: "/admin/reports/:id/remove",
    request: RemoveReportRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  sendReportFollowup: def({
    method: "POST",
    path: "/admin/reports/:id/message",
    request: SendFollowupRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  routeReport: def({
    method: "POST",
    path: "/admin/reports/:id/route",
    request: RouteReportRequestSchema,
    response: RouteReportResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setReportVerdict: def({
    method: "POST",
    path: "/admin/reports/:id/verdict",
    request: SetReportVerdictRequestSchema,
    response: SetReportVerdictResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listAdminEvents: def({
    method: "GET",
    path: "/admin/events",
    request: AdminEventListQuerySchema,
    response: AdminEventListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getAdminEvent: def({
    method: "GET",
    path: "/admin/events/:id",
    request: null,
    response: GetAdminEventResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  setEventStatus: def({
    method: "POST",
    path: "/admin/events/:id/status",
    request: SetEventStatusRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  flagEvent: def({
    method: "POST",
    path: "/admin/events/:id/flag",
    request: FlagEventRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  cancelEvent: def({
    method: "POST",
    path: "/admin/events/:id/cancel",
    request: CancelRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  postEventMessage: def({
    method: "POST",
    path: "/admin/events/:id/message",
    request: PostMessageRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setEventOutcome: def({
    method: "POST",
    path: "/admin/events/:id/outcome",
    request: SetEventOutcomeRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  linkEventReports: def({
    method: "POST",
    path: "/admin/events/:id/link-reports",
    request: LinkEventReportsRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unlinkEventReport: def({
    method: "DELETE",
    path: "/admin/events/:id/reports/:reportId",
    request: null,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listAdminUsers: def({
    method: "GET",
    path: "/admin/users",
    request: AdminUserListQuerySchema,
    response: AdminUserListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getAdminUser: def({
    method: "GET",
    path: "/admin/users/:id",
    request: null,
    response: GetAdminUserResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getUserReports: def({
    method: "GET",
    path: "/admin/users/:id/reports",
    request: UserSubListQuerySchema,
    response: UserReportsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getUserEvents: def({
    method: "GET",
    path: "/admin/users/:id/events",
    request: UserSubListQuerySchema,
    response: UserEventsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getUserMessages: def({
    method: "GET",
    path: "/admin/users/:id/messages",
    request: UserSubListQuerySchema,
    response: UserMessagesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  flagUser: def({
    method: "POST",
    path: "/admin/users/:id/flag",
    request: FlagUserRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setUserStatus: def({
    method: "POST",
    path: "/admin/users/:id/status",
    request: SetUserStatusRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setUserRole: def({
    method: "POST",
    path: "/admin/users/:id/role",
    request: SetRoleRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setUserReportVerified: def({
    method: "POST",
    path: "/admin/users/:id/report-verify",
    request: SetUserReportVerifiedRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  removeUserMessage: def({
    method: "POST",
    path: "/admin/users/:id/messages/:messageId/remove",
    request: RemoveUserMessageRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listGovClaims: def({
    method: "GET",
    path: "/admin/gov-claims",
    request: GovClaimListQuerySchema,
    response: GovClaimListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getGovClaim: def({
    method: "GET",
    path: "/admin/gov-claims/:id",
    request: null,
    response: GetGovClaimResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  verifyGovClaim: def({
    method: "POST",
    path: "/admin/gov-claims/:id/verify",
    request: VerifyCheckRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  approveGovClaim: def({
    method: "POST",
    path: "/admin/gov-claims/:id/approve",
    request: ApproveGovClaimRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  rejectGovClaim: def({
    method: "POST",
    path: "/admin/gov-claims/:id/reject",
    request: RejectGovClaimRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listModeration: def({
    method: "GET",
    path: "/admin/moderation",
    request: ModerationListQuerySchema,
    response: ModerationListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getModerationItem: def({
    method: "GET",
    path: "/admin/moderation/:id",
    request: null,
    response: GetModerationItemResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  approveModeration: def({
    method: "POST",
    path: "/admin/moderation/:id/approve",
    request: ApproveModerationRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  removeModeration: def({
    method: "POST",
    path: "/admin/moderation/:id/remove",
    request: RemoveModerationRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  holdModeration: def({
    method: "POST",
    path: "/admin/moderation/:id/hold",
    request: HoldModerationRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  appealModeration: def({
    method: "POST",
    path: "/admin/moderation/:id/appeal",
    request: AppealModerationRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listMail: def({
    method: "GET",
    path: "/admin/mail",
    request: MailListQuerySchema,
    response: MailListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getMailThread: def({
    method: "GET",
    path: "/admin/mail/:id",
    request: null,
    response: GetMailThreadResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  composeMail: def({
    method: "POST",
    path: "/admin/mail",
    request: ComposeRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  replyMail: def({
    method: "POST",
    path: "/admin/mail/:id/reply",
    request: ReplyRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  markMailRead: def({
    method: "POST",
    path: "/admin/mail/:id/read",
    request: MarkMailReadRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setMailStatus: def({
    method: "POST",
    path: "/admin/mail/:id/status",
    request: SetMailStatusRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  resendMail: def({
    method: "POST",
    path: "/admin/mail/:id/resend",
    request: ResendRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getMailStats: def({
    method: "GET",
    path: "/admin/mail/stats",
    request: null,
    response: MailStatsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getForwardTemplateDefault: def({
    method: "GET",
    path: "/admin/mail/forward-template",
    request: null,
    response: GetForwardTemplateDefaultResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  setForwardTemplateDefault: def({
    method: "PUT",
    path: "/admin/mail/forward-template",
    request: SetForwardTemplateDefaultRequestSchema,
    response: GetForwardTemplateDefaultResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  previewForwardTemplate: def({
    method: "POST",
    path: "/admin/mail/forward-template/preview",
    request: PreviewForwardTemplateRequestSchema,
    response: PreviewForwardTemplateResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listInbox: def({
    method: "GET",
    path: "/admin/inbox",
    request: InboxListQuerySchema,
    response: InboxListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getInboxMessage: def({
    method: "GET",
    path: "/admin/inbox/:id",
    request: null,
    response: GetInboxMessageResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  setInboxStatus: def({
    method: "POST",
    path: "/admin/inbox/:id/status",
    request: SetInboxStatusRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  analyticsKpis: def({
    method: "GET",
    path: "/admin/analytics/kpis",
    request: null,
    response: AnalyticsKpisResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsPinsByWeek: def({
    method: "GET",
    path: "/admin/analytics/pins-by-week",
    request: null,
    response: AnalyticsPinsByWeekResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsByCategory: def({
    method: "GET",
    path: "/admin/analytics/by-category",
    request: null,
    response: AnalyticsByCategoryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsFunnel: def({
    method: "GET",
    path: "/admin/analytics/funnel",
    request: null,
    response: AnalyticsFunnelResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsCoverage: def({
    method: "GET",
    path: "/admin/analytics/coverage",
    request: null,
    response: AnalyticsCoverageResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsResolutionByCategory: def({
    method: "GET",
    path: "/admin/analytics/resolution-by-category",
    request: null,
    response: AnalyticsResolutionByCategoryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsEvents: def({
    method: "GET",
    path: "/admin/analytics/events",
    request: null,
    response: AnalyticsEventsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsTopJurisdictions: def({
    method: "GET",
    path: "/admin/analytics/top-jurisdictions",
    request: null,
    response: AnalyticsTopJurisdictionsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsTopContributors: def({
    method: "GET",
    path: "/admin/analytics/top-contributors",
    request: null,
    response: AnalyticsTopContributorsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsHeatmap: def({
    method: "GET",
    path: "/admin/analytics/heatmap",
    request: null,
    response: AnalyticsHeatmapResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  analyticsRetention: def({
    method: "GET",
    path: "/admin/analytics/retention",
    request: null,
    response: AnalyticsRetentionResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  listAudit: def({
    method: "GET",
    path: "/admin/audit",
    request: AuditListQuerySchema,
    response: AuditListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getLegalVersions: def({
    method: "GET",
    path: "/legal/versions",
    request: null,
    response: GetLegalVersionsResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
} as const

export const hostEndpoints = {
  createOrganization: def({
    method: "POST",
    path: "/orgs",
    request: CreateOrganizationRequestSchema,
    response: CreateOrganizationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listMyOrganizations: def({
    method: "GET",
    path: "/me/organizations",
    request: null,
    response: ListMyOrganizationsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getOrganization: def({
    method: "GET",
    path: "/orgs/by-slug/:slug",
    request: GetOrganizationRequestSchema,
    response: GetOrganizationResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  listOrganizationEvents: def({
    method: "GET",
    path: "/orgs/by-slug/:slug/events",
    request: ListOrganizationEventsRequestSchema,
    response: ListOrganizationEventsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  updateOrganization: def({
    method: "PATCH",
    path: "/orgs/:id",
    request: UpdateOrganizationRequestSchema,
    response: UpdateOrganizationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listOrganizationMembers: def({
    method: "GET",
    path: "/orgs/:id/members",
    request: ListOrganizationMembersRequestSchema,
    response: ListOrganizationMembersResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  inviteOrganizationMember: def({
    method: "POST",
    path: "/orgs/:id/members",
    request: InviteOrganizationMemberRequestSchema,
    response: InviteOrganizationMemberResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setOrganizationMemberRole: def({
    method: "PATCH",
    path: "/orgs/:id/members/:userId",
    request: SetOrganizationMemberRoleRequestSchema,
    response: SetOrganizationMemberRoleResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  removeOrganizationMember: def({
    method: "DELETE",
    path: "/orgs/:id/members/:userId",
    request: RemoveOrganizationMemberRequestSchema,
    response: RemoveOrganizationMemberResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  applyOrganizationVerification: def({
    method: "POST",
    path: "/orgs/:id/verification",
    request: ApplyOrganizationVerificationRequestSchema,
    response: ApplyOrganizationVerificationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getOrganizationVerification: def({
    method: "GET",
    path: "/orgs/:id/verification",
    request: GetOrganizationVerificationRequestSchema,
    response: GetOrganizationVerificationResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  listOrganizationInvites: def({
    method: "GET",
    path: "/orgs/:id/invites",
    request: ListOrganizationInvitesRequestSchema,
    response: ListOrganizationInvitesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  revokeOrganizationInvite: def({
    method: "DELETE",
    path: "/orgs/:id/invites/:inviteId",
    request: RevokeOrganizationInviteRequestSchema,
    response: RevokeOrganizationInviteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  // Not under /orgs/: every /orgs/* route is /orgs/:id or /orgs/by-slug/ (pinned by a test), and
  // the token identifies the org, so the accept lives on its own static prefix.
  acceptOrganizationInvite: def({
    method: "POST",
    path: "/org-invites/accept",
    request: AcceptOrganizationInviteRequestSchema,
    response: AcceptOrganizationInviteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listMyOrgInvites: def({
    method: "GET",
    path: "/me/org-invites",
    request: null,
    response: ListMyOrgInvitesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  acceptMyOrgInvite: def({
    method: "POST",
    path: "/me/org-invites/:inviteId/accept",
    request: AcceptMyOrgInviteRequestSchema,
    response: AcceptMyOrgInviteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  declineMyOrgInvite: def({
    method: "POST",
    path: "/me/org-invites/:inviteId/decline",
    request: DeclineMyOrgInviteRequestSchema,
    response: DeclineMyOrgInviteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listEventTeam: def({
    method: "GET",
    path: "/cleanups/:id/team",
    request: ListEventTeamRequestSchema,
    response: ListEventTeamResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  inviteEventTeamMember: def({
    method: "POST",
    path: "/cleanups/:id/team/invites",
    request: InviteEventTeamMemberRequestSchema,
    response: InviteEventTeamMemberResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  revokeEventTeamInvite: def({
    method: "DELETE",
    path: "/cleanups/:id/team/invites/:inviteId",
    request: RevokeEventTeamInviteRequestSchema,
    response: RevokeEventTeamInviteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  acceptEventTeamInvite: def({
    method: "POST",
    path: "/cleanups/:id/team/invites/accept",
    request: AcceptEventTeamInviteRequestSchema,
    response: AcceptEventTeamInviteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listMyHostedEvents: def({
    method: "GET",
    path: "/me/hosted-events",
    request: ListMyHostedEventsRequestSchema,
    response: ListMyHostedEventsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  listMyEventInvites: def({
    method: "GET",
    path: "/me/event-invites",
    request: ListMyEventInvitesRequestSchema,
    response: ListMyEventInvitesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  acceptMyEventInvite: def({
    method: "POST",
    path: "/me/event-invites/:inviteId/accept",
    request: AcceptMyEventInviteRequestSchema,
    response: AcceptMyEventInviteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  declineMyEventInvite: def({
    method: "POST",
    path: "/me/event-invites/:inviteId/decline",
    request: DeclineMyEventInviteRequestSchema,
    response: DeclineMyEventInviteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listEventTicketTypes: def({
    method: "GET",
    path: "/cleanups/:id/ticket-types",
    request: ListEventTicketTypesRequestSchema,
    response: ListEventTicketTypesResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  createEventTicketType: def({
    method: "POST",
    path: "/cleanups/:id/ticket-types",
    request: CreateEventTicketTypeRequestSchema,
    response: CreateEventTicketTypeResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  reorderEventTicketTypes: def({
    method: "PUT",
    path: "/cleanups/:id/ticket-types/order",
    request: ReorderEventTicketTypesRequestSchema,
    response: ReorderEventTicketTypesResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  updateEventTicketType: def({
    method: "PATCH",
    path: "/cleanups/:id/ticket-types/:ticketTypeId",
    request: UpdateEventTicketTypeRequestSchema,
    response: UpdateEventTicketTypeResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  deleteEventTicketType: def({
    method: "DELETE",
    path: "/cleanups/:id/ticket-types/:ticketTypeId",
    request: DeleteEventTicketTypeRequestSchema,
    response: DeleteEventTicketTypeResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  listEventQuestions: def({
    method: "GET",
    path: "/cleanups/:id/questions",
    request: ListEventQuestionsRequestSchema,
    response: ListEventQuestionsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  saveEventQuestions: def({
    method: "PUT",
    path: "/cleanups/:id/questions",
    request: SaveEventQuestionsRequestSchema,
    response: SaveEventQuestionsResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  registerForEvent: def({
    method: "POST",
    path: "/cleanups/:id/registrations",
    request: RegisterForEventRequestSchema,
    response: RegisterForEventResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listEventRegistrations: def({
    method: "GET",
    path: "/cleanups/:id/registrations",
    request: ListEventRegistrationsRequestSchema,
    response: ListEventRegistrationsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  createWalkupRegistration: def({
    method: "POST",
    path: "/cleanups/:id/registrations/walkup",
    request: CreateWalkupRegistrationRequestSchema,
    response: CreateWalkupRegistrationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getEventRegistration: def({
    method: "GET",
    path: "/cleanups/:id/registrations/:registrationId",
    request: GetEventRegistrationRequestSchema,
    response: GetEventRegistrationResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  removeEventRegistration: def({
    method: "DELETE",
    path: "/cleanups/:id/registrations/:registrationId",
    request: RemoveEventRegistrationRequestSchema,
    response: RemoveEventRegistrationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  cancelEventRegistration: def({
    method: "POST",
    path: "/cleanups/:id/registrations/:registrationId/cancel",
    request: CancelEventRegistrationRequestSchema,
    response: CancelEventRegistrationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  transferEventRegistration: def({
    method: "POST",
    path: "/cleanups/:id/registrations/:registrationId/transfer",
    request: TransferEventRegistrationRequestSchema,
    response: TransferEventRegistrationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setEventRegistrationNote: def({
    method: "PUT",
    path: "/cleanups/:id/registrations/:registrationId/note",
    request: SetEventRegistrationNoteRequestSchema,
    response: SetEventRegistrationNoteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getEventRegistrationAnswers: def({
    method: "GET",
    path: "/cleanups/:id/registrations/:registrationId/answers",
    request: GetEventRegistrationAnswersRequestSchema,
    response: GetEventRegistrationAnswersResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  joinEventWaitlist: def({
    method: "POST",
    path: "/cleanups/:id/waitlist",
    request: JoinEventWaitlistRequestSchema,
    response: JoinEventWaitlistResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  leaveEventWaitlist: def({
    method: "DELETE",
    path: "/cleanups/:id/waitlist",
    request: LeaveEventWaitlistRequestSchema,
    response: LeaveEventWaitlistResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listEventWaitlist: def({
    method: "GET",
    path: "/cleanups/:id/waitlist",
    request: ListEventWaitlistRequestSchema,
    response: ListEventWaitlistResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  claimWaitlistOffer: def({
    method: "POST",
    path: "/cleanups/:id/waitlist/claim",
    request: ClaimWaitlistOfferRequestSchema,
    response: ClaimWaitlistOfferResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  promoteFromWaitlist: def({
    method: "POST",
    path: "/cleanups/:id/waitlist/:waitlistId/promote",
    request: PromoteFromWaitlistRequestSchema,
    response: PromoteFromWaitlistResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  getPublicEventPage: def({
    method: "GET",
    path: "/pages/:slug",
    request: GetPublicEventPageRequestSchema,
    response: GetPublicEventPageResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  recordEventPageView: def({
    method: "POST",
    path: "/pages/:slug/view",
    request: RecordEventPageViewRequestSchema,
    response: RecordEventPageViewResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  getEventPage: def({
    method: "GET",
    path: "/cleanups/:id/page",
    request: GetEventPageRequestSchema,
    response: GetEventPageResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  saveEventPage: def({
    method: "PUT",
    path: "/cleanups/:id/page",
    request: SaveEventPageRequestSchema,
    response: SaveEventPageResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  publishEventPage: def({
    method: "POST",
    path: "/cleanups/:id/page/publish",
    request: PublishEventPageRequestSchema,
    response: PublishEventPageResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  checkEventPageSlug: def({
    method: "GET",
    path: "/cleanups/:id/page/slug-check",
    request: CheckEventPageSlugRequestSchema,
    response: CheckEventPageSlugResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  getEventIcs: def({
    method: "GET",
    path: "/cleanups/:id/ics",
    request: GetEventIcsRequestSchema,
    response: GetEventIcsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  getMyEventTicket: def({
    method: "GET",
    path: "/cleanups/:id/ticket",
    request: GetMyEventTicketRequestSchema,
    response: GetMyEventTicketResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getGuestEventTicket: def({
    method: "POST",
    path: "/guest-rsvp/ticket",
    request: GetGuestEventTicketRequestSchema,
    response: GetGuestEventTicketResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  scanEventTicket: def({
    method: "POST",
    path: "/cleanups/:id/checkins/scan",
    request: ScanEventTicketRequestSchema,
    response: ScanEventTicketResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  checkInEventSeat: def({
    method: "POST",
    path: "/cleanups/:id/checkins",
    request: CheckInEventSeatRequestSchema,
    response: CheckInEventSeatResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  markEventNoShows: def({
    method: "POST",
    path: "/cleanups/:id/checkins/no-show",
    request: MarkEventNoShowsRequestSchema,
    response: MarkEventNoShowsResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  undoEventCheckIn: def({
    method: "DELETE",
    path: "/cleanups/:id/checkins/:seatId",
    request: UndoEventCheckInRequestSchema,
    response: UndoEventCheckInResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getEventCheckinCounters: def({
    method: "GET",
    path: "/cleanups/:id/checkins/counters",
    request: GetEventCheckinCountersRequestSchema,
    response: GetEventCheckinCountersResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  listEventBroadcasts: def({
    method: "GET",
    path: "/cleanups/:id/broadcasts",
    request: ListEventBroadcastsRequestSchema,
    response: ListEventBroadcastsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  createEventBroadcast: def({
    method: "POST",
    path: "/cleanups/:id/broadcasts",
    request: CreateEventBroadcastRequestSchema,
    response: CreateEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getEventBroadcast: def({
    method: "GET",
    path: "/cleanups/:id/broadcasts/:broadcastId",
    request: GetEventBroadcastRequestSchema,
    response: GetEventBroadcastResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  updateEventBroadcast: def({
    method: "PATCH",
    path: "/cleanups/:id/broadcasts/:broadcastId",
    request: UpdateEventBroadcastRequestSchema,
    response: UpdateEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  deleteEventBroadcast: def({
    method: "DELETE",
    path: "/cleanups/:id/broadcasts/:broadcastId",
    request: DeleteEventBroadcastRequestSchema,
    response: DeleteEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  previewEventBroadcast: def({
    method: "POST",
    path: "/cleanups/:id/broadcast-preview",
    request: PreviewEventBroadcastRequestSchema,
    response: PreviewEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  testSendEventBroadcast: def({
    method: "POST",
    path: "/cleanups/:id/broadcasts/:broadcastId/test-send",
    request: TestSendEventBroadcastRequestSchema,
    response: TestSendEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  sendEventBroadcast: def({
    method: "POST",
    path: "/cleanups/:id/broadcasts/:broadcastId/send",
    request: SendEventBroadcastRequestSchema,
    response: SendEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  scheduleEventBroadcast: def({
    method: "POST",
    path: "/cleanups/:id/broadcasts/:broadcastId/schedule",
    request: ScheduleEventBroadcastRequestSchema,
    response: ScheduleEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  cancelEventBroadcast: def({
    method: "POST",
    path: "/cleanups/:id/broadcasts/:broadcastId/cancel",
    request: CancelEventBroadcastRequestSchema,
    response: CancelEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listBroadcastDeliveries: def({
    method: "GET",
    path: "/cleanups/:id/broadcasts/:broadcastId/deliveries",
    request: ListBroadcastDeliveriesRequestSchema,
    response: ListBroadcastDeliveriesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  setEventBroadcastMute: def({
    method: "POST",
    path: "/cleanups/:id/broadcast-mute",
    request: SetEventBroadcastMuteRequestSchema,
    response: SetEventBroadcastMuteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unsubscribeBroadcasts: def({
    method: "POST",
    path: "/broadcasts/unsubscribe",
    request: UnsubscribeBroadcastsRequestSchema,
    response: UnsubscribeBroadcastsResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  openUnsubscribeBroadcasts: def({
    method: "GET",
    path: "/broadcasts/unsubscribe",
    request: OpenUnsubscribeBroadcastsRequestSchema,
    response: OpenUnsubscribeBroadcastsResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),

  createEventAnnouncement: def({
    method: "POST",
    path: "/cleanups/:id/announcements",
    request: CreateEventAnnouncementRequestSchema,
    response: CreateEventAnnouncementResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listEventAnnouncements: def({
    method: "GET",
    path: "/cleanups/:id/announcements",
    request: ListEventAnnouncementsRequestSchema,
    response: ListEventAnnouncementsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  getEventAnnouncement: def({
    method: "GET",
    path: "/cleanups/:id/announcements/:announcementId",
    request: GetEventAnnouncementRequestSchema,
    response: GetEventAnnouncementResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),

  getEventAnalytics: def({
    method: "GET",
    path: "/cleanups/:id/analytics",
    request: GetEventAnalyticsRequestSchema,
    response: GetEventAnalyticsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  eventAnalyticsOverview: def({
    method: "GET",
    path: "/cleanups/:id/analytics/overview",
    request: EventAnalyticsRequestSchema,
    response: EventAnalyticsOverviewResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  eventAnalyticsRegistrations: def({
    method: "GET",
    path: "/cleanups/:id/analytics/registrations",
    request: EventAnalyticsRequestSchema,
    response: EventAnalyticsRegistrationsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  eventAnalyticsCheckins: def({
    method: "GET",
    path: "/cleanups/:id/analytics/checkins",
    request: EventAnalyticsRequestSchema,
    response: EventAnalyticsCheckinsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  eventAnalyticsBroadcasts: def({
    method: "GET",
    path: "/cleanups/:id/analytics/broadcasts",
    request: EventAnalyticsRequestSchema,
    response: EventAnalyticsBroadcastsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  eventAnalyticsSources: def({
    method: "GET",
    path: "/cleanups/:id/analytics/sources",
    request: EventAnalyticsRequestSchema,
    response: EventAnalyticsSourcesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  hostedEventsAnalytics: def({
    method: "GET",
    path: "/me/hosted-events/analytics",
    request: HostedEventsAnalyticsRequestSchema,
    response: HostedEventsAnalyticsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  hostedEventsAnalyticsSummary: def({
    method: "GET",
    path: "/me/hosted-events/analytics/summary",
    request: HostAnalyticsSummaryRequestSchema,
    response: HostAnalyticsSummaryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getEventInsights: def({
    method: "GET",
    path: "/cleanups/:id/insights",
    request: GetEventInsightsRequestSchema,
    response: GetEventInsightsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  requestEventExport: def({
    method: "POST",
    path: "/cleanups/:id/exports",
    request: RequestEventExportRequestSchema,
    response: RequestEventExportResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listEventExports: def({
    method: "GET",
    path: "/cleanups/:id/exports",
    request: ListEventExportsRequestSchema,
    response: ListEventExportsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getEventExport: def({
    method: "GET",
    path: "/cleanups/:id/exports/:exportId",
    request: GetEventExportRequestSchema,
    response: GetEventExportResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  downloadHostExport: def({
    method: "GET",
    path: "/me/host-exports/:id/download",
    request: DownloadHostExportRequestSchema,
    response: DownloadHostExportResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
} as const

export const hostAdminEndpoints = {
  adminListOrgVerifications: def({
    method: "GET",
    path: "/admin/orgs/verifications",
    request: AdminOrgVerificationListQuerySchema,
    response: AdminOrgVerificationListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminGetOrg: def({
    method: "GET",
    path: "/admin/orgs/:id",
    request: GetAdminOrgRequestSchema,
    response: GetAdminOrgResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminDecideOrgVerification: def({
    method: "POST",
    path: "/admin/orgs/:id/verification",
    request: DecideOrgVerificationRequestSchema,
    response: DecideOrgVerificationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminListOrgs: def({
    method: "GET",
    path: "/admin/orgs",
    request: AdminOrgListQuerySchema,
    response: AdminOrgListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminCreateOrg: def({
    method: "POST",
    path: "/admin/orgs",
    request: AdminCreateOrgRequestSchema,
    response: AdminCreateOrgResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminUpdateOrg: def({
    method: "PATCH",
    path: "/admin/orgs/:id",
    request: AdminUpdateOrgRequestSchema,
    response: AdminUpdateOrgResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminSetOrgSuspended: def({
    method: "POST",
    path: "/admin/orgs/:id/suspend",
    request: AdminSetOrgSuspendedRequestSchema,
    response: AdminSetOrgSuspendedResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminListOrgMembers: def({
    method: "GET",
    path: "/admin/orgs/:id/members",
    request: AdminOrgMemberListRequestSchema,
    response: AdminOrgMemberListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminAddOrgMember: def({
    method: "POST",
    path: "/admin/orgs/:id/members",
    request: AdminAddOrgMemberRequestSchema,
    response: AdminAddOrgMemberResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminSetOrgMemberRole: def({
    method: "PATCH",
    path: "/admin/orgs/:id/members/:userId",
    request: AdminSetOrgMemberRoleRequestSchema,
    response: AdminSetOrgMemberRoleResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminRemoveOrgMember: def({
    method: "DELETE",
    path: "/admin/orgs/:id/members/:userId",
    request: AdminRemoveOrgMemberRequestSchema,
    response: AdminRemoveOrgMemberResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminListOrgEvents: def({
    method: "GET",
    path: "/admin/orgs/:id/events",
    request: AdminOrgEventListRequestSchema,
    response: AdminOrgEventListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  adminSetHostMessagingSuspended: def({
    method: "POST",
    path: "/admin/hosts/:id/messaging",
    request: SetHostMessagingSuspendedRequestSchema,
    response: SetHostMessagingSuspendedResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminListBroadcasts: def({
    method: "GET",
    path: "/admin/broadcasts",
    request: AdminBroadcastListQuerySchema,
    response: AdminBroadcastListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  adminListEventPages: def({
    method: "GET",
    path: "/admin/pages",
    request: AdminEventPageListQuerySchema,
    response: AdminEventPageListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminFlagEventPage: def({
    method: "POST",
    path: "/admin/pages/:id/flag",
    request: FlagEventPageRequestSchema,
    response: FlagEventPageResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminUnpublishEventPage: def({
    method: "POST",
    path: "/admin/pages/:id/unpublish",
    request: UnpublishEventPageRequestSchema,
    response: UnpublishEventPageResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),

  adminListHosts: def({
    method: "GET",
    path: "/admin/hosts",
    request: AdminHostListQuerySchema,
    response: AdminHostListResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminGetEventPage: def({
    method: "GET",
    path: "/admin/pages/:id",
    request: AdminGetEventPageRequestSchema,
    response: AdminGetEventPageResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminGetMedia: def({
    method: "GET",
    path: "/admin/media/:id",
    request: AdminGetMediaRequestSchema,
    response: AdminGetMediaResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminGetLegalVersions: def({
    method: "GET",
    path: "/admin/legal/versions",
    request: null,
    response: GetLegalVersionsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
} as const

export const adminReportChatEndpoints = {
  adminReportMessages: def({
    method: "GET",
    path: "/admin/reports/:id/messages",
    request: AdminReportMessagesRequestSchema,
    response: AdminReportMessagesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  adminSendReportMessage: def({
    method: "POST",
    path: "/admin/reports/:id/messages",
    request: AdminSendReportMessageRequestSchema,
    response: AdminSendReportMessageResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  adminRemoveReportMessage: def({
    method: "POST",
    path: "/admin/reports/:id/messages/:messageId/remove",
    request: AdminRemoveReportMessageRequestSchema,
    response: AdminOkResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const

export const endpoints: typeof coreEndpoints &
  typeof hostEndpoints &
  typeof hostAdminEndpoints &
  typeof adminReportChatEndpoints = {
  ...coreEndpoints,
  ...hostEndpoints,
  ...hostAdminEndpoints,
  ...adminReportChatEndpoints,
}

export type Endpoints = typeof endpoints
export type EndpointName = keyof Endpoints

export type RequestOf<N extends EndpointName> = Endpoints[N]["request"] extends z.ZodTypeAny
  ? z.infer<Endpoints[N]["request"]>
  : never

export type ResponseOf<N extends EndpointName> = z.infer<Endpoints[N]["response"]>
