/**
 * AUTO-GENERATED by scripts/gen-i18n-resources.mjs: DO NOT EDIT BY HAND.
 *
 * Re-run `pnpm --filter @civfix/ui i18n:gen` after adding or removing a namespace or locale.
 */
import type { ResourceLanguage } from "i18next"

import de_about from "../locales/de/about.json"
import de_account_blocked from "../locales/de/account-blocked.json"
import de_account_delete from "../locales/de/account-delete.json"
import de_address from "../locales/de/address.json"
import de_appearance_settings from "../locales/de/appearance-settings.json"
import de_channel_create from "../locales/de/channel-create.json"
import de_common from "../locales/de/common.json"
import de_common_datetime from "../locales/de/common-datetime.json"
import de_common_search from "../locales/de/common-search.json"
import de_common_share from "../locales/de/common-share.json"
import de_conversation from "../locales/de/conversation.json"
import de_conversation_mentions from "../locales/de/conversation-mentions.json"
import de_conversation_polls from "../locales/de/conversation-polls.json"
import de_conversation_reactions from "../locales/de/conversation-reactions.json"
import de_discussion from "../locales/de/discussion.json"
import de_discussion_composer from "../locales/de/discussion-composer.json"
import de_discussion_delete from "../locales/de/discussion-delete.json"
import de_donation_link from "../locales/de/donation-link.json"
import de_enums from "../locales/de/enums.json"
import de_event_bring from "../locales/de/event-bring.json"
import de_event_cancel from "../locales/de/event-cancel.json"
import de_event_card from "../locales/de/event-card.json"
import de_event_create from "../locales/de/event-create.json"
import de_event_dashboard from "../locales/de/event-dashboard.json"
import de_event_detail from "../locales/de/event-detail.json"
import de_event_edit from "../locales/de/event-edit.json"
import de_event_form from "../locales/de/event-form.json"
import de_event_guest_rsvp from "../locales/de/event-guest-rsvp.json"
import de_event_list from "../locales/de/event-list.json"
import de_event_members from "../locales/de/event-members.json"
import de_event_resources from "../locales/de/event-resources.json"
import de_event_rsvp from "../locales/de/event-rsvp.json"
import de_event_slots from "../locales/de/event-slots.json"
import de_group_create from "../locales/de/group-create.json"
import de_group_info from "../locales/de/group-info.json"
import de_home_feed from "../locales/de/home-feed.json"
import de_home_sidebar from "../locales/de/home-sidebar.json"
import de_host_analytics from "../locales/de/host-analytics.json"
import de_host_attendees from "../locales/de/host-attendees.json"
import de_host_broadcasts from "../locales/de/host-broadcasts.json"
import de_host_checkin from "../locales/de/host-checkin.json"
import de_host_common from "../locales/de/host-common.json"
import de_host_event from "../locales/de/host-event.json"
import de_host_exports from "../locales/de/host-exports.json"
import de_host_mode from "../locales/de/host-mode.json"
import de_host_org from "../locales/de/host-org.json"
import de_host_page_builder from "../locales/de/host-page-builder.json"
import de_host_portfolio from "../locales/de/host-portfolio.json"
import de_host_settings from "../locales/de/host-settings.json"
import de_host_team from "../locales/de/host-team.json"
import de_host_ticket from "../locales/de/host-ticket.json"
import de_host_tickets from "../locales/de/host-tickets.json"
import de_language_settings from "../locales/de/language-settings.json"
import de_leaderboard from "../locales/de/leaderboard.json"
import de_lightbox from "../locales/de/lightbox.json"
import de_map_address from "../locales/de/map-address.json"
import de_map_ui from "../locales/de/map-ui.json"
import de_messages_list from "../locales/de/messages-list.json"
import de_mobile_a11y from "../locales/de/mobile-a11y.json"
import de_mobile_auth_otp from "../locales/de/mobile-auth-otp.json"
import de_mobile_auth_registration from "../locales/de/mobile-auth-registration.json"
import de_mobile_auth_signin from "../locales/de/mobile-auth-signin.json"
import de_mobile_auth_welcome from "../locales/de/mobile-auth-welcome.json"
import de_mobile_branding from "../locales/de/mobile-branding.json"
import de_mobile_errors from "../locales/de/mobile-errors.json"
import de_mobile_onboarding from "../locales/de/mobile-onboarding.json"
import de_mobile_report_camera from "../locales/de/mobile-report-camera.json"
import de_mobile_system from "../locales/de/mobile-system.json"
import de_nav from "../locales/de/nav.json"
import de_notifications from "../locales/de/notifications.json"
import de_notifications_prefs from "../locales/de/notifications-prefs.json"
import de_onboarding_age from "../locales/de/onboarding-age.json"
import de_onboarding_terms from "../locales/de/onboarding-terms.json"
import de_post_composer from "../locales/de/post-composer.json"
import de_profile from "../locales/de/profile.json"
import de_profile_connections from "../locales/de/profile-connections.json"
import de_profile_follow from "../locales/de/profile-follow.json"
import de_profile_person from "../locales/de/profile-person.json"
import de_profile_view from "../locales/de/profile-view.json"
import de_report_cluster from "../locales/de/report-cluster.json"
import de_report_content from "../locales/de/report-content.json"
import de_report_detail from "../locales/de/report-detail.json"
import de_report_linked from "../locales/de/report-linked.json"
import de_report_list from "../locales/de/report-list.json"
import de_report_picker from "../locales/de/report-picker.json"
import de_report_row from "../locales/de/report-row.json"
import de_report_wizard from "../locales/de/report-wizard.json"
import de_search from "../locales/de/search.json"
import de_settings from "../locales/de/settings.json"
import de_settings_account from "../locales/de/settings-account.json"
import de_settings_privacy from "../locales/de/settings-privacy.json"
import de_share_post from "../locales/de/share-post.json"
import de_volunteer_hours from "../locales/de/volunteer-hours.json"
import de_web_auth from "../locales/de/web-auth.json"
import de_web_claims from "../locales/de/web-claims.json"
import de_web_common from "../locales/de/web-common.json"
import de_web_guest_cancel from "../locales/de/web-guest-cancel.json"
import de_web_registration from "../locales/de/web-registration.json"
import de_web_service_record from "../locales/de/web-service-record.json"
import de_web_signup from "../locales/de/web-signup.json"
import de_web_unsubscribe from "../locales/de/web-unsubscribe.json"

const catalog: ResourceLanguage = {
  "about": de_about,
  "account-blocked": de_account_blocked,
  "account-delete": de_account_delete,
  "address": de_address,
  "appearance-settings": de_appearance_settings,
  "channel-create": de_channel_create,
  "common": de_common,
  "common-datetime": de_common_datetime,
  "common-search": de_common_search,
  "common-share": de_common_share,
  "conversation": de_conversation,
  "conversation-mentions": de_conversation_mentions,
  "conversation-polls": de_conversation_polls,
  "conversation-reactions": de_conversation_reactions,
  "discussion": de_discussion,
  "discussion-composer": de_discussion_composer,
  "discussion-delete": de_discussion_delete,
  "donation-link": de_donation_link,
  "enums": de_enums,
  "event-bring": de_event_bring,
  "event-cancel": de_event_cancel,
  "event-card": de_event_card,
  "event-create": de_event_create,
  "event-dashboard": de_event_dashboard,
  "event-detail": de_event_detail,
  "event-edit": de_event_edit,
  "event-form": de_event_form,
  "event-guest-rsvp": de_event_guest_rsvp,
  "event-list": de_event_list,
  "event-members": de_event_members,
  "event-resources": de_event_resources,
  "event-rsvp": de_event_rsvp,
  "event-slots": de_event_slots,
  "group-create": de_group_create,
  "group-info": de_group_info,
  "home-feed": de_home_feed,
  "home-sidebar": de_home_sidebar,
  "host-analytics": de_host_analytics,
  "host-attendees": de_host_attendees,
  "host-broadcasts": de_host_broadcasts,
  "host-checkin": de_host_checkin,
  "host-common": de_host_common,
  "host-event": de_host_event,
  "host-exports": de_host_exports,
  "host-mode": de_host_mode,
  "host-org": de_host_org,
  "host-page-builder": de_host_page_builder,
  "host-portfolio": de_host_portfolio,
  "host-settings": de_host_settings,
  "host-team": de_host_team,
  "host-ticket": de_host_ticket,
  "host-tickets": de_host_tickets,
  "language-settings": de_language_settings,
  "leaderboard": de_leaderboard,
  "lightbox": de_lightbox,
  "map-address": de_map_address,
  "map-ui": de_map_ui,
  "messages-list": de_messages_list,
  "mobile-a11y": de_mobile_a11y,
  "mobile-auth-otp": de_mobile_auth_otp,
  "mobile-auth-registration": de_mobile_auth_registration,
  "mobile-auth-signin": de_mobile_auth_signin,
  "mobile-auth-welcome": de_mobile_auth_welcome,
  "mobile-branding": de_mobile_branding,
  "mobile-errors": de_mobile_errors,
  "mobile-onboarding": de_mobile_onboarding,
  "mobile-report-camera": de_mobile_report_camera,
  "mobile-system": de_mobile_system,
  "nav": de_nav,
  "notifications": de_notifications,
  "notifications-prefs": de_notifications_prefs,
  "onboarding-age": de_onboarding_age,
  "onboarding-terms": de_onboarding_terms,
  "post-composer": de_post_composer,
  "profile": de_profile,
  "profile-connections": de_profile_connections,
  "profile-follow": de_profile_follow,
  "profile-person": de_profile_person,
  "profile-view": de_profile_view,
  "report-cluster": de_report_cluster,
  "report-content": de_report_content,
  "report-detail": de_report_detail,
  "report-linked": de_report_linked,
  "report-list": de_report_list,
  "report-picker": de_report_picker,
  "report-row": de_report_row,
  "report-wizard": de_report_wizard,
  "search": de_search,
  "settings": de_settings,
  "settings-account": de_settings_account,
  "settings-privacy": de_settings_privacy,
  "share-post": de_share_post,
  "volunteer-hours": de_volunteer_hours,
  "web-auth": de_web_auth,
  "web-claims": de_web_claims,
  "web-common": de_web_common,
  "web-guest-cancel": de_web_guest_cancel,
  "web-registration": de_web_registration,
  "web-service-record": de_web_service_record,
  "web-signup": de_web_signup,
  "web-unsubscribe": de_web_unsubscribe,
}

export default catalog
