/**
 * AUTO-GENERATED by scripts/gen-i18n-resources.mjs: DO NOT EDIT BY HAND.
 *
 * Re-run `pnpm --filter @civfix/ui i18n:gen` after adding or removing a namespace or locale.
 */
import type { ResourceLanguage } from "i18next"

import en_about from "../locales/en/about.json"
import en_account_blocked from "../locales/en/account-blocked.json"
import en_account_delete from "../locales/en/account-delete.json"
import en_address from "../locales/en/address.json"
import en_appearance_settings from "../locales/en/appearance-settings.json"
import en_channel_create from "../locales/en/channel-create.json"
import en_common from "../locales/en/common.json"
import en_common_datetime from "../locales/en/common-datetime.json"
import en_common_search from "../locales/en/common-search.json"
import en_common_share from "../locales/en/common-share.json"
import en_conversation from "../locales/en/conversation.json"
import en_conversation_mentions from "../locales/en/conversation-mentions.json"
import en_conversation_polls from "../locales/en/conversation-polls.json"
import en_conversation_reactions from "../locales/en/conversation-reactions.json"
import en_discussion from "../locales/en/discussion.json"
import en_discussion_composer from "../locales/en/discussion-composer.json"
import en_discussion_delete from "../locales/en/discussion-delete.json"
import en_donation_link from "../locales/en/donation-link.json"
import en_enums from "../locales/en/enums.json"
import en_event_bring from "../locales/en/event-bring.json"
import en_event_cancel from "../locales/en/event-cancel.json"
import en_event_card from "../locales/en/event-card.json"
import en_event_create from "../locales/en/event-create.json"
import en_event_dashboard from "../locales/en/event-dashboard.json"
import en_event_detail from "../locales/en/event-detail.json"
import en_event_edit from "../locales/en/event-edit.json"
import en_event_form from "../locales/en/event-form.json"
import en_event_guest_rsvp from "../locales/en/event-guest-rsvp.json"
import en_event_list from "../locales/en/event-list.json"
import en_event_members from "../locales/en/event-members.json"
import en_event_resources from "../locales/en/event-resources.json"
import en_event_rsvp from "../locales/en/event-rsvp.json"
import en_event_slots from "../locales/en/event-slots.json"
import en_group_create from "../locales/en/group-create.json"
import en_group_info from "../locales/en/group-info.json"
import en_home_feed from "../locales/en/home-feed.json"
import en_home_sidebar from "../locales/en/home-sidebar.json"
import en_host_analytics from "../locales/en/host-analytics.json"
import en_host_attendees from "../locales/en/host-attendees.json"
import en_host_broadcasts from "../locales/en/host-broadcasts.json"
import en_host_checkin from "../locales/en/host-checkin.json"
import en_host_common from "../locales/en/host-common.json"
import en_host_event from "../locales/en/host-event.json"
import en_host_exports from "../locales/en/host-exports.json"
import en_host_mode from "../locales/en/host-mode.json"
import en_host_org from "../locales/en/host-org.json"
import en_host_page_builder from "../locales/en/host-page-builder.json"
import en_host_portfolio from "../locales/en/host-portfolio.json"
import en_host_settings from "../locales/en/host-settings.json"
import en_host_team from "../locales/en/host-team.json"
import en_host_ticket from "../locales/en/host-ticket.json"
import en_host_tickets from "../locales/en/host-tickets.json"
import en_language_settings from "../locales/en/language-settings.json"
import en_leaderboard from "../locales/en/leaderboard.json"
import en_lightbox from "../locales/en/lightbox.json"
import en_map_address from "../locales/en/map-address.json"
import en_map_ui from "../locales/en/map-ui.json"
import en_messages_list from "../locales/en/messages-list.json"
import en_mobile_a11y from "../locales/en/mobile-a11y.json"
import en_mobile_auth_otp from "../locales/en/mobile-auth-otp.json"
import en_mobile_auth_registration from "../locales/en/mobile-auth-registration.json"
import en_mobile_auth_signin from "../locales/en/mobile-auth-signin.json"
import en_mobile_auth_welcome from "../locales/en/mobile-auth-welcome.json"
import en_mobile_branding from "../locales/en/mobile-branding.json"
import en_mobile_errors from "../locales/en/mobile-errors.json"
import en_mobile_onboarding from "../locales/en/mobile-onboarding.json"
import en_mobile_report_camera from "../locales/en/mobile-report-camera.json"
import en_mobile_system from "../locales/en/mobile-system.json"
import en_nav from "../locales/en/nav.json"
import en_notifications from "../locales/en/notifications.json"
import en_notifications_prefs from "../locales/en/notifications-prefs.json"
import en_onboarding_age from "../locales/en/onboarding-age.json"
import en_onboarding_terms from "../locales/en/onboarding-terms.json"
import en_post_composer from "../locales/en/post-composer.json"
import en_profile from "../locales/en/profile.json"
import en_profile_connections from "../locales/en/profile-connections.json"
import en_profile_follow from "../locales/en/profile-follow.json"
import en_profile_person from "../locales/en/profile-person.json"
import en_profile_view from "../locales/en/profile-view.json"
import en_report_cluster from "../locales/en/report-cluster.json"
import en_report_content from "../locales/en/report-content.json"
import en_report_detail from "../locales/en/report-detail.json"
import en_report_linked from "../locales/en/report-linked.json"
import en_report_list from "../locales/en/report-list.json"
import en_report_picker from "../locales/en/report-picker.json"
import en_report_row from "../locales/en/report-row.json"
import en_report_wizard from "../locales/en/report-wizard.json"
import en_search from "../locales/en/search.json"
import en_settings from "../locales/en/settings.json"
import en_settings_account from "../locales/en/settings-account.json"
import en_settings_privacy from "../locales/en/settings-privacy.json"
import en_share_post from "../locales/en/share-post.json"
import en_volunteer_hours from "../locales/en/volunteer-hours.json"
import en_web_auth from "../locales/en/web-auth.json"
import en_web_claims from "../locales/en/web-claims.json"
import en_web_common from "../locales/en/web-common.json"
import en_web_guest_cancel from "../locales/en/web-guest-cancel.json"
import en_web_registration from "../locales/en/web-registration.json"
import en_web_service_record from "../locales/en/web-service-record.json"
import en_web_signup from "../locales/en/web-signup.json"
import en_web_unsubscribe from "../locales/en/web-unsubscribe.json"

const catalog: ResourceLanguage = {
  "about": en_about,
  "account-blocked": en_account_blocked,
  "account-delete": en_account_delete,
  "address": en_address,
  "appearance-settings": en_appearance_settings,
  "channel-create": en_channel_create,
  "common": en_common,
  "common-datetime": en_common_datetime,
  "common-search": en_common_search,
  "common-share": en_common_share,
  "conversation": en_conversation,
  "conversation-mentions": en_conversation_mentions,
  "conversation-polls": en_conversation_polls,
  "conversation-reactions": en_conversation_reactions,
  "discussion": en_discussion,
  "discussion-composer": en_discussion_composer,
  "discussion-delete": en_discussion_delete,
  "donation-link": en_donation_link,
  "enums": en_enums,
  "event-bring": en_event_bring,
  "event-cancel": en_event_cancel,
  "event-card": en_event_card,
  "event-create": en_event_create,
  "event-dashboard": en_event_dashboard,
  "event-detail": en_event_detail,
  "event-edit": en_event_edit,
  "event-form": en_event_form,
  "event-guest-rsvp": en_event_guest_rsvp,
  "event-list": en_event_list,
  "event-members": en_event_members,
  "event-resources": en_event_resources,
  "event-rsvp": en_event_rsvp,
  "event-slots": en_event_slots,
  "group-create": en_group_create,
  "group-info": en_group_info,
  "home-feed": en_home_feed,
  "home-sidebar": en_home_sidebar,
  "host-analytics": en_host_analytics,
  "host-attendees": en_host_attendees,
  "host-broadcasts": en_host_broadcasts,
  "host-checkin": en_host_checkin,
  "host-common": en_host_common,
  "host-event": en_host_event,
  "host-exports": en_host_exports,
  "host-mode": en_host_mode,
  "host-org": en_host_org,
  "host-page-builder": en_host_page_builder,
  "host-portfolio": en_host_portfolio,
  "host-settings": en_host_settings,
  "host-team": en_host_team,
  "host-ticket": en_host_ticket,
  "host-tickets": en_host_tickets,
  "language-settings": en_language_settings,
  "leaderboard": en_leaderboard,
  "lightbox": en_lightbox,
  "map-address": en_map_address,
  "map-ui": en_map_ui,
  "messages-list": en_messages_list,
  "mobile-a11y": en_mobile_a11y,
  "mobile-auth-otp": en_mobile_auth_otp,
  "mobile-auth-registration": en_mobile_auth_registration,
  "mobile-auth-signin": en_mobile_auth_signin,
  "mobile-auth-welcome": en_mobile_auth_welcome,
  "mobile-branding": en_mobile_branding,
  "mobile-errors": en_mobile_errors,
  "mobile-onboarding": en_mobile_onboarding,
  "mobile-report-camera": en_mobile_report_camera,
  "mobile-system": en_mobile_system,
  "nav": en_nav,
  "notifications": en_notifications,
  "notifications-prefs": en_notifications_prefs,
  "onboarding-age": en_onboarding_age,
  "onboarding-terms": en_onboarding_terms,
  "post-composer": en_post_composer,
  "profile": en_profile,
  "profile-connections": en_profile_connections,
  "profile-follow": en_profile_follow,
  "profile-person": en_profile_person,
  "profile-view": en_profile_view,
  "report-cluster": en_report_cluster,
  "report-content": en_report_content,
  "report-detail": en_report_detail,
  "report-linked": en_report_linked,
  "report-list": en_report_list,
  "report-picker": en_report_picker,
  "report-row": en_report_row,
  "report-wizard": en_report_wizard,
  "search": en_search,
  "settings": en_settings,
  "settings-account": en_settings_account,
  "settings-privacy": en_settings_privacy,
  "share-post": en_share_post,
  "volunteer-hours": en_volunteer_hours,
  "web-auth": en_web_auth,
  "web-claims": en_web_claims,
  "web-common": en_web_common,
  "web-guest-cancel": en_web_guest_cancel,
  "web-registration": en_web_registration,
  "web-service-record": en_web_service_record,
  "web-signup": en_web_signup,
  "web-unsubscribe": en_web_unsubscribe,
}

export default catalog
