/**
 * AUTO-GENERATED by scripts/gen-i18n-resources.mjs: DO NOT EDIT BY HAND.
 *
 * Re-run `pnpm --filter @civfix/ui i18n:gen` after adding or removing a namespace or locale.
 */
import type { ResourceLanguage } from "i18next"

import es_about from "../locales/es/about.json"
import es_account_blocked from "../locales/es/account-blocked.json"
import es_account_delete from "../locales/es/account-delete.json"
import es_address from "../locales/es/address.json"
import es_appearance_settings from "../locales/es/appearance-settings.json"
import es_channel_create from "../locales/es/channel-create.json"
import es_common from "../locales/es/common.json"
import es_common_datetime from "../locales/es/common-datetime.json"
import es_common_search from "../locales/es/common-search.json"
import es_common_share from "../locales/es/common-share.json"
import es_conversation from "../locales/es/conversation.json"
import es_conversation_mentions from "../locales/es/conversation-mentions.json"
import es_conversation_polls from "../locales/es/conversation-polls.json"
import es_conversation_reactions from "../locales/es/conversation-reactions.json"
import es_discussion from "../locales/es/discussion.json"
import es_discussion_composer from "../locales/es/discussion-composer.json"
import es_discussion_delete from "../locales/es/discussion-delete.json"
import es_donation_link from "../locales/es/donation-link.json"
import es_enums from "../locales/es/enums.json"
import es_event_bring from "../locales/es/event-bring.json"
import es_event_cancel from "../locales/es/event-cancel.json"
import es_event_card from "../locales/es/event-card.json"
import es_event_create from "../locales/es/event-create.json"
import es_event_dashboard from "../locales/es/event-dashboard.json"
import es_event_detail from "../locales/es/event-detail.json"
import es_event_edit from "../locales/es/event-edit.json"
import es_event_form from "../locales/es/event-form.json"
import es_event_guest_rsvp from "../locales/es/event-guest-rsvp.json"
import es_event_list from "../locales/es/event-list.json"
import es_event_members from "../locales/es/event-members.json"
import es_event_resources from "../locales/es/event-resources.json"
import es_event_rsvp from "../locales/es/event-rsvp.json"
import es_event_slots from "../locales/es/event-slots.json"
import es_group_create from "../locales/es/group-create.json"
import es_group_info from "../locales/es/group-info.json"
import es_home_feed from "../locales/es/home-feed.json"
import es_home_sidebar from "../locales/es/home-sidebar.json"
import es_host_analytics from "../locales/es/host-analytics.json"
import es_host_attendees from "../locales/es/host-attendees.json"
import es_host_broadcasts from "../locales/es/host-broadcasts.json"
import es_host_checkin from "../locales/es/host-checkin.json"
import es_host_common from "../locales/es/host-common.json"
import es_host_event from "../locales/es/host-event.json"
import es_host_exports from "../locales/es/host-exports.json"
import es_host_mode from "../locales/es/host-mode.json"
import es_host_org from "../locales/es/host-org.json"
import es_host_page_builder from "../locales/es/host-page-builder.json"
import es_host_portfolio from "../locales/es/host-portfolio.json"
import es_host_settings from "../locales/es/host-settings.json"
import es_host_team from "../locales/es/host-team.json"
import es_host_ticket from "../locales/es/host-ticket.json"
import es_host_tickets from "../locales/es/host-tickets.json"
import es_language_settings from "../locales/es/language-settings.json"
import es_leaderboard from "../locales/es/leaderboard.json"
import es_lightbox from "../locales/es/lightbox.json"
import es_map_address from "../locales/es/map-address.json"
import es_map_ui from "../locales/es/map-ui.json"
import es_messages_list from "../locales/es/messages-list.json"
import es_mobile_a11y from "../locales/es/mobile-a11y.json"
import es_mobile_auth_otp from "../locales/es/mobile-auth-otp.json"
import es_mobile_auth_registration from "../locales/es/mobile-auth-registration.json"
import es_mobile_auth_signin from "../locales/es/mobile-auth-signin.json"
import es_mobile_auth_welcome from "../locales/es/mobile-auth-welcome.json"
import es_mobile_branding from "../locales/es/mobile-branding.json"
import es_mobile_errors from "../locales/es/mobile-errors.json"
import es_mobile_onboarding from "../locales/es/mobile-onboarding.json"
import es_mobile_report_camera from "../locales/es/mobile-report-camera.json"
import es_mobile_system from "../locales/es/mobile-system.json"
import es_nav from "../locales/es/nav.json"
import es_notifications from "../locales/es/notifications.json"
import es_notifications_prefs from "../locales/es/notifications-prefs.json"
import es_onboarding_age from "../locales/es/onboarding-age.json"
import es_onboarding_terms from "../locales/es/onboarding-terms.json"
import es_post_composer from "../locales/es/post-composer.json"
import es_profile from "../locales/es/profile.json"
import es_profile_connections from "../locales/es/profile-connections.json"
import es_profile_follow from "../locales/es/profile-follow.json"
import es_profile_person from "../locales/es/profile-person.json"
import es_profile_view from "../locales/es/profile-view.json"
import es_report_cluster from "../locales/es/report-cluster.json"
import es_report_content from "../locales/es/report-content.json"
import es_report_detail from "../locales/es/report-detail.json"
import es_report_linked from "../locales/es/report-linked.json"
import es_report_list from "../locales/es/report-list.json"
import es_report_picker from "../locales/es/report-picker.json"
import es_report_row from "../locales/es/report-row.json"
import es_report_wizard from "../locales/es/report-wizard.json"
import es_search from "../locales/es/search.json"
import es_settings from "../locales/es/settings.json"
import es_settings_account from "../locales/es/settings-account.json"
import es_settings_privacy from "../locales/es/settings-privacy.json"
import es_share_post from "../locales/es/share-post.json"
import es_volunteer_hours from "../locales/es/volunteer-hours.json"
import es_web_auth from "../locales/es/web-auth.json"
import es_web_claims from "../locales/es/web-claims.json"
import es_web_common from "../locales/es/web-common.json"
import es_web_guest_cancel from "../locales/es/web-guest-cancel.json"
import es_web_registration from "../locales/es/web-registration.json"
import es_web_service_record from "../locales/es/web-service-record.json"
import es_web_signup from "../locales/es/web-signup.json"
import es_web_unsubscribe from "../locales/es/web-unsubscribe.json"

const catalog: ResourceLanguage = {
  "about": es_about,
  "account-blocked": es_account_blocked,
  "account-delete": es_account_delete,
  "address": es_address,
  "appearance-settings": es_appearance_settings,
  "channel-create": es_channel_create,
  "common": es_common,
  "common-datetime": es_common_datetime,
  "common-search": es_common_search,
  "common-share": es_common_share,
  "conversation": es_conversation,
  "conversation-mentions": es_conversation_mentions,
  "conversation-polls": es_conversation_polls,
  "conversation-reactions": es_conversation_reactions,
  "discussion": es_discussion,
  "discussion-composer": es_discussion_composer,
  "discussion-delete": es_discussion_delete,
  "donation-link": es_donation_link,
  "enums": es_enums,
  "event-bring": es_event_bring,
  "event-cancel": es_event_cancel,
  "event-card": es_event_card,
  "event-create": es_event_create,
  "event-dashboard": es_event_dashboard,
  "event-detail": es_event_detail,
  "event-edit": es_event_edit,
  "event-form": es_event_form,
  "event-guest-rsvp": es_event_guest_rsvp,
  "event-list": es_event_list,
  "event-members": es_event_members,
  "event-resources": es_event_resources,
  "event-rsvp": es_event_rsvp,
  "event-slots": es_event_slots,
  "group-create": es_group_create,
  "group-info": es_group_info,
  "home-feed": es_home_feed,
  "home-sidebar": es_home_sidebar,
  "host-analytics": es_host_analytics,
  "host-attendees": es_host_attendees,
  "host-broadcasts": es_host_broadcasts,
  "host-checkin": es_host_checkin,
  "host-common": es_host_common,
  "host-event": es_host_event,
  "host-exports": es_host_exports,
  "host-mode": es_host_mode,
  "host-org": es_host_org,
  "host-page-builder": es_host_page_builder,
  "host-portfolio": es_host_portfolio,
  "host-settings": es_host_settings,
  "host-team": es_host_team,
  "host-ticket": es_host_ticket,
  "host-tickets": es_host_tickets,
  "language-settings": es_language_settings,
  "leaderboard": es_leaderboard,
  "lightbox": es_lightbox,
  "map-address": es_map_address,
  "map-ui": es_map_ui,
  "messages-list": es_messages_list,
  "mobile-a11y": es_mobile_a11y,
  "mobile-auth-otp": es_mobile_auth_otp,
  "mobile-auth-registration": es_mobile_auth_registration,
  "mobile-auth-signin": es_mobile_auth_signin,
  "mobile-auth-welcome": es_mobile_auth_welcome,
  "mobile-branding": es_mobile_branding,
  "mobile-errors": es_mobile_errors,
  "mobile-onboarding": es_mobile_onboarding,
  "mobile-report-camera": es_mobile_report_camera,
  "mobile-system": es_mobile_system,
  "nav": es_nav,
  "notifications": es_notifications,
  "notifications-prefs": es_notifications_prefs,
  "onboarding-age": es_onboarding_age,
  "onboarding-terms": es_onboarding_terms,
  "post-composer": es_post_composer,
  "profile": es_profile,
  "profile-connections": es_profile_connections,
  "profile-follow": es_profile_follow,
  "profile-person": es_profile_person,
  "profile-view": es_profile_view,
  "report-cluster": es_report_cluster,
  "report-content": es_report_content,
  "report-detail": es_report_detail,
  "report-linked": es_report_linked,
  "report-list": es_report_list,
  "report-picker": es_report_picker,
  "report-row": es_report_row,
  "report-wizard": es_report_wizard,
  "search": es_search,
  "settings": es_settings,
  "settings-account": es_settings_account,
  "settings-privacy": es_settings_privacy,
  "share-post": es_share_post,
  "volunteer-hours": es_volunteer_hours,
  "web-auth": es_web_auth,
  "web-claims": es_web_claims,
  "web-common": es_web_common,
  "web-guest-cancel": es_web_guest_cancel,
  "web-registration": es_web_registration,
  "web-service-record": es_web_service_record,
  "web-signup": es_web_signup,
  "web-unsubscribe": es_web_unsubscribe,
}

export default catalog
