/**
 * AUTO-GENERATED by scripts/gen-i18n-resources.mjs: DO NOT EDIT BY HAND.
 *
 * Re-run `pnpm --filter @civfix/ui i18n:gen` after adding or removing a namespace or locale.
 */
import type { ResourceLanguage } from "i18next"

import ko_about from "../locales/ko/about.json"
import ko_account_blocked from "../locales/ko/account-blocked.json"
import ko_account_delete from "../locales/ko/account-delete.json"
import ko_address from "../locales/ko/address.json"
import ko_appearance_settings from "../locales/ko/appearance-settings.json"
import ko_channel_create from "../locales/ko/channel-create.json"
import ko_common from "../locales/ko/common.json"
import ko_common_datetime from "../locales/ko/common-datetime.json"
import ko_common_search from "../locales/ko/common-search.json"
import ko_common_share from "../locales/ko/common-share.json"
import ko_conversation from "../locales/ko/conversation.json"
import ko_conversation_mentions from "../locales/ko/conversation-mentions.json"
import ko_conversation_polls from "../locales/ko/conversation-polls.json"
import ko_conversation_reactions from "../locales/ko/conversation-reactions.json"
import ko_discussion from "../locales/ko/discussion.json"
import ko_discussion_composer from "../locales/ko/discussion-composer.json"
import ko_discussion_delete from "../locales/ko/discussion-delete.json"
import ko_donation_link from "../locales/ko/donation-link.json"
import ko_enums from "../locales/ko/enums.json"
import ko_event_bring from "../locales/ko/event-bring.json"
import ko_event_cancel from "../locales/ko/event-cancel.json"
import ko_event_card from "../locales/ko/event-card.json"
import ko_event_create from "../locales/ko/event-create.json"
import ko_event_dashboard from "../locales/ko/event-dashboard.json"
import ko_event_detail from "../locales/ko/event-detail.json"
import ko_event_edit from "../locales/ko/event-edit.json"
import ko_event_form from "../locales/ko/event-form.json"
import ko_event_guest_rsvp from "../locales/ko/event-guest-rsvp.json"
import ko_event_list from "../locales/ko/event-list.json"
import ko_event_members from "../locales/ko/event-members.json"
import ko_event_resources from "../locales/ko/event-resources.json"
import ko_event_rsvp from "../locales/ko/event-rsvp.json"
import ko_event_slots from "../locales/ko/event-slots.json"
import ko_group_create from "../locales/ko/group-create.json"
import ko_group_info from "../locales/ko/group-info.json"
import ko_home_feed from "../locales/ko/home-feed.json"
import ko_home_sidebar from "../locales/ko/home-sidebar.json"
import ko_host_analytics from "../locales/ko/host-analytics.json"
import ko_host_attendees from "../locales/ko/host-attendees.json"
import ko_host_broadcasts from "../locales/ko/host-broadcasts.json"
import ko_host_checkin from "../locales/ko/host-checkin.json"
import ko_host_common from "../locales/ko/host-common.json"
import ko_host_event from "../locales/ko/host-event.json"
import ko_host_exports from "../locales/ko/host-exports.json"
import ko_host_mode from "../locales/ko/host-mode.json"
import ko_host_org from "../locales/ko/host-org.json"
import ko_host_page_builder from "../locales/ko/host-page-builder.json"
import ko_host_portfolio from "../locales/ko/host-portfolio.json"
import ko_host_settings from "../locales/ko/host-settings.json"
import ko_host_team from "../locales/ko/host-team.json"
import ko_host_ticket from "../locales/ko/host-ticket.json"
import ko_host_tickets from "../locales/ko/host-tickets.json"
import ko_language_settings from "../locales/ko/language-settings.json"
import ko_leaderboard from "../locales/ko/leaderboard.json"
import ko_lightbox from "../locales/ko/lightbox.json"
import ko_map_address from "../locales/ko/map-address.json"
import ko_map_ui from "../locales/ko/map-ui.json"
import ko_messages_list from "../locales/ko/messages-list.json"
import ko_mobile_a11y from "../locales/ko/mobile-a11y.json"
import ko_mobile_auth_otp from "../locales/ko/mobile-auth-otp.json"
import ko_mobile_auth_registration from "../locales/ko/mobile-auth-registration.json"
import ko_mobile_auth_signin from "../locales/ko/mobile-auth-signin.json"
import ko_mobile_auth_welcome from "../locales/ko/mobile-auth-welcome.json"
import ko_mobile_branding from "../locales/ko/mobile-branding.json"
import ko_mobile_errors from "../locales/ko/mobile-errors.json"
import ko_mobile_onboarding from "../locales/ko/mobile-onboarding.json"
import ko_mobile_report_camera from "../locales/ko/mobile-report-camera.json"
import ko_mobile_system from "../locales/ko/mobile-system.json"
import ko_nav from "../locales/ko/nav.json"
import ko_notifications from "../locales/ko/notifications.json"
import ko_notifications_prefs from "../locales/ko/notifications-prefs.json"
import ko_onboarding_age from "../locales/ko/onboarding-age.json"
import ko_onboarding_terms from "../locales/ko/onboarding-terms.json"
import ko_post_composer from "../locales/ko/post-composer.json"
import ko_profile from "../locales/ko/profile.json"
import ko_profile_connections from "../locales/ko/profile-connections.json"
import ko_profile_follow from "../locales/ko/profile-follow.json"
import ko_profile_person from "../locales/ko/profile-person.json"
import ko_profile_view from "../locales/ko/profile-view.json"
import ko_report_cluster from "../locales/ko/report-cluster.json"
import ko_report_content from "../locales/ko/report-content.json"
import ko_report_detail from "../locales/ko/report-detail.json"
import ko_report_linked from "../locales/ko/report-linked.json"
import ko_report_list from "../locales/ko/report-list.json"
import ko_report_picker from "../locales/ko/report-picker.json"
import ko_report_row from "../locales/ko/report-row.json"
import ko_report_wizard from "../locales/ko/report-wizard.json"
import ko_search from "../locales/ko/search.json"
import ko_settings from "../locales/ko/settings.json"
import ko_settings_account from "../locales/ko/settings-account.json"
import ko_settings_privacy from "../locales/ko/settings-privacy.json"
import ko_share_post from "../locales/ko/share-post.json"
import ko_volunteer_hours from "../locales/ko/volunteer-hours.json"
import ko_web_auth from "../locales/ko/web-auth.json"
import ko_web_claims from "../locales/ko/web-claims.json"
import ko_web_common from "../locales/ko/web-common.json"
import ko_web_guest_cancel from "../locales/ko/web-guest-cancel.json"
import ko_web_registration from "../locales/ko/web-registration.json"
import ko_web_service_record from "../locales/ko/web-service-record.json"
import ko_web_signup from "../locales/ko/web-signup.json"
import ko_web_unsubscribe from "../locales/ko/web-unsubscribe.json"

const catalog: ResourceLanguage = {
  "about": ko_about,
  "account-blocked": ko_account_blocked,
  "account-delete": ko_account_delete,
  "address": ko_address,
  "appearance-settings": ko_appearance_settings,
  "channel-create": ko_channel_create,
  "common": ko_common,
  "common-datetime": ko_common_datetime,
  "common-search": ko_common_search,
  "common-share": ko_common_share,
  "conversation": ko_conversation,
  "conversation-mentions": ko_conversation_mentions,
  "conversation-polls": ko_conversation_polls,
  "conversation-reactions": ko_conversation_reactions,
  "discussion": ko_discussion,
  "discussion-composer": ko_discussion_composer,
  "discussion-delete": ko_discussion_delete,
  "donation-link": ko_donation_link,
  "enums": ko_enums,
  "event-bring": ko_event_bring,
  "event-cancel": ko_event_cancel,
  "event-card": ko_event_card,
  "event-create": ko_event_create,
  "event-dashboard": ko_event_dashboard,
  "event-detail": ko_event_detail,
  "event-edit": ko_event_edit,
  "event-form": ko_event_form,
  "event-guest-rsvp": ko_event_guest_rsvp,
  "event-list": ko_event_list,
  "event-members": ko_event_members,
  "event-resources": ko_event_resources,
  "event-rsvp": ko_event_rsvp,
  "event-slots": ko_event_slots,
  "group-create": ko_group_create,
  "group-info": ko_group_info,
  "home-feed": ko_home_feed,
  "home-sidebar": ko_home_sidebar,
  "host-analytics": ko_host_analytics,
  "host-attendees": ko_host_attendees,
  "host-broadcasts": ko_host_broadcasts,
  "host-checkin": ko_host_checkin,
  "host-common": ko_host_common,
  "host-event": ko_host_event,
  "host-exports": ko_host_exports,
  "host-mode": ko_host_mode,
  "host-org": ko_host_org,
  "host-page-builder": ko_host_page_builder,
  "host-portfolio": ko_host_portfolio,
  "host-settings": ko_host_settings,
  "host-team": ko_host_team,
  "host-ticket": ko_host_ticket,
  "host-tickets": ko_host_tickets,
  "language-settings": ko_language_settings,
  "leaderboard": ko_leaderboard,
  "lightbox": ko_lightbox,
  "map-address": ko_map_address,
  "map-ui": ko_map_ui,
  "messages-list": ko_messages_list,
  "mobile-a11y": ko_mobile_a11y,
  "mobile-auth-otp": ko_mobile_auth_otp,
  "mobile-auth-registration": ko_mobile_auth_registration,
  "mobile-auth-signin": ko_mobile_auth_signin,
  "mobile-auth-welcome": ko_mobile_auth_welcome,
  "mobile-branding": ko_mobile_branding,
  "mobile-errors": ko_mobile_errors,
  "mobile-onboarding": ko_mobile_onboarding,
  "mobile-report-camera": ko_mobile_report_camera,
  "mobile-system": ko_mobile_system,
  "nav": ko_nav,
  "notifications": ko_notifications,
  "notifications-prefs": ko_notifications_prefs,
  "onboarding-age": ko_onboarding_age,
  "onboarding-terms": ko_onboarding_terms,
  "post-composer": ko_post_composer,
  "profile": ko_profile,
  "profile-connections": ko_profile_connections,
  "profile-follow": ko_profile_follow,
  "profile-person": ko_profile_person,
  "profile-view": ko_profile_view,
  "report-cluster": ko_report_cluster,
  "report-content": ko_report_content,
  "report-detail": ko_report_detail,
  "report-linked": ko_report_linked,
  "report-list": ko_report_list,
  "report-picker": ko_report_picker,
  "report-row": ko_report_row,
  "report-wizard": ko_report_wizard,
  "search": ko_search,
  "settings": ko_settings,
  "settings-account": ko_settings_account,
  "settings-privacy": ko_settings_privacy,
  "share-post": ko_share_post,
  "volunteer-hours": ko_volunteer_hours,
  "web-auth": ko_web_auth,
  "web-claims": ko_web_claims,
  "web-common": ko_web_common,
  "web-guest-cancel": ko_web_guest_cancel,
  "web-registration": ko_web_registration,
  "web-service-record": ko_web_service_record,
  "web-signup": ko_web_signup,
  "web-unsubscribe": ko_web_unsubscribe,
}

export default catalog
