/**
 * AUTO-GENERATED by scripts/gen-i18n-resources.mjs: DO NOT EDIT BY HAND.
 *
 * Re-run `pnpm --filter @civfix/ui i18n:gen` after adding or removing a namespace or locale.
 */
import type { ResourceLanguage } from "i18next"
import type { SupportedLocale } from "@civfix/shared"

/** One loader per locale the web does not bundle statically; webpack emits each as its own chunk. */
export const lazyCatalogs: Record<
  Exclude<SupportedLocale, "en">,
  () => Promise<{ default: ResourceLanguage }>
> = {
  es: () => import(/* webpackChunkName: "i18n-es" */ "./es"),
  de: () => import(/* webpackChunkName: "i18n-de" */ "./de"),
  ko: () => import(/* webpackChunkName: "i18n-ko" */ "./ko"),
}
