import { def } from "../def.js"
import {
  EventAnalyticsBroadcastsResponseSchema,
  EventAnalyticsCheckinsResponseSchema,
  EventAnalyticsOverviewResponseSchema,
  EventAnalyticsRegistrationsResponseSchema,
  EventAnalyticsRequestSchema,
  EventAnalyticsSourcesResponseSchema,
  GetEventAnalyticsRequestSchema,
  GetEventAnalyticsResponseSchema,
  HostAnalyticsSummaryRequestSchema,
  HostAnalyticsSummaryResponseSchema,
  HostedEventsAnalyticsRequestSchema,
  HostedEventsAnalyticsResponseSchema,
} from "../../../schemas/host/analytics.js"
import {
  GetEventInsightsRequestSchema,
  GetEventInsightsResponseSchema,
} from "../../../schemas/host/insights.js"
import {
  DownloadHostExportRequestSchema,
  DownloadHostExportResponseSchema,
  GetEventExportRequestSchema,
  GetEventExportResponseSchema,
  ListEventExportsRequestSchema,
  ListEventExportsResponseSchema,
  RequestEventExportRequestSchema,
  RequestEventExportResponseSchema,
} from "../../../schemas/host/exports.js"

export const hostAnalyticsEndpoints = {
  getEventAnalytics: def({
    method: "GET",
    path: "/cleanups/:id/analytics",
    request: GetEventAnalyticsRequestSchema,
    response: GetEventAnalyticsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  eventAnalyticsOverview: def({
    method: "GET",
    path: "/cleanups/:id/analytics/overview",
    request: EventAnalyticsRequestSchema,
    response: EventAnalyticsOverviewResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  eventAnalyticsRegistrations: def({
    method: "GET",
    path: "/cleanups/:id/analytics/registrations",
    request: EventAnalyticsRequestSchema,
    response: EventAnalyticsRegistrationsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  eventAnalyticsCheckins: def({
    method: "GET",
    path: "/cleanups/:id/analytics/checkins",
    request: EventAnalyticsRequestSchema,
    response: EventAnalyticsCheckinsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  eventAnalyticsBroadcasts: def({
    method: "GET",
    path: "/cleanups/:id/analytics/broadcasts",
    request: EventAnalyticsRequestSchema,
    response: EventAnalyticsBroadcastsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  eventAnalyticsSources: def({
    method: "GET",
    path: "/cleanups/:id/analytics/sources",
    request: EventAnalyticsRequestSchema,
    response: EventAnalyticsSourcesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  hostedEventsAnalytics: def({
    method: "GET",
    path: "/me/hosted-events/analytics",
    request: HostedEventsAnalyticsRequestSchema,
    response: HostedEventsAnalyticsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  hostedEventsAnalyticsSummary: def({
    method: "GET",
    path: "/me/hosted-events/analytics/summary",
    request: HostAnalyticsSummaryRequestSchema,
    response: HostAnalyticsSummaryResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getEventInsights: def({
    method: "GET",
    path: "/cleanups/:id/insights",
    request: GetEventInsightsRequestSchema,
    response: GetEventInsightsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  requestEventExport: def({
    method: "POST",
    path: "/cleanups/:id/exports",
    request: RequestEventExportRequestSchema,
    response: RequestEventExportResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listEventExports: def({
    method: "GET",
    path: "/cleanups/:id/exports",
    request: ListEventExportsRequestSchema,
    response: ListEventExportsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getEventExport: def({
    method: "GET",
    path: "/cleanups/:id/exports/:exportId",
    request: GetEventExportRequestSchema,
    response: GetEventExportResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  downloadHostExport: def({
    method: "GET",
    path: "/me/host-exports/:id/download",
    request: DownloadHostExportRequestSchema,
    response: DownloadHostExportResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
} as const
