import { def } from "../def.js"
import {
  CancelEventBroadcastRequestSchema,
  CancelEventBroadcastResponseSchema,
  CreateEventBroadcastRequestSchema,
  CreateEventBroadcastResponseSchema,
  DeleteEventBroadcastRequestSchema,
  DeleteEventBroadcastResponseSchema,
  GetEventBroadcastRequestSchema,
  GetEventBroadcastResponseSchema,
  ListBroadcastDeliveriesRequestSchema,
  ListBroadcastDeliveriesResponseSchema,
  ListEventBroadcastsRequestSchema,
  ListEventBroadcastsResponseSchema,
  OpenUnsubscribeBroadcastsRequestSchema,
  OpenUnsubscribeBroadcastsResponseSchema,
  PreviewEventBroadcastRequestSchema,
  PreviewEventBroadcastResponseSchema,
  ScheduleEventBroadcastRequestSchema,
  ScheduleEventBroadcastResponseSchema,
  SendEventBroadcastRequestSchema,
  SendEventBroadcastResponseSchema,
  SetEventBroadcastMuteRequestSchema,
  SetEventBroadcastMuteResponseSchema,
  TestSendEventBroadcastRequestSchema,
  TestSendEventBroadcastResponseSchema,
  UnsubscribeBroadcastsRequestSchema,
  UnsubscribeBroadcastsResponseSchema,
  UpdateEventBroadcastRequestSchema,
  UpdateEventBroadcastResponseSchema,
} from "../../../schemas/host/broadcasts.js"
import {
  CreateEventAnnouncementRequestSchema,
  CreateEventAnnouncementResponseSchema,
  GetEventAnnouncementRequestSchema,
  GetEventAnnouncementResponseSchema,
  ListEventAnnouncementsRequestSchema,
  ListEventAnnouncementsResponseSchema,
} from "../../../schemas/host/announcements.js"

export const hostBroadcastEndpoints = {
  listEventBroadcasts: def({
    method: "GET",
    path: "/cleanups/:id/broadcasts",
    request: ListEventBroadcastsRequestSchema,
    response: ListEventBroadcastsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  createEventBroadcast: def({
    method: "POST",
    path: "/cleanups/:id/broadcasts",
    request: CreateEventBroadcastRequestSchema,
    response: CreateEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getEventBroadcast: def({
    method: "GET",
    path: "/cleanups/:id/broadcasts/:broadcastId",
    request: GetEventBroadcastRequestSchema,
    response: GetEventBroadcastResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  updateEventBroadcast: def({
    method: "PATCH",
    path: "/cleanups/:id/broadcasts/:broadcastId",
    request: UpdateEventBroadcastRequestSchema,
    response: UpdateEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  deleteEventBroadcast: def({
    method: "DELETE",
    path: "/cleanups/:id/broadcasts/:broadcastId",
    request: DeleteEventBroadcastRequestSchema,
    response: DeleteEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  previewEventBroadcast: def({
    method: "POST",
    path: "/cleanups/:id/broadcast-preview",
    request: PreviewEventBroadcastRequestSchema,
    response: PreviewEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  testSendEventBroadcast: def({
    method: "POST",
    path: "/cleanups/:id/broadcasts/:broadcastId/test-send",
    request: TestSendEventBroadcastRequestSchema,
    response: TestSendEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  sendEventBroadcast: def({
    method: "POST",
    path: "/cleanups/:id/broadcasts/:broadcastId/send",
    request: SendEventBroadcastRequestSchema,
    response: SendEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  scheduleEventBroadcast: def({
    method: "POST",
    path: "/cleanups/:id/broadcasts/:broadcastId/schedule",
    request: ScheduleEventBroadcastRequestSchema,
    response: ScheduleEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  cancelEventBroadcast: def({
    method: "POST",
    path: "/cleanups/:id/broadcasts/:broadcastId/cancel",
    request: CancelEventBroadcastRequestSchema,
    response: CancelEventBroadcastResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listBroadcastDeliveries: def({
    method: "GET",
    path: "/cleanups/:id/broadcasts/:broadcastId/deliveries",
    request: ListBroadcastDeliveriesRequestSchema,
    response: ListBroadcastDeliveriesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  setEventBroadcastMute: def({
    method: "POST",
    path: "/cleanups/:id/broadcast-mute",
    request: SetEventBroadcastMuteRequestSchema,
    response: SetEventBroadcastMuteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  unsubscribeBroadcasts: def({
    method: "POST",
    path: "/broadcasts/unsubscribe",
    request: UnsubscribeBroadcastsRequestSchema,
    response: UnsubscribeBroadcastsResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  openUnsubscribeBroadcasts: def({
    method: "GET",
    path: "/broadcasts/unsubscribe",
    request: OpenUnsubscribeBroadcastsRequestSchema,
    response: OpenUnsubscribeBroadcastsResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),

  createEventAnnouncement: def({
    method: "POST",
    path: "/cleanups/:id/announcements",
    request: CreateEventAnnouncementRequestSchema,
    response: CreateEventAnnouncementResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listEventAnnouncements: def({
    method: "GET",
    path: "/cleanups/:id/announcements",
    request: ListEventAnnouncementsRequestSchema,
    response: ListEventAnnouncementsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  getEventAnnouncement: def({
    method: "GET",
    path: "/cleanups/:id/announcements/:announcementId",
    request: GetEventAnnouncementRequestSchema,
    response: GetEventAnnouncementResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
} as const
