import { def } from "../def.js"
import {
  CheckInEventSeatRequestSchema,
  CheckInEventSeatResponseSchema,
  GetEventCheckinCountersRequestSchema,
  GetEventCheckinCountersResponseSchema,
  GetGuestEventTicketRequestSchema,
  GetGuestEventTicketResponseSchema,
  GetMyEventTicketRequestSchema,
  GetMyEventTicketResponseSchema,
  MarkEventNoShowsRequestSchema,
  MarkEventNoShowsResponseSchema,
  ScanEventTicketRequestSchema,
  ScanEventTicketResponseSchema,
  UndoEventCheckInRequestSchema,
  UndoEventCheckInResponseSchema,
} from "../../../schemas/host/checkin.js"
import { GetEventIcsRequestSchema, GetEventIcsResponseSchema } from "../../../schemas/host/ics.js"

export const hostCheckinEndpoints = {
  getEventIcs: def({
    method: "GET",
    path: "/cleanups/:id/ics",
    request: GetEventIcsRequestSchema,
    response: GetEventIcsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  getMyEventTicket: def({
    method: "GET",
    path: "/cleanups/:id/ticket",
    request: GetMyEventTicketRequestSchema,
    response: GetMyEventTicketResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getGuestEventTicket: def({
    method: "POST",
    path: "/guest-rsvp/ticket",
    request: GetGuestEventTicketRequestSchema,
    response: GetGuestEventTicketResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  scanEventTicket: def({
    method: "POST",
    path: "/cleanups/:id/checkins/scan",
    request: ScanEventTicketRequestSchema,
    response: ScanEventTicketResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  checkInEventSeat: def({
    method: "POST",
    path: "/cleanups/:id/checkins",
    request: CheckInEventSeatRequestSchema,
    response: CheckInEventSeatResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  markEventNoShows: def({
    method: "POST",
    path: "/cleanups/:id/checkins/no-show",
    request: MarkEventNoShowsRequestSchema,
    response: MarkEventNoShowsResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  undoEventCheckIn: def({
    method: "DELETE",
    path: "/cleanups/:id/checkins/:seatId",
    request: UndoEventCheckInRequestSchema,
    response: UndoEventCheckInResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getEventCheckinCounters: def({
    method: "GET",
    path: "/cleanups/:id/checkins/counters",
    request: GetEventCheckinCountersRequestSchema,
    response: GetEventCheckinCountersResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
} as const
