import { def } from "../def.js"
import {
  AcceptOrganizationInviteRequestSchema,
  AcceptOrganizationInviteResponseSchema,
  ApplyOrganizationVerificationRequestSchema,
  ApplyOrganizationVerificationResponseSchema,
  CreateOrganizationRequestSchema,
  CreateOrganizationResponseSchema,
  GetOrganizationRequestSchema,
  GetOrganizationResponseSchema,
  GetOrganizationVerificationRequestSchema,
  GetOrganizationVerificationResponseSchema,
  AcceptMyOrgInviteRequestSchema,
  AcceptMyOrgInviteResponseSchema,
  DeclineMyOrgInviteRequestSchema,
  DeclineMyOrgInviteResponseSchema,
  InviteOrganizationMemberRequestSchema,
  InviteOrganizationMemberResponseSchema,
  ListMyOrgInvitesResponseSchema,
  ListMyOrganizationsResponseSchema,
  ListOrganizationEventsRequestSchema,
  ListOrganizationEventsResponseSchema,
  ListOrganizationInvitesRequestSchema,
  ListOrganizationInvitesResponseSchema,
  ListOrganizationMembersRequestSchema,
  ListOrganizationMembersResponseSchema,
  RemoveOrganizationMemberRequestSchema,
  RemoveOrganizationMemberResponseSchema,
  RevokeOrganizationInviteRequestSchema,
  RevokeOrganizationInviteResponseSchema,
  SetOrganizationMemberRoleRequestSchema,
  SetOrganizationMemberRoleResponseSchema,
  UpdateOrganizationRequestSchema,
  UpdateOrganizationResponseSchema,
} from "../../../schemas/host/organizations.js"

export const hostOrganizationEndpoints = {
  createOrganization: def({
    method: "POST",
    path: "/orgs",
    request: CreateOrganizationRequestSchema,
    response: CreateOrganizationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listMyOrganizations: def({
    method: "GET",
    path: "/me/organizations",
    request: null,
    response: ListMyOrganizationsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  getOrganization: def({
    method: "GET",
    path: "/orgs/by-slug/:slug",
    request: GetOrganizationRequestSchema,
    response: GetOrganizationResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  listOrganizationEvents: def({
    method: "GET",
    path: "/orgs/by-slug/:slug/events",
    request: ListOrganizationEventsRequestSchema,
    response: ListOrganizationEventsResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  updateOrganization: def({
    method: "PATCH",
    path: "/orgs/:id",
    request: UpdateOrganizationRequestSchema,
    response: UpdateOrganizationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listOrganizationMembers: def({
    method: "GET",
    path: "/orgs/:id/members",
    request: ListOrganizationMembersRequestSchema,
    response: ListOrganizationMembersResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  inviteOrganizationMember: def({
    method: "POST",
    path: "/orgs/:id/members",
    request: InviteOrganizationMemberRequestSchema,
    response: InviteOrganizationMemberResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setOrganizationMemberRole: def({
    method: "PATCH",
    path: "/orgs/:id/members/:userId",
    request: SetOrganizationMemberRoleRequestSchema,
    response: SetOrganizationMemberRoleResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  removeOrganizationMember: def({
    method: "DELETE",
    path: "/orgs/:id/members/:userId",
    request: RemoveOrganizationMemberRequestSchema,
    response: RemoveOrganizationMemberResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  applyOrganizationVerification: def({
    method: "POST",
    path: "/orgs/:id/verification",
    request: ApplyOrganizationVerificationRequestSchema,
    response: ApplyOrganizationVerificationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getOrganizationVerification: def({
    method: "GET",
    path: "/orgs/:id/verification",
    request: GetOrganizationVerificationRequestSchema,
    response: GetOrganizationVerificationResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  listOrganizationInvites: def({
    method: "GET",
    path: "/orgs/:id/invites",
    request: ListOrganizationInvitesRequestSchema,
    response: ListOrganizationInvitesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  revokeOrganizationInvite: def({
    method: "DELETE",
    path: "/orgs/:id/invites/:inviteId",
    request: RevokeOrganizationInviteRequestSchema,
    response: RevokeOrganizationInviteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  // Not under /orgs/: every /orgs/* route is /orgs/:id or /orgs/by-slug/ (pinned by a test), and
  // the token identifies the org, so the accept lives on its own static prefix.
  acceptOrganizationInvite: def({
    method: "POST",
    path: "/org-invites/accept",
    request: AcceptOrganizationInviteRequestSchema,
    response: AcceptOrganizationInviteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listMyOrgInvites: def({
    method: "GET",
    path: "/me/org-invites",
    request: null,
    response: ListMyOrgInvitesResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  acceptMyOrgInvite: def({
    method: "POST",
    path: "/me/org-invites/:inviteId/accept",
    request: AcceptMyOrgInviteRequestSchema,
    response: AcceptMyOrgInviteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  declineMyOrgInvite: def({
    method: "POST",
    path: "/me/org-invites/:inviteId/decline",
    request: DeclineMyOrgInviteRequestSchema,
    response: DeclineMyOrgInviteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
