import { def } from "../def.js"
import {
  CheckEventPageSlugRequestSchema,
  CheckEventPageSlugResponseSchema,
  GetEventPageRequestSchema,
  GetEventPageResponseSchema,
  GetPublicEventPageRequestSchema,
  GetPublicEventPageResponseSchema,
  PublishEventPageRequestSchema,
  PublishEventPageResponseSchema,
  RecordEventPageViewRequestSchema,
  RecordEventPageViewResponseSchema,
  SaveEventPageRequestSchema,
  SaveEventPageResponseSchema,
} from "../../../schemas/host/pages.js"

export const hostPageEndpoints = {
  getPublicEventPage: def({
    method: "GET",
    path: "/pages/:slug",
    request: GetPublicEventPageRequestSchema,
    response: GetPublicEventPageResponseSchema,
    auth: "optional",
    csrf: false,
    version: "v1",
  }),
  recordEventPageView: def({
    method: "POST",
    path: "/pages/:slug/view",
    request: RecordEventPageViewRequestSchema,
    response: RecordEventPageViewResponseSchema,
    auth: "public",
    csrf: false,
    version: "v1",
  }),
  getEventPage: def({
    method: "GET",
    path: "/cleanups/:id/page",
    request: GetEventPageRequestSchema,
    response: GetEventPageResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  saveEventPage: def({
    method: "PUT",
    path: "/cleanups/:id/page",
    request: SaveEventPageRequestSchema,
    response: SaveEventPageResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  publishEventPage: def({
    method: "POST",
    path: "/cleanups/:id/page/publish",
    request: PublishEventPageRequestSchema,
    response: PublishEventPageResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  checkEventPageSlug: def({
    method: "GET",
    path: "/cleanups/:id/page/slug-check",
    request: CheckEventPageSlugRequestSchema,
    response: CheckEventPageSlugResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
} as const
