import { def } from "../def.js"
import {
  CancelEventRegistrationRequestSchema,
  CancelEventRegistrationResponseSchema,
  CreateWalkupRegistrationRequestSchema,
  CreateWalkupRegistrationResponseSchema,
  GetEventRegistrationAnswersRequestSchema,
  GetEventRegistrationAnswersResponseSchema,
  GetEventRegistrationRequestSchema,
  GetEventRegistrationResponseSchema,
  ListEventRegistrationsRequestSchema,
  ListEventRegistrationsResponseSchema,
  RegisterForEventRequestSchema,
  RegisterForEventResponseSchema,
  RemoveEventRegistrationRequestSchema,
  RemoveEventRegistrationResponseSchema,
  SetEventRegistrationNoteRequestSchema,
  SetEventRegistrationNoteResponseSchema,
  TransferEventRegistrationRequestSchema,
  TransferEventRegistrationResponseSchema,
} from "../../../schemas/host/registrations.js"
import {
  ClaimWaitlistOfferRequestSchema,
  ClaimWaitlistOfferResponseSchema,
  JoinEventWaitlistRequestSchema,
  JoinEventWaitlistResponseSchema,
  LeaveEventWaitlistRequestSchema,
  LeaveEventWaitlistResponseSchema,
  ListEventWaitlistRequestSchema,
  ListEventWaitlistResponseSchema,
  PromoteFromWaitlistRequestSchema,
  PromoteFromWaitlistResponseSchema,
} from "../../../schemas/host/waitlist.js"

export const hostRegistrationEndpoints = {
  registerForEvent: def({
    method: "POST",
    path: "/cleanups/:id/registrations",
    request: RegisterForEventRequestSchema,
    response: RegisterForEventResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listEventRegistrations: def({
    method: "GET",
    path: "/cleanups/:id/registrations",
    request: ListEventRegistrationsRequestSchema,
    response: ListEventRegistrationsResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  createWalkupRegistration: def({
    method: "POST",
    path: "/cleanups/:id/registrations/walkup",
    request: CreateWalkupRegistrationRequestSchema,
    response: CreateWalkupRegistrationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getEventRegistration: def({
    method: "GET",
    path: "/cleanups/:id/registrations/:registrationId",
    request: GetEventRegistrationRequestSchema,
    response: GetEventRegistrationResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  removeEventRegistration: def({
    method: "DELETE",
    path: "/cleanups/:id/registrations/:registrationId",
    request: RemoveEventRegistrationRequestSchema,
    response: RemoveEventRegistrationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  cancelEventRegistration: def({
    method: "POST",
    path: "/cleanups/:id/registrations/:registrationId/cancel",
    request: CancelEventRegistrationRequestSchema,
    response: CancelEventRegistrationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  transferEventRegistration: def({
    method: "POST",
    path: "/cleanups/:id/registrations/:registrationId/transfer",
    request: TransferEventRegistrationRequestSchema,
    response: TransferEventRegistrationResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  setEventRegistrationNote: def({
    method: "PUT",
    path: "/cleanups/:id/registrations/:registrationId/note",
    request: SetEventRegistrationNoteRequestSchema,
    response: SetEventRegistrationNoteResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  getEventRegistrationAnswers: def({
    method: "GET",
    path: "/cleanups/:id/registrations/:registrationId/answers",
    request: GetEventRegistrationAnswersRequestSchema,
    response: GetEventRegistrationAnswersResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),

  joinEventWaitlist: def({
    method: "POST",
    path: "/cleanups/:id/waitlist",
    request: JoinEventWaitlistRequestSchema,
    response: JoinEventWaitlistResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  leaveEventWaitlist: def({
    method: "DELETE",
    path: "/cleanups/:id/waitlist",
    request: LeaveEventWaitlistRequestSchema,
    response: LeaveEventWaitlistResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  listEventWaitlist: def({
    method: "GET",
    path: "/cleanups/:id/waitlist",
    request: ListEventWaitlistRequestSchema,
    response: ListEventWaitlistResponseSchema,
    auth: "required",
    csrf: false,
    version: "v1",
  }),
  claimWaitlistOffer: def({
    method: "POST",
    path: "/cleanups/:id/waitlist/claim",
    request: ClaimWaitlistOfferRequestSchema,
    response: ClaimWaitlistOfferResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
  promoteFromWaitlist: def({
    method: "POST",
    path: "/cleanups/:id/waitlist/:waitlistId/promote",
    request: PromoteFromWaitlistRequestSchema,
    response: PromoteFromWaitlistResponseSchema,
    auth: "required",
    csrf: true,
    version: "v1",
  }),
} as const
