#!/usr/bin/env bash
# Re-apply the four machine-local pieces a release gradle build needs and `expo prebuild` does not
# provide, then clear the one stale generated file a non-clean prebuild leaves behind. Idempotent:
# safe to run before every release build, and a no-op when nothing is missing.
#
#   scripts/android-release-patches.sh
#
# WHY THIS EXISTS. `android/` is gitignored and regenerated by `expo prebuild` (which
# scripts/prep-archive.sh runs), so everything below is wiped or reset to the stock Expo template on
# every prep. A re-prebuild over an EXISTING android/ happens to preserve 3 and 4, but a fresh clone
# has none of them, and the failure modes are all misleading:
#
#   1. android/local.properties   -> gradle dies at configuration time with "SDK location not found".
#                                    Only `expo run:android` writes it. On this machine the SDK is
#                                    the homebrew android-commandlinetools cask, NOT ~/Library/Android/sdk.
#   2. android/keystore.properties-> without it the release build silently falls back to the DEBUG
#                                    keystore and Play rejects the upload.
#   3. app/build.gradle signing   -> the stock template ships `release { signingConfig signingConfigs.debug }`
#                                    and has no signingConfigs.release block at all, so both the APK
#                                    and the AAB come out debug-signed.
#   4. gradle.properties jvmargs  -> at Expo's default -XX:MaxMetaspaceSize=512m,
#                                    :expo-updates:kspReleaseKotlin dies with
#                                    "A failure occurred while executing KspAAWorkerAction > Metaspace".
#                                    Metaspace is NOT part of the heap, so raising -Xmx alone does nothing.
#   5. values-night/colors.xml    -> the opposite problem: a non-clean prebuild PRESERVES this file, so
#                                    the dark splashscreen_background written before the light-only
#                                    launch screen (2026-09-14) survives and Android paints the launch
#                                    screen dark in dark mode. A clean prebuild writes an empty
#                                    <resources/> there, which is what deleting the stale file leaves.
#
# Build afterwards with JDK 22 (the Gradle 8.14.3 wrapper cannot use the default Temurin 25):
#   export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home
#   cd android && ./gradlew --no-daemon :app:assembleRelease :app:bundleRelease
set -euo pipefail

cd "$(dirname "$0")/.."

sdk_dir="${CIVFIX_ANDROID_SDK_DIR:-${ANDROID_HOME:-${ANDROID_SDK_ROOT:-/opt/homebrew/share/android-commandlinetools}}}"
keystore_dir="${CIVFIX_KEYSTORE_DIR:-$HOME/civfix-keystore}"
keystore_file="${CIVFIX_KEYSTORE_FILE:-$keystore_dir/civfix-upload.keystore}"
password_file="${CIVFIX_KEYSTORE_PASSWORD_FILE:-$keystore_dir/.password.txt}"
key_alias="${CIVFIX_KEY_ALIAS:-civfix-upload}"

if [ ! -d android ]; then
  echo "android/ not found - run scripts/prep-archive.sh <target> --platform android first." >&2
  exit 1
fi

note() { echo "  $1"; }
applied() { echo "  APPLIED  $1"; }

echo "Re-applying Android release patches..."

# 1. SDK pointer.
if [ ! -d "$sdk_dir" ]; then
  echo "Android SDK not found at $sdk_dir (override with CIVFIX_ANDROID_SDK_DIR)." >&2
  exit 1
fi
if grep -qs "^sdk\.dir=${sdk_dir}\$" android/local.properties; then
  note "ok       android/local.properties already points at $sdk_dir"
else
  cat > android/local.properties <<EOF
# Machine-local Android SDK location. Gitignored, and NOT regenerated by \`expo prebuild\`.
sdk.dir=${sdk_dir}
EOF
  applied "android/local.properties (sdk.dir=$sdk_dir)"
fi

# 2. Release keystore credentials. Written 600 - it holds the keystore password in cleartext.
if [ ! -f "$keystore_file" ]; then
  echo "Release keystore missing at $keystore_file - this machine cannot sign a release build." >&2
  echo "It is NOT in git; restore it from backup. Losing it means the Play listing can never be updated." >&2
  exit 1
fi
if [ ! -f "$password_file" ]; then
  echo "Keystore password file missing at $password_file." >&2
  exit 1
fi
keystore_password="$(tr -d '\n' < "$password_file")"
umask 077
tmp_props="$(mktemp)"
cat > "$tmp_props" <<EOF
storeFile=${keystore_file}
storePassword=${keystore_password}
keyAlias=${key_alias}
keyPassword=${keystore_password}
EOF
if [ -f android/keystore.properties ] && cmp -s "$tmp_props" android/keystore.properties; then
  rm -f "$tmp_props"
  chmod 600 android/keystore.properties
  note "ok       android/keystore.properties already correct"
else
  mv "$tmp_props" android/keystore.properties
  chmod 600 android/keystore.properties
  applied "android/keystore.properties (alias $key_alias, mode 600)"
fi
umask 022

# 3 + 4. The two generated gradle files. Done in python because both edits are structural (brace
# matching inside app/build.gradle), not line-wise, and must survive being run twice.
python3 <<'PY'
import re

BUILD_GRADLE = "android/app/build.gradle"
GRADLE_PROPS = "android/gradle.properties"

JVMARGS = "-Xmx6g -XX:MaxMetaspaceSize=2g"
KOTLIN_JVMARGS = "-Xmx4g -XX:MaxMetaspaceSize=1g"

LOADER = """

// Release signing: load credentials from android/keystore.properties (gitignored, not committed).
// Falls back to the debug keystore if the file is absent so dev builds still work.
def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}"""

RELEASE_SIGNING_CONFIG = """        release {
            if (keystoreProperties.containsKey('storeFile')) {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
"""

RELEASE_SIGNING_CONFIG_REF = (
    "            // Signed with the release keystore from android/keystore.properties "
    "(see signingConfigs.release).\n"
    "            // Falls back to the debug keystore only if that file is missing.\n"
    "            signingConfig keystoreProperties.containsKey('storeFile') "
    "? signingConfigs.release : signingConfigs.debug"
)

JVMARGS_COMMENT = """# Raised from the Expo default (-Xmx2048m / MaxMetaspaceSize=512m): :expo-updates:kspReleaseKotlin
# dies with "A failure occurred while executing KspAAWorkerAction > Metaspace" at 512m. KSP loads a
# lot of classes and metaspace is NOT part of the heap, so bumping -Xmx alone does not help.
# NOTE: android/ is gitignored and regenerated by `expo prebuild`, which restores the Expo defaults -
# re-apply with scripts/android-release-patches.sh after any prebuild.
"""

changed = []


def block_body(src, start):
    """Return (body_start, body_end) for the brace block whose opening { is at or after `start`."""
    open_at = src.index("{", start)
    depth = 0
    for i in range(open_at, len(src)):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                return open_at + 1, i
    raise SystemExit("unbalanced braces in " + BUILD_GRADLE)


def patch_build_gradle():
    src = open(BUILD_GRADLE).read()
    original = src

    if "keystorePropertiesFile" not in src:
        anchor = re.search(r"^def projectRoot = .*$", src, re.M)
        if not anchor:
            raise SystemExit("could not find the `def projectRoot` anchor in " + BUILD_GRADLE)
        src = src[: anchor.end()] + LOADER + src[anchor.end():]
        changed.append("app/build.gradle: keystore.properties loader")

    sc = re.search(r"^\s*signingConfigs\s*\{", src, re.M)
    if not sc:
        raise SystemExit("could not find a signingConfigs block in " + BUILD_GRADLE)
    body_start, body_end = block_body(src, sc.start())
    if not re.search(r"^\s*release\s*\{", src[body_start:body_end], re.M):
        at = src.rfind("\n", 0, body_end) + 1
        src = src[:at] + RELEASE_SIGNING_CONFIG + src[at:]
        changed.append("app/build.gradle: signingConfigs.release")

    bt = re.search(r"^\s*buildTypes\s*\{", src, re.M)
    if not bt:
        raise SystemExit("could not find a buildTypes block in " + BUILD_GRADLE)
    bt_start, bt_end = block_body(src, bt.start())
    rel = re.search(r"^\s*release\s*\{", src[bt_start:bt_end], re.M)
    if not rel:
        raise SystemExit("could not find buildTypes.release in " + BUILD_GRADLE)
    rel_start, rel_end = block_body(src, bt_start + rel.start())
    rel_body = src[rel_start:rel_end]
    if "signingConfigs.release" not in rel_body:
        new_body, n = re.subn(
            r"^[ \t]*(?://[^\n]*\n[ \t]*)*signingConfig signingConfigs\.debug[ \t]*$",
            RELEASE_SIGNING_CONFIG_REF,
            rel_body,
            count=1,
            flags=re.M,
        )
        if n != 1:
            raise SystemExit("could not rewrite buildTypes.release signingConfig in " + BUILD_GRADLE)
        src = src[:rel_start] + new_body + src[rel_end:]
        changed.append("app/build.gradle: buildTypes.release signingConfig -> release")

    if src != original:
        open(BUILD_GRADLE, "w").write(src)


def patch_gradle_properties():
    src = open(GRADLE_PROPS).read()
    original = src

    src, n = re.subn(
        r"^org\.gradle\.jvmargs=.*$", "org.gradle.jvmargs=" + JVMARGS, src, count=1, flags=re.M
    )
    if n == 0:
        src = src.rstrip("\n") + "\n\n" + JVMARGS_COMMENT + "org.gradle.jvmargs=" + JVMARGS + "\n"
    elif JVMARGS_COMMENT.splitlines()[0] not in src:
        src = src.replace(
            "org.gradle.jvmargs=" + JVMARGS, JVMARGS_COMMENT + "org.gradle.jvmargs=" + JVMARGS, 1
        )

    src, n = re.subn(
        r"^kotlin\.daemon\.jvmargs=.*$",
        "kotlin.daemon.jvmargs=" + KOTLIN_JVMARGS,
        src,
        count=1,
        flags=re.M,
    )
    if n == 0:
        src = src.replace(
            "org.gradle.jvmargs=" + JVMARGS,
            "org.gradle.jvmargs=" + JVMARGS + "\nkotlin.daemon.jvmargs=" + KOTLIN_JVMARGS,
            1,
        )

    if src != original:
        open(GRADLE_PROPS, "w").write(src)
        changed.append("gradle.properties: jvmargs + kotlin.daemon.jvmargs")


patch_build_gradle()
patch_gradle_properties()

for line in changed:
    print("  APPLIED  " + line)
if not changed:
    print("  ok       app/build.gradle and gradle.properties already patched")
PY

# 5. Stale dark splash colour left behind by a non-clean prebuild.
night_colors="android/app/src/main/res/values-night/colors.xml"
if [ -f "$night_colors" ] && grep -q "splashscreen_background" "$night_colors"; then
  rm -f "$night_colors"
  applied "removed $night_colors (stale dark splashscreen_background)"
else
  note "ok       no stale splashscreen_background in values-night/colors.xml"
fi

echo
echo "=========================== ANDROID RELEASE PATCHES ========================"
echo "  sdk.dir       $(sed -n 's/^sdk\.dir=//p' android/local.properties | head -1)"
echo "  keystore      $(sed -n 's/^storeFile=//p' android/keystore.properties | head -1)"
echo "  key alias     $(sed -n 's/^keyAlias=//p' android/keystore.properties | head -1)"
echo "  perms         $(stat -c '%a' android/keystore.properties 2>/dev/null || stat -f '%Lp' android/keystore.properties) (android/keystore.properties)"
echo "  release sign  $(grep -c 'signingConfigs\.release' android/app/build.gradle) reference(s) in app/build.gradle"
echo "  jvmargs       $(sed -n 's/^org\.gradle\.jvmargs=//p' android/gradle.properties | head -1)"
echo "  kotlin args   $(sed -n 's/^kotlin\.daemon\.jvmargs=//p' android/gradle.properties | head -1)"
echo "  night splash  $(grep -qs splashscreen_background "$night_colors" && echo 'STALE dark colour still present' || echo 'clean (launch screen is light in both appearances)')"
echo "============================================================================"
