#!/usr/bin/env bash
# Prepare the native iOS project for a HAND-DRIVEN Xcode archive (Product > Archive), with the right
# API base URL baked in. Does not build or upload anything.
#
#   scripts/prep-archive.sh testflight    dev/testing build -> staging API  https://api.civfix.dev
#   scripts/prep-archive.sh appstore      App Store release -> prod API     https://api.civfix.org
#   scripts/prep-archive.sh <target> --platform android    same, for the gradle release build
#
# WHY THIS EXISTS. `eas.json` build profiles are read by `eas build` ONLY. A raw Xcode archive never
# sees them, so archiving with the eas.json split in place would still produce whatever URL the
# fallback picks. What a raw archive DOES read is `.env`: the Xcode "Bundle React Native code and
# images" phase runs `expo export:embed` (inlines EXPO_PUBLIC_* into the JS bundle) and the
# expo-constants pod phase runs getAppConfig.js, which calls `@expo/env`.load() before serialising the
# app config into EXConstants.bundle. Both therefore pick up `.env` at ARCHIVE time - so this script
# writes `.env`, then regenerates the native project from it.
#
# `.env` is gitignored and persists, so it silently governs every later local build too. That is
# exactly how a TestFlight prep would otherwise poison a subsequent App Store archive, which is why
# the appstore target writes the prod URL EXPLICITLY instead of leaning on the fallback in
# src/lib/apiUrl.ts, and why the banner below prints the baked URL read back off the built config.
set -euo pipefail

cd "$(dirname "$0")/.."

usage() {
  echo "usage: scripts/prep-archive.sh testflight|appstore [--platform ios|android]" >&2
  exit 1
}

target="${1:-}"
case "$target" in
  testflight) api_url="https://api.civfix.dev"; channel="testflight" ;;
  appstore)   api_url="https://api.civfix.org"; channel="production" ;;
  *) usage ;;
esac

platform="ios"
if [ "${2:-}" = "--platform" ]; then
  platform="${3:-}"
  case "$platform" in ios|android) ;; *) usage ;; esac
elif [ -n "${2:-}" ]; then
  usage
fi

command -v node >/dev/null 2>&1 || { echo "node not found." >&2; exit 1; }

# Rewriting project.pbxproj under a running Xcode leaves its build service holding a stale project
# graph, which surfaces on the next build as:
#   error: Could not compute dependency graph: MsgHandlingError(message: "unable to initiate PIF
#   transfer session (operation in progress?)")
# The project on disk is fine at that point - only Xcode's in-memory session is stale.
if pgrep -xq "Xcode"; then
  echo
  echo "WARNING: Xcode is running. This script rewrites the Xcode project, which will leave Xcode"
  echo "holding a stale project graph ('unable to initiate PIF transfer session' on the next build)."
  echo "Close the workspace now and reopen it after this finishes. If you already hit that error:"
  echo "  pkill -x SWBBuildService   # or XCBBuildService on older Xcode; Xcode respawns it"
  echo "and if it persists, quit Xcode entirely and reopen ios/civfix.xcworkspace."
  echo
fi
if [ "$platform" = "ios" ]; then
  command -v xcodebuild >/dev/null 2>&1 || { echo "xcodebuild not found. Install Xcode + command-line tools." >&2; exit 1; }
fi

# Keep the Google values in lockstep with eas.json so a local archive and an EAS build of the same
# target are byte-for-byte equivalent in configuration. These are public client ids, not secrets.
cat > .env <<EOF
# GENERATED by scripts/prep-archive.sh ${target} - do not edit by hand, re-run the script instead.
# This file is what bakes the API base URL into a local Xcode archive / gradle release build.
EXPO_PUBLIC_API_URL=${api_url}
CIVFIX_UPDATE_CHANNEL=${channel}
EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=521996499476-d86mdmhsuopfp9gmqf7qarc2ousv6sqt.apps.googleusercontent.com
EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID=521996499476-0oghodcp5h8o3anfob8k71ltj9h6ab1t.apps.googleusercontent.com
EXPO_PUBLIC_GOOGLE_IOS_URL_SCHEME=com.googleusercontent.apps.521996499476-0oghodcp5h8o3anfob8k71ltj9h6ab1t
EOF
echo "Wrote .env for target '${target}' (API ${api_url}, update channel ${channel})."

# Bring node_modules into agreement with the lockfile BEFORE bundling anything. The Xcode archive
# bundles JS straight out of node_modules, and nothing else in the pipeline notices when that is
# behind: `pnpm-lock.yaml` can say @civfix/ui 0.51.1 while node_modules still holds 0.50.0, and
# typecheck + tests go green because they resolve the same stale copy. That is how a "latest" archive
# silently ships week-old @civfix/ui to TestFlight (hit exactly this on 2026-08-11).
# --frozen-lockfile so this can only correct node_modules, never quietly re-resolve the lockfile.
echo "Syncing node_modules to pnpm-lock.yaml..."
(cd ../.. && pnpm install --frozen-lockfile)

# Carry the Xcode signing team across the prebuild. `withDevelopmentTeam` deletes DEVELOPMENT_TEAM
# from the pbxproj on every prebuild unless ios.appleTeamId is set, so a team chosen by hand in
# Signing & Capabilities would vanish here. Read it back out and feed it to app.config.js. This only
# affects how the archive is signed locally - the team/certificate for the upload itself is still
# chosen in Xcode's Distribute flow.
if [ -z "${CIVFIX_APPLE_TEAM_ID:-}" ] && [ -f ios/civfix.xcodeproj/project.pbxproj ]; then
  detected=$(sed -n 's/^[[:space:]]*DEVELOPMENT_TEAM = "\{0,1\}\([A-Z0-9]*\)"\{0,1\};.*/\1/p' \
    ios/civfix.xcodeproj/project.pbxproj | head -1)
  if [ -n "$detected" ]; then
    export CIVFIX_APPLE_TEAM_ID="$detected"
    echo "Preserving Xcode signing team ${detected} across the prebuild."
  else
    echo "No DEVELOPMENT_TEAM in the current project - you will need to pick a team in Xcode."
  fi
fi

# CocoaPods chokes on an ASCII locale (see README).
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# android/local.properties is machine-local and gitignored, and ONLY `expo run:android` writes it -
# a prebuild that recreates android/ leaves gradle with "SDK location not found". Same class as the
# DEVELOPMENT_TEAM above: carry it across rather than making the next person rediscover it.
sdk_dir=""
if [ "$platform" = "android" ] && [ -f android/local.properties ]; then
  sdk_dir=$(sed -n 's/^sdk\.dir=//p' android/local.properties | head -1)
fi

# No --clean: the config plugins re-apply over the existing project, and a wipe would also take out
# ios/.xcode.env.local (the NODE_BINARY pin the Xcode script phases need).
echo "Regenerating the native ${platform} project (expo prebuild)..."
# --no-install: node_modules is already resolved by the pnpm workspace at the repo root, and prebuild's
# own install step would run the package manager from this sub-package. It also suppresses prebuild's
# implicit `pod install`, which we run below ourselves under the UTF-8 locale exported above.
npx expo prebuild --platform "$platform" --no-install

if [ "$platform" = "ios" ]; then
  echo "Installing pods..."
  (cd ios && pod install)
fi

if [ "$platform" = "android" ] && [ -n "$sdk_dir" ] && [ ! -f android/local.properties ]; then
  printf '%s\n' "sdk.dir=$sdk_dir" > android/local.properties
  echo "Restored android/local.properties (sdk.dir=$sdk_dir) - prebuild does not regenerate it."
fi

# Metro's transform cache is content-keyed, but a stale file-map has been known to survive a
# node_modules swap. The archive bundles JS from scratch; make sure it does so from scratch.
find "${TMPDIR:-/tmp}" -maxdepth 1 -name "metro-*" -exec rm -rf {} + 2>/dev/null || true

echo
echo "=============================== BAKED CONFIG ==============================="
node -e '
const { execFileSync } = require("child_process")
const out = execFileSync("npx", ["expo", "config", "--json"], { encoding: "utf8", maxBuffer: 64e6 })
const cfg = JSON.parse(out.slice(out.indexOf("{")))
const apiUrl = cfg.extra && cfg.extra.apiUrl
console.log("  target        " + process.argv[1])
console.log("  version       " + cfg.version)
console.log("  buildNumber   " + (cfg.ios && cfg.ios.buildNumber) + "   (iOS)")
console.log("  versionCode   " + (cfg.android && cfg.android.versionCode) + "    (Android)")
console.log("  extra.apiUrl  " + JSON.stringify(apiUrl))
console.log("  channel       " + JSON.stringify(cfg.updates && cfg.updates.requestHeaders))
// What will actually be bundled, read off disk - not what package.json asks for.
for (const dep of ["@civfix/ui", "@civfix/shared"]) {
  const want = require("./package.json").dependencies[dep]
  const got = require(require.resolve(dep + "/package.json")).version
  console.log(("  " + dep).padEnd(18) + got + "   (package.json wants " + want + ")")
}
if (typeof apiUrl !== "string" || apiUrl !== process.argv[2]) {
  console.error("\n  FAIL: extra.apiUrl is not the string " + process.argv[2] + " - do NOT archive this.")
  process.exit(1)
}
' "$target" "$api_url"
if [ "$platform" = "ios" ]; then
  echo "  Info.plist    $(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' ios/civfix/Info.plist) ($(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' ios/civfix/Info.plist))"
  echo "  Expo.plist    channel=$(/usr/libexec/PlistBuddy -c 'Print :EXUpdatesRequestHeaders:expo-channel-name' ios/civfix/Supporting/Expo.plist 2>/dev/null || echo NONE), runtimeVersion=$(/usr/libexec/PlistBuddy -c 'Print :EXUpdatesRuntimeVersion' ios/civfix/Supporting/Expo.plist 2>/dev/null || echo NONE)"
  echo "  signing team  $(sed -n 's/^[[:space:]]*DEVELOPMENT_TEAM = "\{0,1\}\([A-Z0-9]*\)"\{0,1\};.*/\1/p' ios/civfix.xcodeproj/project.pbxproj | head -1 || true)"
fi
echo "============================================================================"
echo

if [ "$platform" = "ios" ]; then
  cat <<EOF
Ready to archive. Nothing has been built.

  1. open apps/community-mobile/ios/civfix.xcworkspace
  2. scheme "civfix", destination "Any iOS Device (arm64)"
  3. Product > Archive
  4. Distribute App > App Store Connect > Upload

The archive re-derives the app config from .env at build time, so leave .env in place until the
archive finishes. The build number above must be HIGHER than every build already uploaded to App
Store Connect, or the upload is rejected.
EOF
else
  cat <<EOF
Ready to build. Nothing has been built.

  cd apps/community-mobile/android && ./gradlew :app:bundleRelease   # JDK 20 - see README
EOF
fi
